### ISSUE TITLE
Working on Webpack

### ISSUE THREAD

**Issue by SachaG** [VulcanJS/Vulcan#1427]
Here's a list of things I did to [migrate to Webpack](https://github.com/TelescopeJS/Telescope/tree/webpack2), as a reminder to myself. 
- Do not `imply` the `ecmascript` package, instead add it individually to each `nova:*` package (see https://github.com/thereactivestack/meteor-webpack/issues/44). 
- Pass `ReactDOM` to `ReactRouterSSR` and added local copy of the package to fix the `multiple copies of React` issue (see https://github.com/thereactivestack/kickstart-meteor-react-router/issues/83#issuecomment-224975331).
- Add local copy of `meteor-webpack` to enable `resolve.alias` (see https://github.com/thereactivestack/meteor-webpack/pull/218).
- Add `triggerUpdate` to `AccountsField` (see https://github.com/studiointeract/accounts-ui/issues/60)
- Import `datetime.css` from `DateTime.jsx`. 
- Get rid of client-only files (use `Meteor.isClient` instead), for example in `nova-events` package.
- Replace `import Foo from 'meteor/nova:foo'` with `import Foo from 'nova-foo'`. 
- Add `const` to variables (`Foo = "bar"` to `const Foo = "bar"`) everywhere. 
- Create `export.js` and `server.js` files when necessary.

**Comment by SachaG** [comment]
TODO:

- [ ] Figure out `nova-newsletter` bug. 
- [ ] Find solution for email templates (maybe [this](https://github.com/thereactivestack/meteor-webpack/tree/master/packages/assets)?)
- [ ] Fix server-side reloading.
- [ ] Make SSR work.

**Comment by comus** [comment]
hi, @SachaG @xavcz 
perhaps you are not interested in webpack build now, or focus on Telescope 1.0.0 and graphql.
but after i tried,  i found some solutions about this issues.

i created a meteor react tutorial demo, use meteor-webpack to build, and change the project structure like Telescope. so you will understand it easier.
see: https://github.com/comus/todoscope

how to run it
```
git clone
cd .....
meteor npm install
```
for development: `METEOR_PACKAGE_DIRS=meteor_packages meteor`
for production: `METEOR_PACKAGE_DIRS=meteor_packages meteor --production`

the solutions:
- Fix server-side reloading.
use METEOR_PACKAGE_DIRS

- Make SSR work.
in your telescope:webpack2 
see: https://github.com/TelescopeJS/Telescope/blob/webpack2/src/server.js
may be you forgot require `base-components`, so SSR not work

**Comment by xavcz** [comment]
Waow @comus, great job!!

I believe we'll migrate to Webpack, or offer an easy path to do it, at some point after gathering feedbacks on the GraphQL API.

What do you think @SachaG?

**Comment by comus** [comment]
there are also someone use webpack and meteor too
> Crater
> A new app skeleton for Meteor/React
> Meteor/Webpack/React SSR app skeleton that runs your app code outside of Meteor Isobuild
> https://github.com/jcoreio/crater

**Comment by SachaG** [comment]
Nice! I'll have to look at this in more detail, but basically my conclusion was that I didn't want to depend on the `meteor-webpack` package, and that we'd probably wait until we switch out of Meteor completely to migrate to Webpack. 

That being said if there's a good way to migrate to Webpack now while remaining on Meteor, why not. Anything we can do to smoothen the transition is good! :)

**Comment by jpmelnik** [comment]
What's the status about Webpack and Vulcan?

Great job. Thanks!

**Comment by SachaG** [comment]
No real plans for now, we're waiting to see how Meteor's build tool evolves since a lot of new improvements are announced for 1.5.

**Comment by iamrommel** [comment]
I'm interested with webpack/gulp and npm combo for modular app development.
It has the same concept/architecture as vulcan, but rather than meteor it's
webpack/gulp, and rather than atmosphere it's npm. I'm also hesitant to
start because im looking for what meteor can offer next

**Comment by hakimelek** [comment]
Does this mean deprecating meteor build tool?

**Comment by meteorplus** [comment]
You can't get rid of Isobuild from meteor unless you move from Meteor but I think it's not worth it since as Sacha said Meteor have made some really good speed improvements.

**Comment by eric-burel** [comment]
Closing as we would basically need more work on the Meteor side for this, or moving away from Meteor. Storybook provides an experimental example of using Vulcan with Webpack. It's based on naming conventions to find each package client-side code, and scraps out Meteor specific code that can't be imported correctly.

Next step would be loading some Vulcan package in a Next app for example.
