### ISSUE TITLE
Opensource theme to showcase a grid layout

### ISSUE THREAD

**Issue by xavxyz** [VulcanJS/Vulcan#1464]
This is a [starter issue](http://hood.ie/blog/starter-issues.html), _highly inspired_ by the great job of the folks at [Hoodie](http://hood.ie/blog/starter-issues.html). 👍 
### 🎃🙀👕🔭😻 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. 

We are sure you can learn a cool trick or two in the process on how to hack & customize Telescope Nova! 🔭
### 🤔 What you will need to know

Meteor, React, Telescope Nova structure ([short videos to get started](https://www.youtube.com/watch?v=-F6ZHZuVOfk&index=4&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB))
### 🎯 The Goal

Remember [Zeiss](https://www.smashingmagazine.com/wp-content/uploads/2015/09/03-screenings-original-opt.png) from Legacy? This issue is inspired by this issue #786 👍 

**edit:** someone already claimed this issue, but if you also want to create a theme, tell us!! let's build awesome themes! 😄 

This would be interesting to have another theme that people can install and modify directly! This would be like a super-_my-custom-package_ but focused on extending `base-components` and adding new styles. 

By being built as an extension of `nova:base-components` (and so being dependent on it), we would still have access to all the components methods and only the `render()` methods would change 🤖 

To install it, we would just have to disable `nova:base-styles` and add this new package.

Up to you on what it looks like! :art:

ps: you might even use [Rebass](http://jxnblk.com/rebass/) if you don't feel to design every thing (#1271) :octocat: 
### 📋 Step by Step

**Working on your first Pull Request?** You can learn how from this _free_ series [How to Contribute to an Open Source Project on GitHub](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github).

---
### 📋 Step by Step
- [x] Claim this issue (@estevanjantsk, @ananthamapod, .. opened to others too -> you?)
- [ ] Fork the repo, [setup repository locally](https://github.com/TelescopeJS/Telescope#getting-started) and checkout on `devel` branch.
- [ ] Create a custom package `you:nova-the-name-of-your-theme` in `/packages`, init it as an independent Git repository and add it to `.meteor/packages`.
- [ ] Build your theme! 🎨 ⚡️ 
- [ ] Modify `README.md` of Telescope Nova to link to your package's GitHub repository.
- [ ] Open a PR to `devel` branch, mentioning this issue.
- [ ] Someone else: review & merge! 🎉
  Ping us here, in the [Telescope Slack room](http://slack.telescopeapp.org) or on [Twitter](https://twitter.com/telescopeapp) if you have any questions 😉

**Comment by estevanjantsk** [comment]
Hey, can I get this issue? :+1:

**Comment by xavcz** [comment]
Hey @estevanjantsk! Sure, keep us up to date on your progress there! 👍 

*To someone interested in making a theme too, tell us there!! We'll also add you to the list of opensource custom themes!! Let's build awesome stuff* 🚀 :art:

**Comment by ananthamapod** [comment]
Hey there! I would love to work on this issue too :smile:

**Comment by xavcz** [comment]
Awesome!

@estevanjantsk @ananthamapod don't hesitate to come by the Slack room too: http://slack.telescopeapp.org 👍

**Comment by xavcz** [comment]
Anyone want to give a try with the Apollo version?

Hints:
- 🚀 Apollo version is on `devel`: http://github.com/TelescopeJS/Telescope/devel 
- 📑 The docs are pretty explicit to help customization: http://nova-docs.telescopeapp.org 
- 💅 Styling didn't change from before

**Comment by vipinlahoti** [comment]
@xavcz Let me in,
Currently I'm working on my personal project which uses Apollo version. I can manage to create a custom UI package.

**Comment by eric-burel** [comment]
Closing as stale (or maybe even historical ;) )
