### ISSUE TITLE
Redirection to homepage from search results list

### ISSUE THREAD

**Issue by juliancwirko** [VulcanJS/Vulcan#1564]
Hi, I think there is a bug. When we search something and after that when we click comments link to be able to go to post view and comment it, there is a redirection to the homepage. You can see it even on https://crater.io Try to search something and click on "No comments" link. 

Also I get a feeling that performance isn't so great as I thought ;) I mean when I click 'load more' button I need to wait almost 8 seconds, the same is when I want to filter by category. In this case it is worst because there isn't a loader. I don't know if this is just me and my server or maybe someone else has this too. I have only 40 posts in the database at the moment. Just saying, maybe you'll be able to find some improvements.

**Comment by SachaG** [comment]
I'm not sure why that's happening on Crater, but I haven't been able to replicate that issue on the latest `devel`. What version of Nova are you running?

As for the performance issue, it's really hard to tell without knowing more. What's your server configuration?

**Comment by juliancwirko** [comment]
Ok, I'll try to debug this more, maybe I'll be able to post some more specific information about it. 

Regarding server, it is standard Digital Ocean droplet and free mLab mongo db hosting. Maybe this is the problem.

**Comment by eric-burel** [comment]
Closing as stale
