### ISSUE TITLE
SSR Error makes the page to reload

### ISSUE THREAD

**Issue by urupvog** [VulcanJS/Vulcan#1591]
I installed the latest version of telescope app and edited it for my purpose . However, I see a weird problem since beginning. Whenever I visit the home page, it loads twice. chrome shows a SSR Error in console. I am copying the error verbatim below.
Link of my app - http://cillyhunt.cillypoint.com

Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <div class="spinner" data-reactr
 (server) <div class="wrapper" id="wrapper

Any help would be appreciated. Thanks

**Comment by SachaG** [comment]
I think those two problems might be unrelated, because I get the SSR warning locally when I work on the app, but I don't get the reloading behavior some people have reported. I'm still looking into that. 

And I'm not seeing either problem on http://cillyhunt.cillypoint.com/ actually? What browser are you using?

**Comment by urupvog** [comment]
You are correct. My fault. The SSR warning isnt coming(It comes on my localhost and I mistakenly thought to be production).

However, the double loading still happens. I use Chrome on Mac, iOS and Android.

**Comment by urupvog** [comment]
Update: Double loading isnt happening everytime. Too difficult to trace it. Usually, it happens when the page loads and user starts scrolling.

**Comment by urupvog** [comment]
Still facing the page loading issue, any help?

**Comment by SachaG** [comment]
Are you using those latest version of Vulcan? Anything else you can tell us about what's triggering the problem?

**Comment by urupvog** [comment]
I am using Telescope Nova, I don't see this issue in the application examples available with Nova, but this has been the problem with my application since the beginning. This always happens on the first load of cillyhunt and the users are finding it difficult.

**Comment by SachaG** [comment]
I'm sorry but Telescope Nova isn't supported anymore, I would recommend updating to the latest version of Vulcan.
