### ISSUE TITLE
Unable to load settings.json file on Heroku

### ISSUE THREAD

**Issue by xeoneux** [VulcanJS/Vulcan#1602]
I've cloned the repository over at https://github.com/HelloMeets/HelloMakers with script to generate `settings.json` file from environment variables.

It uses https://github.com/AdmitHub/meteor-buildpack-horse and runs well... It works like the demo hosted at http://demo.telescopeapp.org and does not read the `settings.json` file.

I've made sure that the settings file exists on the server with the validated JSON and correct values. It works locally as well but not over at Heroku. I can't seem to pinpoint where the problem lies.

**Comment by xeoneux** [comment]
Moved to Google Cloud Platform...

**Comment by kamish24six** [comment]
try: heroku config:set METEOR_SETTINGS="$(cat settings.json)"
