### ISSUE TITLE
Load more don't load more than 100 documents

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan#1604]
Hi,

We have 2,429 documents (record) in our database but the load more don't load more than 100 documents. How can we change this 100 limit ?

Please check it on our website https://adalidda.com

We use VulcanJS version 1.2.

Thank You
Adalidda

**Comment by SachaG** [comment]
See here: https://github.com/TelescopeJS/Telescope/blob/devel/packages/vulcan-posts/lib/resolvers.js#L26

You can use `GraphQLSchema.addResolvers()` to overwrite that resolver. That's not very well documented right now so let me know if you need more info.

**Comment by adalidda** [comment]
Thank You so much Sacha.

Is it possible to have our websites add to the list of website powered by VulcanJS ?
https://adalidda.com (English)
https://fr.adalidda.com (French)

Thank You
Adalidda
