### ISSUE TITLE
How can i ensure that the user has logged in first before navigating to specific route

### ISSUE THREAD

**Issue by iamrommel** [VulcanJS/Vulcan#1606]
Let say i have the route "/setting/adminOnly", when my user copy paste the URL to their browser, i should have the logic to that the user needs to login first before going to this route (if he is not logged in yet).

But i don't know where to put this ensurelogin logic, iron-router has that feature, i'm not sure how it should be implemented in vulcanjs. Any thoughts/hint?

**Comment by SachaG** [comment]
I would do that check inside the React component and redirect in the `componentDidMount` callback. 

React-Router might have a route callback feature, but I'm not sure if it would work inside Vulcan…

**Comment by meteorplus** [comment]
@iamrommel check this out https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Redirect.md

**Comment by iamrommel** [comment]
I like the implementation here https://medium.com/the-many/adding-login-and-authentication-sections-to-your-react-or-react-native-app-7767fd251bd1
specially the EnsureLoggedInContainer, i just that I'm not sure how to create child route of specific path.

If only I can have something like this
```
addRoute({name: 'app', path: '/app', componentName: 'EnsureLogin'});
addChildRoute('app', { {name: 'app.workorder', path: '/app/workorder', componentName: 'Layout'}}  )

```
that will create the child of existing route 'app', which will generate a react-router route like this

```
 <Route component={EnsureLogin}>
    <Route path=”/app/workorder” component={Layout}/>
  </Route>

```

I can have the flexibility to define in my route which should be private and public. Which i guess a good addition in vulcan:routing.

I hope I can make a PR for this.

**Comment by iamrommel** [comment]
This addChildRoute will be helpful also if we want to define sub-routes in our route.

**Comment by SachaG** [comment]
I don't think I've used child routes before. What's the difference between:

```
addRoute({name: 'app', path: '/app', componentName: 'EnsureLogin'});
addChildRoute('app', { {name: 'app.workorder', path: '/app/workorder', componentName: 'Layout'}}  )
```

and

```
addRoute({name: 'app', path: '/app', componentName: 'EnsureLogin'});
addRoute({name: 'app.workorder', path: '/app/workorder', componentName: 'Layout'})
```

?

**Comment by iamrommel** [comment]
Yep, there is no child route yet, that is the name of method what i'm thinking to implement.

I planned to create a route that is child of a parent route and so 'app' (EnsureLogin) is the parent and 'app.workorder' (Layout) is the child thereby creating a route like this

```
<Route name="app" component={EnsureLogin}>
    <Route name="app.workorder" path=”/app/workorder” component={Layout}/>
  </Route>

```

Oh,  On the second thought, i haven't tried if

```
addRoute({name: 'app', path: '/app', componentName: 'EnsureLogin'});
addRoute({name: 'app.workorder', path: '/app/workorder', componentName: 'Layout'})

```
will generate the same react-route route as shown above.

**Comment by SachaG** [comment]
I guess the difference with child routes is that you can specify a `{this.props.children}` prop that works as a nested layout? But I don't know if you need that feature in this specific case?

**Comment by iamrommel** [comment]
The nested layout indeed is what i need. That EnsureLogin component can have the specific styles and logic and that will be the base for it's children. For this instance, i can check if the user was logged in from ComponentDidMount (as you suggested earlier to do the logic/check on component level).  Aside from that, i can put more UI customization for certain route only. 

```

import React from 'react';
import {browserHistory} from 'react-router'
import {withCurrentUser, registerComponent} from 'meteor/vulcan:core';


class EnsureLogin extends React.Component {
    componentDidMount() {
        const {currentUser} = this.props;
        if (!currentUser) {
            browserHistory.replace("/login")
        }
    }

    render() {
        const {currentUser, children} = this.props;
        if (currentUser) {
            return children
        } else {
            return null
        }
    }
}

EnsureLogin = withCurrentUser(EnsureLogin);
registerComponent('EnsureLogin', EnsureLogin);

```

**Comment by SachaG** [comment]
That makes sense. I would accept a PR to add `addChildRoute` if you can do it then :)

**Comment by dshitik** [comment]
This is an important thing. I support the author and look forward to working with the child routes correctly.

**Comment by SachaG** [comment]
This was actually added a while back. I just updated the docs: http://docs.vulcanjs.org/routing.html

**Comment by dshitik** [comment]
Not worked if i do like this:

addRoute({name: 'main', path: '/', component: MainLayout});
addRoute({name: 'home', path: '/home', component: Home}, 'main');
addRoute({name: 'about', path: '/about', component: About},'main');

i get - Sorry, we couldn't find what you were looking for.
