### ISSUE TITLE
Issues with Examples

### ISSUE THREAD

**Issue by rahulkgupta** [VulcanJS/Vulcan#1607]
It's unclear based on the docs whether there is an Example-Forum example or not.

Also the customization-example's styling seems to be off when comparing the documentation (video within the doc) and the actual page.
<img width="630" alt="screen shot 2017-04-06 at 11 31 01 am" src="https://cloud.githubusercontent.com/assets/610372/24769801/a040bf5e-1abc-11e7-9863-93f22df97dfd.png">

**Comment by SachaG** [comment]
There is an `example-forum` example: 

https://github.com/TelescopeJS/Telescope/tree/devel/packages/example-forum

I'll try to clarify the docs. 

I'm not sure why your styles wouldn't be loading though, sorry… Any more info?

**Comment by valgalin** [comment]
Did you uncomment the vulcan-base-styles found in .meteor/packages?

**Comment by rahulkgupta** [comment]
I do not believe I did, but I just pulled the latest branch and did a `meteor reset` and things seem to be working fine.
