### ISSUE TITLE
How can I rename a schema fieldName or change value?

### ISSUE THREAD

**Issue by vipinlahoti** [VulcanJS/Vulcan#1611]
I want to change the max value to lets say as max: 100 for vulcan:posts > schema
```
title: {
    ...
    max: 500,
}
```

Also I want to rename "body" to "content"
```
body: {
    ...
    max: 3000,
}
```

How can I do this?

Thank you

**Comment by SachaG** [comment]
You can change the `title` field by adding a new custom field with the same name (`title`). The new field will replace the old. 

You can't change the name of an existing field, so you'll have to delete it and add your own new field separately.
