### ISSUE TITLE
Unable to create/edit Posts Master & devel branch

### ISSUE THREAD

**Issue by manriquef** [VulcanJS/Vulcan#1614]
The latest Master and devel branch is throwing an error when trying to create a new post or edit a post. I suspect it is something to do with SmartForms, but not entirely sure..

modules.js?hash=0dc72b1…:34697 Uncaught TypeError: Cannot convert undefined or null to object
    at from (native)
    at exports.default
    at FormComponent.renderComponent (http://localhost:3000/packages/vulcan_forms.js?
    at FormComponent.render (http://localhost:3000/packages/vulcan_forms.js?
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext 
    at ReactCompositeComponentWrapper._renderValidatedComponent 
    at ReactCompositeComponentWrapper.performInitialMount 
    at ReactCompositeComponentWrapper.mountComponent 
    at Object.mountComponent
    at ReactDOMComponent.mountChildren

**Comment by SachaG** [comment]
How about now?

**Comment by SachaG** [comment]
(if you pull again)

**Comment by manriquef** [comment]
Works perfectly now!, what was the solution?

**Comment by SachaG** [comment]
Posts.statuses wasn't defined yet: 

https://github.com/VulcanJS/Vulcan/commit/a815dca0a2610fff60e5c1e2d8cd3e9327b910fe
