### ISSUE TITLE
React-Bootstrap 3 based minimalist theme for Vulcan

### ISSUE THREAD

**Issue by vipinlahoti** [VulcanJS/Vulcan#1618]
React-Bootstrap 3 based minimalist theme for Vulcan,
Any ideas are welcome:

https://github.com/vipinlahoti/vulcan-boot

<img src="https://s3.ap-south-1.amazonaws.com/grudr/vipi.nsl2787%40gmail.com/FireShot+Capture+34+-+Vulcan+-+http___localhost_3000_.png" width="500">

<img src="https://s3.ap-south-1.amazonaws.com/grudr/vipi.nsl2787%40gmail.com/FireShot+Capture+35+-+Read+This+First+%F0%9F%8E%88_+-+http___localhost_3000_posts_WZWK7T.png" width="500">

**Comment by SachaG** [comment]
Really cool! I'll give it a try tomorrow :)

**Comment by SachaG** [comment]
Nice work! Just one small thing, the `vulcan:xyz` namespace is reserved for official Vulcan packages. So you should name your package using your own [Atmosphere](http://atmospherejs.com/) username, something like `vipinlahoti:boot` or `vipinlahoti:vulcanboot`.

**Comment by vipinlahoti** [comment]
Package name changed to vipinlahoti:vulcan-theme-mini
