### ISSUE TITLE
Instagram Error: "ID is required"

### ISSUE THREAD

**Issue by masterminding** [VulcanJS/Vulcan#1622]
Leaving a comment or uploading an image yields the error `ID is required` even after doing `meteor reset`.
<Enter>
![screen shot 2017-04-19 at 5 34 41 pm](https://cloud.githubusercontent.com/assets/12018689/25203255/872ebfe2-2526-11e7-92f6-6edcc4dbf58d.png)
<Enter>
![screen shot 2017-04-19 at 5 29 50 pm](https://cloud.githubusercontent.com/assets/12018689/25204471/9f92a2a6-252b-11e7-9621-5deed5c01c78.png)

**Comment by SachaG** [comment]
Fixed.
