### ISSUE TITLE
Telescope install still instructs to clone telescope/telescope

### ISSUE THREAD

**Issue by janat08** [VulcanJS/Vulcan#1625]
React has 5 month of development over legacy, any chance it would be possible to iterate their difference in features?

**Comment by SachaG** [comment]
Sorry I'm not sure what you mean? Are you talking about React, or about Vulcan?

**Comment by janat08** [comment]
I meant nova telescope instructs to install from telescope/telescope, and was asking if there're major features amiss between two?

**Comment by SachaG** [comment]
I just renamed the repo, so there is no difference between the contents of either URL.
