### ISSUE TITLE
Mailchimp initialization error

### ISSUE THREAD

**Issue by HelloMakers** [VulcanJS/Vulcan#1626]
I'm getting the following error in the JS console: 

```
Error: GraphQL error: {"id":"newsletter.subscription_failed"}
    at new t (7c0a38f….js?meteor_js_resource=true:28)
    at 7c0a38f….js?meteor_js_resource=true:28
    at 7c0a38f….js?meteor_js_resource=true:3
```

Have the right Mailchimp API and List ID keys

**Comment by SachaG** [comment]
If you're on the `devel` branch (which has a refactored version of the newsletter package), you can try calling `Newsletters.subscribeUser` and `Newsletters.subscribeEmail` directly from the Meteor shell (`meteor shell`) to see what the actual error is.
