### ISSUE TITLE
Not work correctly route

### ISSUE THREAD

**Issue by dshitik** [VulcanJS/Vulcan#1629]
Not worked route if i do like this:

addRoute({name: 'main', path: '/', component: MainLayout});
addRoute({name: 'home', path: '/home', component: Home}, 'main');
addRoute({name: 'about', path: '/about', component: About},'main');

if follow route home or about page, i get :
 Sorry, we couldn't find what you were looking for.

**Comment by dshitik** [comment]
It happened when parentRoute is index route - '/'
If to correct:
addRoute({name: 'main', path: '/qwe', component: MainLayout});
addRoute({name: 'home', path: '/home', component: Home}, 'main');
addRoute({name: 'about', path: '/about', component: About},'main');
its will be work, but that's not what I need.

**Comment by SachaG** [comment]
yes, you can't add child routes to the `/` route since all routes except `/` are already child routes of `/`.
