### ISSUE TITLE
Please explain how to use the new settings useSegment and segmentWriteKey in VulcanJS 1.4

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan#1637]
Hi,

In VulcanJS 1.4, I notice 2 new settings "useSegment" and "segmentWriteKey". Could you please explain the purpose and how to use them ?

Thank You
Adalidda

**Comment by SachaG** [comment]
I think @xavcz wrote this code, but it's probably for using https://segment.com/

I imagine you have to set `useSegment` to `true` and then add you segment API key in `segmentWriteKey`?

**Comment by xavcz** [comment]
Exactly as Sacha said. You may not want to send everything to segment even if you have the key set (dev / prod environments). 

Feel free to open a PR to change the API if you feel it's unclear 😊

**Comment by adalidda** [comment]
Thank You Sacha and @xavcz
