### ISSUE TITLE
Little error in VulcanJS 1.4 vulcan-core/lib/modules/containers/withList.js 

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan#1639]
instead of
  const { collection, limit = 10, pollInterval = 20000 } = options,

should write

  const { collection, limit = getSetting('postsPerPage', 10), pollInterval = 20000 } = options,

Hope that help.
Adalidda

**Comment by xavcz** [comment]
Can you do a PR for that @adalidda please? 👍

**Comment by adalidda** [comment]
Sure @xavcz . Will do it this week-end as I need to be familiar how to do it with Github first.

Thank You
Adalidda
