### ISSUE TITLE
Type not found in document [Error]

### ISSUE THREAD

**Issue by jpmelnik** [VulcanJS/Vulcan#1643]
I created the "Invoices Collection".

```
import { createCollection } from 'meteor/vulcan:core';
import schema from './schema.js';
import resolvers from './resolvers.js';
import mutations from './mutations.js';

const Invoices = createCollection({
  collectionName: 'Invoices',
  typeName: 'Invoice',
  schema,
  resolvers,
  mutations,
});

export default Invoices;

```

When I add "mutations" I'm getting the following error:

> Error: Type "InvoicesInput" not found in document.

I reviewed other packages and I can't found something related with GraphQL Types.

Here two links with related information:
[Link #1](https://github.com/orionsoft/meteor-apollo-accounts/issues/44)
[Link #2](https://github.com/graphql/graphql-js/issues/497)

Should I define Types? Where?

I found that in "vulcan:lib"/ collections.js at line 161

```
GraphQLSchema.addMutation(`${mutations.new.name}(document: ${collectionName}Input) : ${typeName}`);

```

In "vulcan:lib"/ graphql.js at line 160 I'm getting:

```
type Invoice {
        _id: String
  name: String
  isVisible: Boolean
  createdAt: Date
  updatedAt: Date
  userId: String
  user: User
      }

```

Thanks

**Comment by SachaG** [comment]
You can review your schema with `meteor shell` and then `Vulcan.getGraphQLSchema()`. This should show you what input types are available. `InvoicesInput` is supposed to be generated automatically for you, I'm not sure why it wouldn't be…

**Comment by jpmelnik** [comment]
Thanks.

I'm reviewed the schema with meteor shell and Vulcan.getGraphQLSchema().

I found type "User" and type "Invoice" but nothing about "InvoicesInput".

**Comment by SachaG** [comment]
One reason why you might not have any `InvoicesInput` type is if none of your fields are marked as insertable or editable? (`insertableBy` and `editableBy`)

**Comment by jpmelnik** [comment]
Yes. Thanks You.

Right Now I reading...

> One more thing! By default, all schema fields are locked down, so we need to specify which ones the user should be able to insert as part of a “new document” operation.
> 
> Once again, we do this through the schema. We’ll add an insertableBy property to any “insertable” field and set it to [members] to indicate that a field should be insertable by any member of the members group (in other words, regular logged-in users):

Thanks.

**Comment by xyx2011** [comment]
This is so useful! Thanks!
