### ISSUE TITLE
Multiupload support?

### ISSUE THREAD

**Issue by j-jackson** [VulcanJS/Vulcan#1649]
I have had a look at [vulcan-cloudinary](https://github.com/VulcanJS/Vulcan/tree/master/packages/vulcan-cloudinary), [vulcan-forms-upload](https://github.com/VulcanJS/Vulcan/tree/master/packages/vulcan-forms-upload) & the Instagram example app, but I cant see how to enable multi upload. Is multi upload not supported?

**Comment by SachaG** [comment]
The upload feature available is pretty specific, it's really only for uploading a single image to Cloudinary. If you want something else you'll have to create it yourself, sorry.
