### ISSUE TITLE
/reset-password/:token does not display input form

### ISSUE THREAD

**Issue by daniloc** [VulcanJS/Vulcan#1650]
This is a freshly cloned install of Vulcan with #example-forum enabled. 

I can initiate a password reset from the login form. When I follow the link from the resulting email, for example:

    http://10.0.1.191:3000/reset-password/3iUIay80lX9lfGvELgpH5-k1fUPF7YW4nu1h4j8_j5x

I end up at the appropriate page but without the new password input field or submission button:

![screenshot 2017-06-13 00 10 57](https://user-images.githubusercontent.com/213358/27065766-4c773e34-4fcd-11e7-99cb-68b83032d922.png)

Any advice on restoring this functionality? Thanks.

**Comment by SachaG** [comment]
That should be handled by the accounts package, which was adapted from [accounts-ui](https://atmospherejs.com/std/accounts-ui). Maybe it's missing the route or something?

**Comment by daniloc** [comment]
The route appears to be there, in the accounts package, but even when I explicitly re-add it in my own package, it doesn't seem to make a difference. Hmmmm. I'll keep spelunking. Let me know if any other thoughts occur to you in this!

**Comment by SachaG** [comment]
Should be fixed via https://github.com/VulcanJS/Vulcan/commit/08277e1a9943217a533b7c8158b304de80a1c84a
