### ISSUE TITLE
In latest commit 5f95749 Load More don't load post

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan#1652]
Hi,

In the latest commit 5f95749 Load More don't load post.
As I suspect the bug have something related to the message:
npm WARN deprecated graphql-server-core@0.6.0: critical bug related to GET queries fixed in v0.8.1
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

so I update package.json to use
"graphql-server-express": "^0.8.5",

instead of "graphql-server-express": "^0.6.0",

but unfortunately, the bug remain !

Any idea, how to fix this bug ?

Thank You
Adalidda

**Comment by SachaG** [comment]
Do you have any errors in the browser console?

**Comment by adalidda** [comment]
Hi Sacha,

I test it with the example-forum 1.5.0 package as is (no customization code).

After I type npm start, I got the following message:
W20170619-20:08:07.563(7)? (STDERR) Warning: Accessing PropTypes via the main React package is deprecated, a
nd will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
W20170619-20:08:07.777(7)? (STDERR) Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
W20170619-20:08:17.530(7)? (STDERR) Warning: fragment with name UsersCurrent already exists.
W20170619-20:08:17.532(7)? (STDERR) graphql-tag enforces all fragment names across your application to be unique; read more about
W20170619-20:08:17.534(7)? (STDERR) this in the docs: http://dev.apollodata.com/core/fragments.html#unique-names

=> Started your app.

=> App running at: http://localhost:3000/

Then VulcanJS run normally and I got the list of post. But when I click on Load More, the App don't load any post and still display 10/2902 (I have 2902 posts in my mongodb).

There are no message displayed on the console after I click on Load More !

Any idea ?

PS:
1. If that could help, I can create an access (new user name and password) to a copy of our production mongodb for you.
2. You can view the working version of Load More on the current version of our website (based on VulcanJS version 1.3) at https://adalidda.com

Thank You
Adalidda

**Comment by SachaG** [comment]
I just tried the latest master and the load more button seems to work for me. So I'm not sure what's going on, sorry…

**Comment by adalidda** [comment]
Dear Sacha,

I am able to fix the bug by:
1. Install core-js package with the command
meteor npm install --save core-js
2. upgrade npm to npm 5.0.3
npm i -g npm

Hope that give you the indication how to include these information to the general package.

Thank You
Adalidda

**Comment by adalidda** [comment]
Hi Sacha,

The bug is related to MeteorJS 1.5. I found the Explanation below at https://tweakers.net/downloads41227/meteor-15.html

The ecmascript-runtime package, which provides polyfills for various new ECMAScript runtime APIs and language features, has been split into ecmascript-runtime-client and ecmascript-runtime-server, to reflect the different needs of browsers versus Node 4. The client runtime now relies on the core-js library found in the node_modules directory of the application, rather than a private duplicate installed via Npm.depends. This is unlikely to be a disruptive change for most developers, since the babel-runtime npm package is expected to be installed, and core-js is a dependency of babel-runtime, so node_modules/core-js should already be present. If that's not the case, just run meteor npm install --save core-js to install it.

Hope this information to other people.

Thank You
Adalidda

**Comment by SachaG** [comment]
Thanks! I definitely had no idea about this issue… Hopefully it'll help others if they run into this.
