### ISSUE TITLE
[Feature] Reactive Data HigherOrderComponent

### ISSUE THREAD

**Issue by Twisterking** [VulcanJS/Vulcan#1656]
I think a very awesome feature would be to have something similar to MDGs `createContainer()` function.
Of course, instead of using Meteor's default pub/sub, the Vulcan equivalent would subscribe to a GraphQL endpoint and also be fully reactive. And like the `withList` component, it would put the results into a `result` prop any maybe also offer a boolean `loading` prop to display loading spinners and all that, if the user decides to do so.

I really think a feature like this would make many Meteor devs out there think about switching to Vulcan and in general it would greatly enhance the multitude of apps which can be built by using Vulcan as a framework.
If you also would love to see this feature in a future version of Vulcan please feel free to upvote. (I hope this is okay - I already spoke to @SachaG in the Slack channel)

**Comment by eric-burel** [comment]
See https://github.com/VulcanJS/Vulcan/issues/1653
