### ISSUE TITLE
Google Tag Manager with VulcanJS

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan#1657]
Hi,

I am not sure if VulcanJS have a component to manage Google Tag Manager. 

By using, npm package react-google-tag-manager, I just successfully be able to use Google Tag Manager with VulcanJS.

I suggest to add this component to the default VulcanJS package as tracking visitors behaviour is very important.

Thank You
Adalidda

**Comment by SachaG** [comment]
I think this would work great as a third-party package :)
