### ISSUE TITLE
Validation error messages broken in vulcan-accounts

### ISSUE THREAD

**Issue by martinspain** [VulcanJS/Vulcan#1658]
I have an issue with validation error messages not being shown correctly on the signin/signup form. I'm pretty new to React/Meteor/VulcanJS and I've done my best to dig around in the code and Google a solution, but sadly I've not been able to resolve this.

When the signin/signup form is submitted with empty fields, instead of the localised error messages being shown, the key for the localised string is displayed instead. For example, instead of saying "Username required" it displays "accounts.error_username_required". This is true for all validation error messages for this form.

I've traced it back to the helpers.js file in vulcan-accounts, which calls the `showMessage` method with the error string key directly:

`showMessage("accounts.error_username_required", 'warning', false, fieldName);`

All other usage of the `showMessage` method appears to fetch the correct translated string first using a call to `formatMessage`. For example, LoginForm.jsx calls it like this:

`this.showMessage(this.context.intl.formatMessage({id: 'accounts.info_password_changed'}), 'success', 5000);`

Is this a bug, or have I got something misconfigured in my project? 

I have tried to resolve this myself, but I'm still learning my way around the Meteor/VulcanJS frameworks and can't seem to figure out the right way to import the formatMessage functionality into the vulcan-accounts helpers.js file.

**Comment by SachaG** [comment]
Sorry about that, it's likely a bug. The accounts code was adapted from another package and a few issues crept in when I refactored that code. Like you said, it should be `showMessage(formatMessage(string))` instead of `showMessage(string)`.

**Comment by acidsound** [comment]
I fixed it. please check it out ⚡️

**Comment by martinspain** [comment]
Now fixed.
