### ISSUE TITLE
[Resolved, but  with possible security hole] Cordoba client can't access http://xx.xx.xx.xx:3000/graphql. Apollo server CORS config problem

### ISSUE THREAD

**Issue by juanmafont** [VulcanJS/Vulcan#1662]
I'm trying to launch Vulcan from android mobile.

But I got an error into javascript remote client console:

   OPTIONS http://192.168.43.20:3000/graphql 405 (Method Not Allowed)

Note:  android/Cordova apk client was compile using below command.
meteor build ../out_apk --debug --verbose --server=http://192.168.43.20:3000

I think maybe is a bug like comment here -> https://github.com/apollographql/apollo-client/issues/529

 But I can not find into Vulcan code the way to pass to createApolloServer() function CORS options to enable it from an external ip or server.

![screenshot_2017-07-03_17-22-34](https://user-images.githubusercontent.com/6154911/27799893-4e500858-6017-11e7-8d7b-28b72038c6ed.png)

**Comment by juanmafont** [comment]
Resolved ¡¡¡¡¡

  Adding cors npm package https://www.npmjs.com/package/cors
  `npm install cors`

and modify packages/vulcan-lib/lib/server/apollo_server.js

  add
`import cors from 'cors';`

modify line:
`const graphQLServer = express();`
with
`const graphQLServer = express().use('*', cors());`

Now Cordoba/Android client runs.

NOTE: I think that **cors** using '*' is a opened security hole, maybe reading options to using with **cors** from another vulcan config file will be good.

**Comment by eric-burel** [comment]
Hi,

The weird part is that on Cordova request are sent to an IP that is'nt localhost, can this be solved ?

**Comment by SachaG** [comment]
Maybe we could also ask MDG directly how to properly configure Apollo server to work with Meteor+Cordova?

**Comment by Sebi55** [comment]
Maybe this is not the greatest solution but setting cors to "*" is a bad idea because some warnings are thrown at least for me.

I went with this solution:

```
var whitelist = ['http://localhost', 'https://example.io','https://www.example.io']
var corsOptionsDelegate = function (req, callback) {
  var corsOptions;
  if (whitelist.indexOf(req.header('Origin')) !== -1) {
    corsOptions = { origin: true } // reflect (enable) the requested origin in the CORS response
  }else{
    corsOptions = { origin: false } // disable CORS for this request
  }
  callback(null, corsOptions) // callback expects two parameters: error and options
}

// createApolloServer
const createApolloServer = (givenOptions = {}, givenConfig = {}) => {
  const graphiqlOptions = { ...defaultConfig.graphiqlOptions, ...givenConfig.graphiqlOptions };
  const config = { ...defaultConfig, ...givenConfig };
  config.graphiqlOptions = graphiqlOptions;

  const graphQLServer = express().use('*', cors(corsOptionsDelegate));
```
This is done when the apollo server is started.

**Comment by eric-burel** [comment]
We now have a cors setting, either enabling all (public api) or a whitelist of domain

```
  "apolloServer": {
    "corsWhitelist": [],
    "corsEnableAll": false
  }
```
