### ISSUE TITLE
Is Vulcan A good platform for a social network with tens of thousands of users?

### ISSUE THREAD

**Issue by shmulikkaminker** [VulcanJS/Vulcan#1668]
Who has experienced it, how good are the performance? Is it suitable for sites with hundreds of thousands of users?

**Comment by SachaG** [comment]
I can't really answer this because I don't think anybody has used Vulcan to build a site this large yet. All I can say is that I don't see any obvious reasons why you couldn't use it for a large site.

**Comment by vipinlahoti** [comment]
@kamish24six we are using Vulcan as a base to build internal social community at our office, and at present we have approx 300 users, 2000+ posts, 1000+ images stored, apart from posts Question/answer section also implemented, no down in performance yet.
