### ISSUE TITLE
redirect www request to non-www

### ISSUE THREAD

**Issue by shmulikkaminker** [VulcanJS/Vulcan#1672]
Is it possible? I use herooku. herooku have addaons to this or will I add a function in meteor startup?

**Comment by SachaG** [comment]
This should be done at the DNS level, not at the app level.

**Comment by eric-burel** [comment]
For googlers: this is not always doable at the DNS level if you want a true redirect. In this case you can either setup an nginx server (Meteor Up allows this I think) or use `meteor/webapp` to redirect at the server level.

See https://github.com/lbke/vulcan-http-redirect
