### ISSUE TITLE
TypeError: getDataFromTree is not a function

### ISSUE THREAD

**Issue by valgalin** [VulcanJS/Vulcan#1687]
Hi guys,

I just git cloned new VulcanJS, and I'm getting this warning/error upon running.

TypeError: getDataFromTree is not a function

Although, I can still see the site up in localhost:3000.

**Comment by SachaG** [comment]
Maybe related to https://github.com/apollographql/react-apollo/blob/master/Changelog.md#v071 ?

What version of react-apollo are you using?

**Comment by comus** [comment]
it s ok now with react-apollo 1.4.10
https://github.com/apollographql/react-apollo/issues/926

**Comment by valgalin** [comment]
Hi @SachaG , @comus is right, updating react-apollo to 1.4.10 resolved the issue.

Thank you, guys! :+1:
