### ISSUE TITLE
Error: Depending on unknown package vulcan:forms

### ISSUE THREAD

**Issue by spherop** [VulcanJS/Vulcan#1689]
Just trying out Vulcan for the first time and I am sure I am missing something very basic. But I went through some setup using the cli package - which is excellent and really draws me to the framework...

```
############ Your Packages ############

question-art
# example-simple
```

The app is crashing with
`Error: Depending on unknown package vulcan:forms`

error after I added `core` and `accounts` to the `package.js` file in my own package:

```
  Package.describe({
    name: 'question-art',
  });

  Package.onUse(function(api) {
    api.use([
    // vulcan core
    'vulcan:core',

    // vulcan packages
    'vulcan:forms',
    'vulcan:accounts',
    ]
  );

  api.mainModule('lib/server/main.js', 'server');
  api.mainModule('lib/client/main.js', 'client');
});
```

I can't see much that is different configuration wise between my new package and the example-simple one....

**Comment by SachaG** [comment]
Try deleting your `.meteor/versions` file and restarting, and seeing if that fixes it.

**Comment by spherop** [comment]
Yes!
~Thanks
