### ISSUE TITLE
replaceComponent called after DOM rendering

### ISSUE THREAD

**Issue by acidsound** [VulcanJS/Vulcan#1690]
Hi.
```replaceComponent``` feature is so useful.
I'm writting some themes package with vulcan.
![screen shot 2017-08-03 at 15 06 44](https://user-images.githubusercontent.com/623157/28908387-67869698-785e-11e7-88c6-9fa265ba34e2.png)

but it has some rendering issue.
After refreshing, I can see the following screen in a very short time.

![screen shot 2017-08-03 at 15 06 41](https://user-images.githubusercontent.com/623157/28908818-97d4db6e-7860-11e7-8c3b-c8c5913e13e5.png)

customized stylesheet has applied. but ```replaceComponent``` hasn't.
It feels weird. How can I improve this?
I don't want to see old ```registerComponent``` that changed with ```replaceComponent```.

**Comment by SachaG** [comment]
How/when are you calling `replaceComponent`?

**Comment by acidsound** [comment]
I made my package for vulcanJS and wrote some customComponents using ```replaceComponent```.
like this.
![image](https://user-images.githubusercontent.com/623157/28910797-3c2eac96-7869-11e7-9e17-a8f43aca46be.png)

**Comment by acidsound** [comment]
It works as expected. but I can see also original ```PostsItem``` component. I don't want to see it.

**Comment by SachaG** [comment]
Hmm I can't see much in that screenshot. I don't see where you're calling `replaceComponent` for example. But basically, I would suggest you look at the `example-custom` package and follow the same pattern to replace components.

**Comment by acidsound** [comment]
I got it. studied hard with ```example-customization```as your suggestion.
components import moved from client-side to both-side(client/server).
works perfect! thanks SachaG!

**Comment by SachaG** [comment]
Great :)
