### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined (in newsletter component)

### ISSUE THREAD

**Issue by valgalin** [VulcanJS/Vulcan#1691]
Hi Sacha,

I'm using a modified example-customization package.

And I'm getting this error when submitting an email in the newsletter subscribe form. I'm already using my Mailchimp API and ID in settings.json.

Upon checking console, I think it's referring to `this.state.error.name` in the code below from Newsletter.jsx file:

`async subscribeEmail(data) {
    try {
      const result = await this.props.addEmailNewsletter({email: data.email});
      this.successCallbackSubscription(result);
    } catch(error) {
      const graphQLError = error.graphQLErrors[0];
      console.error(graphQLError); // eslint-disable-line no-console
      const message = this.context.intl.formatMessage({id: `newsletter.error_${**this.state.error.name**}`}, {message: this.state.error.message});
      this.props.flash(message, 'error');
    }
  }`

Please help. Thank you!

**Comment by SachaG** [comment]
It looks like maybe it should be `graphQLError` instead of `this.state.error`. `this.state.error` is probably leftover code from an earlier implementation.

**Comment by valgalin** [comment]
Hi Sacha,

I removed CustomNewsletter.jsx in my custom package. I still can't get to submit an email, and I get a new error in console that says:

`TypeError: Cannot read property 'subscribe' of undefined`

I think it's referring to these lines of code from the newsletter.js file in vulcan-newsletter package:

`Newsletters.subscribeEmail = (email, confirm = false) => {
  console.log(`// Adding ${email} to ${provider} list…`); // eslint-disable-line
  const result = Newsletters[provider].**subscribe**(email, confirm);
  if (result) {console.log ('-> added')}
}`

It did print in the console the first line, for example: `// Adding email@domain-name.com to mailchimp list…`

Thoughts?

**Comment by SachaG** [comment]
Did you add `  "newsletterProvider": "mailchimp",` to your settings?

**Comment by valgalin** [comment]
Hi Sacha,

I added `"newsletterProvider": "mailchimp"` to my settings.json file. However, I still get this error in console:

`TypeError: Cannot read property 'subscribe' of undefined`

**Comment by SachaG** [comment]
It looks like you'll just have to go in there and debug the issue. A PR would be appreciated once you fix it :)

**Comment by valgalin** [comment]
Okay, I will do my best. :)

**Comment by DSoe** [comment]
Hi @valgalin and @SachaG 

It's working fine for me. In settings.json file, you have to have the followings:

`"newsletterProvider": "mailchimp",
  "mailchimp": {
      "apiKey": "your-mailchimp-api-key",
      "listId": "your-mailchimp-listId"
  }`

Thanks

**Comment by valgalin** [comment]
Hi @DSoe 

Thank you! :) That also solved the issue for me.

I just saw this on the docs yesterday, http://docs.vulcanjs.org/newsletter.html#Settings, and was ready to try it today. I guess you beat me to it.

Will close this now.
