### ISSUE TITLE
Custom form with onChange Methods

### ISSUE THREAD

**Issue by kamish24six** [VulcanJS/Vulcan#1692]
It's possible to use a custom form with the traditional methods like "onChange" or "onSubmit"? if so, how i can manage the data?

**Comment by SachaG** [comment]
Yes, you can use the `withNew`, `withEdit`, etc. mutation HoCs to wrap your form component and pass it a mutation. Or you can even write your own GraphQL mutation. I think the Mutations section of the docs should cover all of that: 

http://docs.vulcanjs.org/mutations.html

And here's an example: https://github.com/SachaG/Zensroom/blob/devel/packages/zensroom/lib/components/bookings/BookingsNewForm.js
