### ISSUE TITLE
PeerDB for relational data

### ISSUE THREAD

**Issue by janat08** [VulcanJS/Vulcan#1700]
I thought I'd put it out there. It solves some of the roadmap features and issues.
#1677 and the feature of handling cases where user comments and deletes account. On the whole I think it would get difficult to provide turn key framework which works on imperative api, especially with subscriptions on graphql. PeerDB is thematically meteor business, but I would think that it won't be as expensive while allowing you to funnel away subscription watchers to graphql in easier fashion that is easier to adapt to your needs. I would like to hear about this, even though I only read abstract for graphql.

**Comment by SachaG** [comment]
I don't know anything about PeerDB so I don't really have an opinion on this but obviously if you can get it working with Vulcan that's awesome. It's a bit out of the scope of the current roadmap though so I'll close this for now. Feel free to reopen it if you make any progress on it :)

**Comment by janat08** [comment]
It looks at oplog to give "transactions", the sort of thing people dislike about mongodb especially in social setting of apps. I belief mongodb joins are no better than just querying for two documents.
