### ISSUE TITLE
Understanding Routing in Vulcan

### ISSUE THREAD

**Issue by renganatha10** [VulcanJS/Vulcan#1704]
Hi I am trying to understand the routing Mechanism in Vulcan. I find it odd that Sometimes my app reloads completely(Loading all the Js again and again) for each route changes. Is there a way to debug this scenario ? I am newbie to vulcan. I have seen the example in `example instagram` package and added the routes.js of my package

**Comment by SachaG** [comment]
Are you using `<Link>` from react-router?

**Comment by renganatha10** [comment]
I was not using <Link /> That Helps.
