### ISSUE TITLE
Missing field user in movies example

### ISSUE THREAD

**Issue by c316** [VulcanJS/Vulcan#1705]
I'm following along on the Movies tutorial and I keep getting a warning. 

```
printer.js:170
Missing field user in {
  "_id": "MTYrCSFmF3vTKN67L",
  "name": "Movie Name",
  "year": "2017",
  "review": "Bad Movie",
```

I've tried all of these ways to resolve it

adding ```user={Meteor.userId()``` or
```user={currentUser}``` or
```currentUser={currentUser}``` to
```
<Components.SmartForm collection={Movies} />
```

I'm still getting the same warning. 

When I see this warning the whole list of documents disappears and I get what you see in this screenshot.

![screenshot 2017-08-14 16 16 27](https://user-images.githubusercontent.com/3142974/29292244-0b397142-810c-11e7-84ad-1a0e1b9de33e.png)

After about 5 seconds the list renders correctly, including the movie I just inserted

**Comment by SachaG** [comment]
It's possible that the tutorial and/or video have some out-of-date code. I'd recommend comparing your own code to the finished product in example-movies and see if you can find the source of the problem.

**Comment by c316** [comment]
Yes, you are right. 

I changed this line 

```
<Components.SmartForm collection={Movies} />
```

to this

```
<Components.SmartForm
    collection={Movies}
    mutationFragment={getFragment('MoviesItemFragment')}
/> 
```

Then imported the getFragment method from ```meteor/vulcan:core```
