### ISSUE TITLE
Typo in Movies Example docs

### ISSUE THREAD

**Issue by DavOnGit** [VulcanJS/Vulcan#1708]
here: http://docs.vulcanjs.org/example-movies.html#The-User-Resolver

is:

>  typeName: 'User'

should be:

> type: 'User'

**Comment by Bitti09** [comment]
@DavOnGit  already done here: https://github.com/VulcanJS/vulcan-docs/commit/1e5c6418a3199aed889b2df549227a7c53ef111e

docs need to be rebuild to apply the change.
