### ISSUE TITLE
Display single group from edit profile

### ISSUE THREAD

**Issue by vipinlahoti** [VulcanJS/Vulcan#1710]
I have a multiple groups in user profile like:
General,
Professional,
Stats,
Notification,
Subscriptions.. etc.
how can I take out the Subscriptions form group from edit account page and make it under subscription page?

**Comment by SachaG** [comment]
Sorry, I don't really understand the question. Can you give more details, maybe some screenshots or a mockup of what you're trying to achieve?

**Comment by vipinlahoti** [comment]
Attached is the accounts page where, General, Professional, Social and Notification groups are available,
I want to take out the Notification group and add it to separate tab as same as Edit Profile and Change password are made above.

![image](https://user-images.githubusercontent.com/2918394/29513943-72712300-8684-11e7-82c8-0b65be8e7fb0.jpg)

**Comment by SachaG** [comment]
Oh ok, I understand now. You can restrict which fields are displayed in the form by passing it a `fields` option. This means you'll have to pass the list of all fields that you *do* want (so everything except notifications) in one form (or you can also hide the group using CSS, if that's easier), and then have a second form where `fields` only contains the three notification fields and nothing else.

**Comment by vipinlahoti** [comment]
In this case I will be duplicating the edit form and restricting with CSS.

**Comment by MHerszak** [comment]
Can this be closed? Should those questions be on StackOverflow?
