### ISSUE TITLE
WithList HOC loading prop is always false?

### ISSUE THREAD

**Issue by DavOnGit** [VulcanJS/Vulcan#1714]
bug: withList `loading` prop stay false while loading data (by `loadMore()`)

**Reproduction:**

- Clone vulcan v1.7
- Start example-instagram pkg
- Add a debug/console.log to the **PicList.jsx** file pointing the `loading` prop
- Trigger the `addMore` function

Maybe i missed something?

(another issue is the fact that example-instagram `<Loader />` component is unstyled, so also in case `loading` should become true, it will show an empty div. Note that main package.json version is still 1.2...)

**Comment by SachaG** [comment]
What about the `networkStatus` prop? Does it change correctly?

**Comment by DavOnGit** [comment]
I have, `networkStatus: 7` and it does't change while loading data...
