### ISSUE TITLE
Subscribe Button not working

### ISSUE THREAD

**Issue by Michael-Reich** [VulcanJS/Vulcan#1729]
I added API key and List Id of MailChimp and got this error on clicking on the button: 
Error: GraphQL error: Cannot read property 'subscribe' of undefined

**Comment by valgalin** [comment]
Hi @Michael-Reich ,

This has been fixed in the devel branch. Please see sample_settings.json file in devel. You can see the correct parameters for Mailchimp.

**Comment by valgalin** [comment]
It looks like sample_settings.json in devel branch has been cleaned up. Please see this doc instead:

http://docs.vulcanjs.org/newsletter.html#Settings

**Comment by Michael-Reich** [comment]
Thank you will test it today!

**Comment by Michael-Reich** [comment]
Worked
