### ISSUE TITLE
Utils.getCollectionNameFromTypename() only works with core collections

### ISSUE THREAD

**Issue by klokie** [VulcanJS/Vulcan#1730]
Hi, I just ran into an issue while trying to implement a "subscribe" button for a custom collection.
It seems that [Utils.getCollectionNameFromTypename()](https://github.com/VulcanJS/Vulcan/blob/342cc39bf42ac05247c555c458b8ae9cf86c9d3e/packages/vulcan-lib/lib/modules/utils.js#L299) will only work with the `categories`, `comments`, `posts`, and `users` collections, as these are hard-coded into the lookup function.

I was able to make it work by overriding this function with the following code in a custom helper file, but I wonder if there could be a better way (maybe using GraphQL introspection)?

```
Utils.getCollectionNameFromTypename = (type) => {
  if (type.indexOf("Cat") > -1) {
    return "categories";
  }

  return `${type.toLowerCase()}s`;
};
```

**Comment by SachaG** [comment]
Hmm, to be honest since I didn't write the subscribe package I don't really know why/how it's using that function. I definitely agree it shouldn't be hard-coded though.
