### ISSUE TITLE
Error When I am Using Embedly provider

### ISSUE THREAD

**Issue by salimakhtar786** [VulcanJS/Vulcan#1733]
When I am using `embedly` provider it is generating following error
```
[Error: failed [401] {"error_code": 401, "error_message": "Invalid `key` provided: 123foo. To find your key, log into https://app.embed.ly -&gt; API.", "type": "error"}]
```
in private setting i added
```
"private": {
    "embedProvider": "embedly",
      "embedly": {
      "apiKey": "123foo"
    }
  }
```

and using following code

const embedProvider = getSetting('embedProvider', 'embedly');

**Comment by SachaG** [comment]
You're supposed to replace `123foo` with your real Embedly API key.
