### ISSUE TITLE
CustomLogo.jsx modification required (simple)

### ISSUE THREAD

**Issue by hammannja** [VulcanJS/Vulcan#1735]
In order to get the CustomLogo.jsx to function with the CurrentUser customization, it is necessary to change replaceComponent('Logo', CustomLogo); to replaceComponent('Logo', CustomLogo, withCurrentUser);

**Comment by MHerszak** [comment]
I am going to close this for now. I am unable to see a question. Feel free to open it again once you have one.

**Comment by hammannja** [comment]
Not a question. Just a bug-fix that may or may not have been solved in the master branch long ago.
