### ISSUE TITLE
How to Update simple_settings.json File

### ISSUE THREAD

**Issue by salimakhtar786** [VulcanJS/Vulcan#1741]
Is it possible to update settings.json file?

I am using VulcanJS and want to open simple_settings.json file in a modal  with editing feature and then update.

How to do this?

**Comment by SachaG** [comment]
Sorry, `settings.json` is read-only and cannot be modified from the client, mainly for security and convenience (easy to copy/save your config) reasons. If you'd like to have customizable settings you will have to create your own settings package.
