### ISSUE TITLE
Error: The babel-runtime npm package could not be found in your node_modules 

### ISSUE THREAD

**Issue by TylerL-uxai** [VulcanJS/Vulcan#1742]
git clone, npm install, npm start:

W20171009-01:08:37.883(-5)? (STDERR) Error: The babel-runtime npm package could not be found in your node_modules 
W20171009-01:08:37.884(-5)? (STDERR) directory. Please run the following command to install it:
W20171009-01:08:37.884(-5)? (STDERR) 
W20171009-01:08:37.885(-5)? (STDERR)   meteor npm install --save babel-runtime

**Comment by TylerL-uxai** [comment]
Deleting package-lock.json and running meteor npm install fixed the issue

**Comment by martinhbramwell** [comment]
@TylerL-uxai Can close?

**Comment by TylerL-uxai** [comment]
Yep! Thanks :)
