### ISSUE TITLE
May I Use The CreateContainer in VulcanJS

### ISSUE THREAD

**Issue by salimakhtar786** [VulcanJS/Vulcan#1745]
I am using the following packages in VulcanJS

`meteor npm install --save react-addons-pure-render-mixin`

`meteor add react-meteor-data`

`createContainer()` is not calling.
```
export default createContainer(() => {

 return {
    user: 'Meteor.user()'
  };
}, HeadTags);
```

In **`HeadTags`** component  **`console.log(this.props.user)`** giving **`undefined`**

**Comment by SachaG** [comment]
I'm not sure, sorry. But I would suggest staying away from any Meteor-specific packages like react-meteor-data.
