### ISSUE TITLE
npm install errors on Windows

### ISSUE THREAD

**Issue by toyeebgodo** [VulcanJS/Vulcan#1749]
After cloning the master of the Vulcan repo and running "npm install", I got the following errors:

Toyeeb (master) Vulcan $ npm install

> bcrypt@0.8.7 install C:\Users\Toyeeb\Vulcan\node_modules\bcrypt
> node-gyp rebuild

C:\Users\Toyeeb\Vulcan\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Toyeeb\Vulcan\node_modules\bcrypt
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enzyme-adapter-react-16@1.0.1 requires a peer of enzyme@^3.0.0 but none was installed.
npm WARN enzyme-adapter-react-16@1.0.1 requires a peer of react@^16.0.0-0 but none was installed.
npm WARN enzyme-adapter-react-16@1.0.1 requires a peer of react-dom@^16.0.0-0 but none was installed.
npm WARN enzyme-adapter-react-16@1.0.1 requires a peer of react-test-renderer@^16.0.0-0 but none was installed.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Toyeeb\Vulcan\npm-debug.log
Toyeeb (master) Vulcan $

Please help

**Comment by toyeebgodo** [comment]
The following answer from Stackoverflow solved it for me. 

For windows install the following module

npm install -g node-gyp
npm install --g --production windows-build-tools
then try to install

npm install bcrypt

https://stackoverflow.com/a/40046466/7756330

**Comment by kashoncode** [comment]
Tried the above, still getting the same errors. Any ideas?
