### ISSUE TITLE
How to prefetch data

### ISSUE THREAD

**Issue by PolGuixe** [VulcanJS/Vulcan#1762]
I would love to improve navigation UX, with prefetching: http://dev.apollodata.com/react/prefetching.html

I have tried to load data in advance calling `withDocument` on an empty component so I could execute the query - I know it is the best approach, I just wanted to do a quick try-. The data gets downloaded and added to the store. However, when I am trying to access the document I have already downloaded, the page is not rendered straight away and the loading property is still set to true. After this, if I leave the document and come back the document is rendererd straight away.

**Comment by SachaG** [comment]
Have you tried doing what the documentation says?

> in GitHunt, we use the withApollo higher-order component to directly call a query as soon as the user hovers over a link to the comments page. 

I don't really see a good way to do it with `withDocument` to be honest.
