### ISSUE TITLE
Regarding FormWrapper/ SmartForms

### ISSUE THREAD

**Issue by MHerszak** [VulcanJS/Vulcan#1766]
Facebook's suggestion for HOCs is to not put them into render.

https://reactjs.org/docs/higher-order-components.html#dont-use-hocs-inside-the-render-method

I am going to change it as soon as I understand the component concern itself.

**Comment by SachaG** [comment]
Oh that's a great point! I think this is the relevant part:

> In those rare cases where you need to apply an HOC dynamically, you can also do it inside a component’s lifecycle methods or its constructor.

Shouldn't be too hard to do.

**Comment by SachaG** [comment]
OK, let's see if this works: https://github.com/VulcanJS/Vulcan/commit/41b585adfa045f3902a41259c13f9a478743bb72

**Comment by MHerszak** [comment]
I looked at the file but haven't tested it, yet. I am wondering about the loading order of the components you are composing a wrapper earlier than its wrapped component. I am not sure if this supposed to be happening in Meteor or as a concept for React components.
