### ISSUE TITLE
Forum Example: Upvotes / replyCancelCallback not working on Comments

### ISSUE THREAD

**Issue by neonbrown82** [VulcanJS/Vulcan#1774]
When I try to upvote a comment on my custom forum example, the view doesn't update. The server console log is showing that the vote registered, but the display stays at 0. Thinking that I possibly messed something up, I installed a fresh version of the vulcan-master repo and it doesn't work on the fresh install either. Works great on the Posts, and it appears the code is identical between the two with the exception of the collection names...

...and another issue while I'm here: if I click to leave a new comment (or edit an existing one) and then hit 'cancel', nothing happens. The client console is showing an error that event.preventDefault is not a function, at CommentsItem.replyCancelCallback (CommentsItem.jsx:25) -- nothing looks out of the ordinary on that line or anywhere else in that function...

Any quick fixes for either of these issues?

**Comment by valgalin** [comment]
Hello @neonbrown82 ,

Were you able to find a quick fix for the "Cancel" option? If not, I documented here how I was able to find a quick fix for that:

https://github.com/VulcanJS/Vulcan/issues/1870

Although, I'm still asking if what I did was correct and does not break anything.

For the upvote in comments, I think the latest release has fixed this issue.

**Comment by justinr1234** [comment]
The reply cancel should not have a call to `preventDefault` as that’s already done inside the smart forms

**Comment by justinr1234** [comment]
Same thing for edit cancel
