### ISSUE TITLE
Create user without using std:accounts-ui

### ISSUE THREAD

**Issue by muninn9** [VulcanJS/Vulcan#1775]
What is the best way to create users without using the std:accounts-ui package? I just want to use my own signup form for creating new users.

I've tried: `Users.options.mutations.new.mutation(this, this.state, Users)`

and in GraphiQL I've tried: 
```
mutation {
  usersNew (document: {email: "test@test", username: "test", password: "1234"}) {
    _id
    email
    username
  }
}
```
which both give an error message of:
```
{
  "data": {
    "usersNew": null
  },
  "errors": [
    {
      "message": "{\"id\":\"app.mutation_not_allowed\",\"value\":\"\\\"usersNew\\\" on _id \\\"undefined\\\"\"}",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "usersNew"
      ]
    }
  ]
}
```
I'm assuming this error message is because I didn't provide an id but it doesn't accept id or _id as an argument in the mutation. Some guidance would be appreciated.

**Comment by SachaG** [comment]
There isn't really a good way right now. I would probably suggest using https://github.com/orionsoft/meteor-apollo-accounts since we'll probably transition to that eventually anyway.
