### ISSUE TITLE
Delete a User, his post still remain there and nothing get loaded on home Page

### ISSUE THREAD

**Issue by deligence** [VulcanJS/Vulcan#1776]
<img width="1198" alt="screen shot 2017-11-13 at 5 10 19 pm" src="https://user-images.githubusercontent.com/8718725/32879148-d6cdce32-cace-11e7-907e-12f3177747c5.png">

Delete a User, his post still remain there and nothing get loaded on home Page as the query gets failed. See the attached screen shot for the error message.

**Comment by deligence** [comment]
We have resolved this issue for our client by adding the functionality to delete the posts when a user gets deleted. We would like to contribute this code to Vulcan. 

The process of taking a pull request isn't clear to me. Do let me know how I can take a Pull Request and Contribute this code.

**Comment by SachaG** [comment]
Thanks! You can submit a PR to the `devel` branch. See https://github.com/VulcanJS/Vulcan/blob/master/CONTRIBUTING.md

**Comment by SachaG** [comment]
There's already a `UsersRemoveDeletePosts` callback, the problem is that it checks for an `options.deletePosts` flag that doesn't exist. The best way to fix this is to replace that check by a check for `getSetting('forum.deletePosts')` and then register that setting using `registerSetting`.
