### ISSUE TITLE
How to Set Metadata (HeadTags) Only For Home Page

### ISSUE THREAD

**Issue by salimakhtar786** [VulcanJS/Vulcan#1781]
Hello

I am using VulcanJS and I want to show metadata using "HeadTags" component only for the home page.

How to do this?

**Comment by MHerszak** [comment]
Would this help:
`<Components.HeadTags url={Posts.getPageUrl(post, true)} title={post.title} image={post.thumbnailUrl} description={post.excerpt} />`

[PostPages.jsx](https://github.com/VulcanJS/Vulcan/blob/master/packages/example-forum/lib/components/posts/PostsPage.jsx)

**Comment by deligent** [comment]
I want to show metadata only at home page but not post-page.

**Comment by MHerszak** [comment]
Maybe I misunderstood your question? The code above can be adapted to meet your requirements when you implement it on your homepage. And only on your home page. If it appears somewhere else just delete it.
