### ISSUE TITLE
Idea for improving withDocument

### ISSUE THREAD

**Issue by PolGuixe** [VulcanJS/Vulcan#1782]
Right now `withDocument` makes a query, without checking if the data that it requires is already in the store. This makes `withDocument` unusable if you have done any kind of data pre-fetching.

I suggest to change the logic of `withDocument` as follows:
1. Fetch data from the client store.
2. If data from the client store not available, make a query.

However, I have some concerns:

1. How do we know if the data in the client store is the most up-to-date?
2. Should the mutations also affect the client store?

I am some code that does the above, however I am still testing it. 

I want to open the discussion to find the best way to improve `withDocument`.

**Comment by Discordius** [comment]
I think withDocument should just take an argument in the options document that sets the Apollo query mode. 

I think in general we want rewrite withDocument so that it's basically just a wrapper around withList, since the two components do almost precisely the same.

**Comment by PolGuixe** [comment]
I am not sure wrapping withList to achieve what withDocument does is a good idea. Probably some code can be extracted to make withList and withDocument more modular. 

In both cases they should check if the client cache already contains de information.

**Comment by SachaG** [comment]
Actually this is something I added to both `withList` and `withDocument` recently:

```
if (options.fetchPolicy) {
        graphQLOptions.fetchPolicy = options.fetchPolicy;
      }
```

So you can now specify a `fetchPolicy` option, which should address your concern. 

> I think in general we want rewrite withDocument so that it's basically just a wrapper around withList, since the two components do almost precisely the same.

Maybe, I'll think about it when we rewrite `withList` to not use the reducer anymore.

**Comment by SachaG** [comment]
(oh this is on the `devel` branch btw)

**Comment by MHerszak** [comment]
@PolGuixe when you talk about caching, isn't Apollo client taking care of some of the caching you are trying to achieve? I am not sure if Vulcan should get into caching at all. @SachaG is there an example of how to use fetchPolicy?

**Comment by PolGuixe** [comment]
Through a lot of testing, I realized that you can have a finer control of the data cached using `ApolloClient.readFragment` and `ApolloClient.readQuery`. 

`ApolloClient.readFragment` is required if you are trying to implement a proper pre-fetching on your app and is **faster** than doing any query. It is basically a sync function. I would like to use it in `withDocument`. If `ApolloClient.readFragment` fails, then it can fallback to perform a query, which will probably go to the network. 

To implement something similar for the `withList`, probably is better to use `ApolloClient.readQuery`. Although, I haven't performed many tests with it. In some of them, it was behaving as I expected just partially.

What I am not sure about is the difference between `ApolloClient.readQuery` and `ApolloClinet.query` with the fetch policy set to `cache-only`.

**Comment by SachaG** [comment]
That's definitely outside the scope of `withDocument` and `withList`. In that case I would suggest writing your own HoC that calls `readFragment`.

**Comment by PolGuixe** [comment]
I think that being able to use pre-fetching and read the data from client cache are really useful features.

maybe this logic can be implemented as a HoC that can wrap `withDocument`?

I don't have many ideas for the naming. So please feel free to suggest names.

**Comment by SachaG** [comment]
> I think that being able to use pre-fetching and read the data from client cache are really useful features.

But that's already implemented by Apollo itself. This is what `fetchPolicy` is for.

**Comment by PolGuixe** [comment]
Imagine you have a list of Posts. To get the data and display them you have the following query

```
query postsList {
  posts {
    id
    title
    shortDescription
    image
  }
}
```
When the user navigates to a specific post then you use this query

```
query postsList {
  onePost(id: $postId) {
    id
    title
    body
    image
  }
}
```
Above you have a basic normal pattern. You first query for the list and then you query for the post.

Imagine you want your users to access the post instantly -without a network query-. You could modify the first query as follows: 
```
query postsList {
  posts {
    id
    title
    shortDescription
    body
    image
  }
}
```
This way you'll have all the data you need on the client. However, when you access your post by using the following query:
```
query postsList {
  onePost(id: $postId) {
    id
    title
    body
    image
  }
}
```
You'll still have to do a network query, even if all the data you need is on the client. Because Apollo hasn't performed this query before.

If you want to access that data 'directly' you can use `readFragment`. In this `
readQuery` won't work as there is no query registered like this one yet. Moreover, you can have logic to still perform de query if `readFragment` fails or still do it anyway for the sake of data consistency on the client or you want to add a pollInterval, etc.

Does it make sense?

I think it will be useful for Vulcan to have such capabilities. Otherwise, this could be a separate library. :)

**Comment by SachaG** [comment]
I always assumed that Apollo already does what you describe out of the box. I might be wrong though, I would suggest asking in the Apollo chatroom directly to make sure.

**Comment by MHerszak** [comment]
Has anyone read this: [dev-blog.apollodata.com](https://dev-blog.apollodata.com/announcing-apollo-cache-persist-cb05aec16325)

**Comment by PolGuixe** [comment]
@MHerszak that topic is super interesting and I would love to explore it! 

Probably the very first step to implement it would be to upgrade to Apollo Client 2. I gave it a try, however I got stuck at the redux interface and I did had much time to investigate.

**Comment by MHerszak** [comment]
@PolGuixe yeah redux can be tricky when you try to cut a domain into pieces. Do you think we can close this issue, for now?

**Comment by PolGuixe** [comment]
@MHerszak honestly I don't think so. The behavior, I've described is not the one offered by Vulcan right now. My question is: do we want Vulcan to have this behavior?

I'll try to make a PR, so it is more clear what I am proposing.

**Comment by SachaG** [comment]
I think this should be handled at the Apollo level, not the Vulcan level. So I would probably discourage a PR in that direction to be honest.

**Comment by PolGuixe** [comment]
I've made a PR to our fork: https://github.com/OrigenStudio/Vulcan/pull/1

Currently to go around we are using another HoC, we have call it `withLocalDocument`. See PR.
We use this HoC in combination of `withDocument`: 

```
// curryWithRouteNode.js

....

export default options => {
  const {
    collection,
    fragmentName,
    pollInterval,
    localDocumentOptions,
  } = options;
  return compose(
    withDocumentID,
    withDocument({
      collection,
      fragmentName,
      pollInterval,
    }),
    withLocalDocument({
      collection,
      fragmentName,
      ...localDocumentOptions,
    }),
  );
};
```

I believe that the logic in `withLocalDocument` should be combined with the logic in `withDocument`. I understand you @SachaG when you say that it should be handled at Apollo level, however right now they are not doing it. I my opinion the problem arises from the differences between fragments and queries.

**Comment by SachaG** [comment]
This is really cool, but yeah it's just too much magic/complexity on top of an already magic/complex thing (`withDocument`) on top of Apollo which itself has its own magic and complexity… So I think it's better to either A) keep this as a separate, optional `withLocalDocument` HoC or B) find a way to integrate this feature into Apollo directly. 

I'm going to close this for now, but let me know if you open an issue in the Apollo repo or somewhere else, I would be interested in seeing the discussion around this topic.

**Comment by PolGuixe** [comment]
@SachaG ok. I'll try to open an issue in the apollo repo. 

If we would like to open source this code and other code that supplements Vulcan, which way you think is the best? A separate package authored by us?  or a Vulcan package?

**Comment by PolGuixe** [comment]
Does anyone knows where is the best place to discuss this with the Apollo team? I feel like if I open an issue in Github, it will be ignored. As it is not an issue with their current API. 
It is more of a feature request.

**Comment by SachaG** [comment]
A separate package would be best. And I don't think a GitHub issue will be ignored, but if it is let me know and I'll nudge them to answer it :)

**Comment by PolGuixe** [comment]
Just opened an issue in the `react-apollo` repo.

**Comment by MHerszak** [comment]
@PolGuixe The latest medium article shows they will work on state handling in Apollo client. That means no detour (to redux) necessary.

**Comment by ShockiTV** [comment]
https://www.apollographql.com/docs/react/features/cache-updates.html#cacheRedirect

**Comment by PolGuixe** [comment]
@ShockiTV That is right. However, those docs are for the Apollo Client 2.x. Vulcan is still using 1.x

**Comment by ShockiTV** [comment]
@PolGuixe yes, in v1 cacheResolvers was property on client init, not on cache. But it is 1:1 I think.

**Comment by PolGuixe** [comment]
@ShockiTV I see now. Thx!!
