### ISSUE TITLE
Slack link on website not working

### ISSUE THREAD

**Issue by vonwao** [VulcanJS/Vulcan#1785]
http://slack.telescopeapp.org/

**Comment by MHerszak** [comment]
[https://vulcanjs.slack.com](https://vulcanjs.slack.com)

**Comment by SachaG** [comment]
My Heroku dyno ran out of free time, fixed now.

**Comment by jacobpdq** [comment]
@SachaG down again :(

Could I please have an invite? jacob@subsumo.com

**Comment by amir1m** [comment]
I am not able to access the slack group? Is it working now? Whats the URL?

**Comment by Apollinaire** [comment]
The slack itself is working but the app to invite yourself in the slack is currently down, sorry. https://slack.vulcanjs.org/

**Comment by SachaG** [comment]
Fixed it, just needed to restart the heroku dyno.
