### ISSUE TITLE
Use FormsUpload in User Schema

### ISSUE THREAD

**Issue by Sebi55** [VulcanJS/Vulcan#1792]
I am trying to import meteor/vulcan:forms-upload into the user schema but I keep getting an error message that the package is not found.
How would I use the FormsUpload component in the user schema to automatically display it in all Forms?
I think the load order is currently wrong at the time I am trying to import the package.

**Comment by MHerszak** [comment]
Did you check `example-instagram` package for help? It comes with a form-upload in the schema definition. [schema](https://github.com/VulcanJS/Vulcan/blob/ac5d92d89c335b6fda90a2afd2f0a5be2a2e3871/packages/example-instagram/lib/modules/pics/schema.js#L48)

**Comment by SachaG** [comment]
Make sure the package where you want to use `meteor/vulcan:forms-upload` itself depends on `vulcan:forms-upload` in its `package.js` file.

**Comment by Sebi55** [comment]
I tried to extend the vulcan:users package schema by adding the vulcan:forms-upload package as dependency and adding the fields manually in the schema instead of using the addField method which was totaly wrong. This led to problems like duplicate dependencies when loading the users package.

**Comment by SachaG** [comment]
Glad you worked it out :)
