### ISSUE TITLE
Misleading account login form

### ISSUE THREAD

**Issue by eric-burel** [VulcanJS/Vulcan#1796]
Hi,

In version 1.8.1, using the default `AccountsLoginForm` asks for the "email or username". Actually, it only reckognize the username, which is quite misleading (took me more time to get it than I am willing to admit). 
I guess this is an Account-ui setup issue, how can we fix that ? By the way how can we handle i18n (e.g. to add French to the account-ui) and more broadly the account form legend ? By tweaking the `vulcan:accounts` package ?

Thanks !

**Comment by MHerszak** [comment]
I can only help with the i18n question. Here is a link to a french implementation: [fr_FR](https://github.com/VulcanJS/nova-i18n-fr-fr/blob/master/lib/fr_FR.js) Is this what you are looking for?

**Comment by eric-burel** [comment]
Thanks for the link. Changing the labels are indeed the solution, I'll try to PR the EN version to fix my issue.

**Comment by meteorplus** [comment]
@eric-burel avec plaisir Eric :)

**Comment by eric-burel** [comment]
Okay it seems to work, however the fr package dates back to Nova and haven't been updated, I'll try to publish an updated version when it's ready. Also the issue actually comes from the meteor Accounts package, that uses the `accounts.enter_username_or_email` i18n token although it accepts only the username.

**Comment by MHerszak** [comment]
@eric-burel can we close this issue?

**Comment by eric-burel** [comment]
Yep I closed it, thanks
