### ISSUE TITLE
Contents within HeaderTags.jsx not defined

### ISSUE THREAD

**Issue by MHerszak** [VulcanJS/Vulcan#1804]
Here is the part that breaks.

`{Head.script.map((tag, index) => <script key={index} {...tag}>{contents}</script>)}`

"contents" is not defined. My solution is to just get rid of it. How come no one else is experiencing this problem? Am I missing something?

**Comment by SachaG** [comment]
I think it should be:

```
          {Head.script.map((tag, index) => <script key={index} {...tag}>{tag.contents}</script>)}
```
