### ISSUE TITLE
[Question]Electron support?

### ISSUE THREAD

**Issue by michaelspeed** [VulcanJS/Vulcan#1809]
Can we use this framework with electron?

**Comment by SachaG** [comment]
I haven't tried myself but I think so, maybe using https://github.com/electron-webapps/meteor-electron ?

**Comment by michaelspeed** [comment]
but is it powerful for offline support - as stated in the repo

> This package differs from Electrometeor and Electrify by not baking Meteor into the packaged app. This makes things significantly simpler, but if you need strong offline support, one of them is a better solution.

i currently need a strong offline support with something as powerful as vulcan.

**Comment by SachaG** [comment]
Sorry, I don't know more than that. If you find out more please update this tread with any additional info :)

**Comment by michaelspeed** [comment]
ok i will try with this. Hope it works!

**Comment by michaelspeed** [comment]
i finally added electron to the basic vulcan starter
with this lib - [https://github.com/wojtkowiak/meteor-desktop](https://github.com/wojtkowiak/meteor-desktop)
but i have an error - 

> Fetch API cannot load http://127.0.0.1/graphql. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8062' is therefore not allowed access. The response had HTTP status code 405. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

anyway we can change the graphql endpoint?

**Comment by SachaG** [comment]
We can't change the endpoint but there should be a way to whitelist the URL? I think we had the same issue with Cordova, maybe you can search recent issues?

**Comment by michaelspeed** [comment]
ok thanks will figure it out

**Comment by eric-burel** [comment]
#1662 for reference, solution should be the same I guess

**Comment by eric-burel** [comment]
Closing as this is an old question. Let's hope that Meteor could be integrated to Electron, it could be fun though I don't want to imagine the RAM consumption of the whole thing.
