### ISSUE TITLE
Hydrate fails

### ISSUE THREAD

**Issue by eric-burel** [VulcanJS/Vulcan#1812]
Hi, 
I encounter an hydrate issue when running my app in production (related to apollo or redux I guess?). The issue appeared widly after adding some collections/updating schemas, seemingly for no reason (did not touch the server whatsoever).
You can observe it [here for now](http://simply-charge-staging.herokuapp.com/)

```
Uncaught TypeError: i.hydrate is not a function
```
The homepage correctly prints, so it seems like a non fatal error, maybe linked to redux for example. However it is unusable, as if React totally froze.

Google gave no clue :/

**Comment by MHerszak** [comment]
#1808 Do you have the latest version of React?

**Comment by eric-burel** [comment]
No but I've read that it may be related to React 16 indeed. I am using a recent clone of Vulcan-Starter so I thought it was okay to use the provided version of react (15+). I guess I've missed a PR in the meantime. I'll update to React 16 and tell you if its ok then.

**Comment by eric-burel** [comment]
Here what an update of `react` and `react-dom` to 1.6.2 gives on my app:
```
```

**Comment by eric-burel** [comment]
Ok solved, we must 
- update React to 16.2
-update React-dom to 16.2
- update formsy-react to 0.19.5 (BUT not 1.x version, there are breaking change)

**Comment by MHerszak** [comment]
I am glad you worked it out :)

**Comment by SachaG** [comment]
Yeah I've been meaning to publish this post: https://medium.com/vulcanjs/whats-new-in-vulcanjs-v1-8-3-bea45752d606
