### ISSUE TITLE
How to access request context to get IP from client

### ISSUE THREAD

**Issue by lunchboxer** [VulcanJS/Vulcan#1819]
In express I can get the address from the client when they make a request. Depending on the exact context, it could look something like this: 
`var ip = req.headers['x-forwarded-for'] || req.connection.remoteAddress`
Is it possible to do something similar in meteor/vulcan?
```
import { addCallback } from 'meteor/vulcan:core';

function setClientIP (post, user) {
  post.clientIP = ?
  return post;
}
addCallback('posts.edit.sync', setClientIP);
```
if so, how? I couldn't find any clues in the docs

**Comment by SachaG** [comment]
That's a good question. I think ideally the last argument of the callback should be the `context`, and the IP should be available on it. 

It would require a little bit of fiddling with the Apollo code to find the right place to inject this though, and then manually adding the context to every relevant callback. Happy to accept a PR to do this.
