### ISSUE TITLE
Reconsider how fields are added to GraphQL schema/made viewable

### ISSUE THREAD

**Issue by SachaG** [VulcanJS/Vulcan#1829]
Previously: 

- All fields added by default
- All fields viewable by default <- probably a bug!

Now: 

- No fields added by default
- No fields viewable by default

**Comment by MHerszak** [comment]
Just a gut feeling regarding 'No fields viewable by default'. Since the GraphQL schema is auto-generated, doesn't it make sense to leave it up to you what to expose? Am I misunderstanding something?

**Comment by SachaG** [comment]
Yes, it was more of a reminder to myself to look into why all fields were viewable before, might be a security issue somewhere.
