### ISSUE TITLE
Can't pass a stateless component in the schema form option

### ISSUE THREAD

**Issue by eric-burel** [VulcanJS/Vulcan#1831]
Hi,

I am building an input based on `react-select`. I'd like to set the `optionRenderer` props, which expects a React stateless component.
The best solution would be to put it in the `form` attribute of the schema, as any other prop:

```
form:{
           collection: VendingMachines,
           multiple: true,
           optionRenderer: VendingMachineOption,
           labelKey: '_id',
           valueKey:'_id',
       },
control: MyAmazingSelect,
```
but my `VendingMachineOption` somehow gets serialized or rendered in the process, when I look at the props it's an object, not a function anymore. 

My components themselves works well, I simply built a specific wrapper that pass the correct Renderer to get a working solution and it works smoothly, but it means creating a custom component each time. It would be easier to have generic inputs and pass specific components as props whenever possible.

**Comment by MHerszak** [comment]
I am only guessing here, did you register your component? `FormComponent.jsx` in `vulcan:forms` requests a form element like so `const CustomComponent = Components[this.props.control];`. Checkout the embed component.

**Comment by SachaG** [comment]
I'm not sure I understand the question, sorry. You'd like to be able to pass any random function from the schema to the form control component as props basically?

If it's not working as expected, maybe SimpleSchema is doing something weird to the schema? What if you just pass the function name as a string and then get the function itself from somewhere else instead?

**Comment by eric-burel** [comment]
I indeed need to pass a component to `MyAmazingSelect` as a prop, more specifically a "render function" (so a stateless functionnal component), sorry if I was somehow unclear.

The component seem to have been rendered before it is passed a prop to `MyAmazingSelect`, as if I wrote `optionRenderer: <VendingMachineOption />` instead of `optionRenderer: VendingMachineOption` (or so I guess).

![image](https://user-images.githubusercontent.com/7983005/35430962-e749ebf4-027a-11e8-84ce-774e919eafb1.png)

It should be a function instead. 

I also tried with a simple arrow function instead of a component, there the field containing the function is simply scraped out.


And indeed the issue might not be Vulcan-side, but I raise the issue in case it is, I don't really know what happens to the schema during all this process.

@MHerszak You were right in your first answer, another way to solve this is to use registered component and simply pass the name instead, I think I'll go for this solution for the moment. But it is Vulcan specific, passing functionnall components to advanced form input to customize them is a relevant use case, a lot of lib rely on this, so it is more a temporary solution.

**Comment by SachaG** [comment]
I think this is the relevant bit of code: 

https://github.com/VulcanJS/Vulcan/blob/master/packages/vulcan-forms/lib/components/Form.jsx#L176-L187

I can't say I remember writing this and I'm not super clear what it's supposed to be doing…

**Comment by eric-burel** [comment]
This definitely makes sense, because we may want to pass a value to the form input props, but build it upon the props that contains some relevant values (current collection etc.). So you would expect Vulcan to run the function or to render the Component, which is what you do.

But sometimes you don't want this, either because the component must be passed further down or because you actually want to pass a function in the props, so you need a closure.

This is not an actual bug I think the behaviour you implemented is fine (and you do not have much alternative anyway), the doc simply lacks a sentence about this.

**Comment by eric-burel** [comment]
[https://github.com/VulcanJS/vulcan-docs/pull/61]()
