### ISSUE TITLE
Conflict: Constraint vulcan:lib@1.8.6 is not satisfied by vulcan:lib 1.4.0

### ISSUE THREAD

**Issue by MHerszak** [VulcanJS/Vulcan#1854]
I am currently on 1.8.6 and I am trying to deploy to Galaxy.

I am getting this error:

```
While selecting package versions:
error: Conflict: Constraint vulcan:lib@1.8.6 is not satisfied by vulcan:lib 1.4.0.
Constraints on package "vulcan:lib":
* vulcan:lib@1.8.6 <- vulcan:core 1.8.6
* vulcan:lib@1.8.6 <- vulcan:users 1.8.6 <- vulcan:core 1.8.6
* vulcan:lib@1.8.6 <- vulcan:routing 1.8.6 <- vulcan:core 1.8.6
* vulcan:lib@1.8.6 <- vulcan:i18n 1.8.6 <- vulcan:core 1.8.6
* vulcan:lib@1.8.6 <- vulcan:debug 1.8.6 <- vulcan:core 1.8.6
```
I deleted .versions but can't deploy. I am not sure how to solve this dependency issue.

To add to this list. I don't think it is necessary to include `vulcan:debug` in `vulcan:core`. I believe it is better to include debug in my .meteor/packages when I need it.

**Comment by SachaG** [comment]
Weird because `1.4.0` doesn't appear anywhere in that list?

> To add to this list. I don't think it is necessary to include vulcan:debug in vulcan:core. I believe it is better to include debug in my .meteor/packages when I need it.

I see your point, but I think my original idea was that people wouldn't realize the debug package exists otherwise. And since it's not deployed anyway it didn't really matter?

**Comment by MHerszak** [comment]
I created a new project added all dependencies by hand and still get the same dependency problem.

```
error: Conflict: Constraint vulcan:lib@1.8.6 is not satisfied by vulcan:lib 1.4.0.

Conflict: Constraint vulcan:debug@1.8.6 is not satisfied by vulcan:debug 1.3.2.
```
Is there a way to track those issues down? I am not seeing any dependencies to lib 1.4.0 or debug 1.3.2.

**Comment by SachaG** [comment]
I think that's a Meteor issue, it happens when you don't hardcode your dependencies versions. Are your own packages depending on non-versioned Vulcan packages?

**Comment by MHerszak** [comment]
So I checked, all vulcan packages have a version 1.8.7. I `rm -rf .meteor/local` and `rm -rf .meteor/versions` started from scratch and tried to deploy.

```
error: Conflict: Constraint vulcan:lib@1.8.7 is not satisfied by vulcan:lib 1.4.0.
Constraints on package "vulcan:lib":
* vulcan:lib@1.8.7 <- vulcan:core 1.8.7
* vulcan:lib@1.8.7 <- vulcan:users 1.8.7 <- vulcan:core 1.8.7
* vulcan:lib@1.8.7 <- vulcan:routing 1.8.7 <- vulcan:core 1.8.7
* vulcan:lib@1.8.7 <- vulcan:i18n 1.8.7 <- vulcan:core 1.8.7
* vulcan:lib@1.8.7 <- vulcan:debug 1.8.7 <- vulcan:core 1.8.7
```
Does no one else experience this?

**Comment by MHerszak** [comment]
Got it working. All those conflicts seem to appear because of the update to meteor 1.6.1.

**Comment by SachaG** [comment]
So was setting the Meteor version in all packages what fixed the issue for you?

**Comment by MHerszak** [comment]
Yeah. I added 1.6.1 to all packages.

**Comment by nisshii0313** [comment]
Hello!  Sacha, MHerszak.
I experienced same trouble.
Please give me some advices.
(I'm using latest version Vulcan.)
![2018-02-01 9 32 13](https://user-images.githubusercontent.com/28529327/35655007-21876e56-0733-11e8-854e-1db42d106366.png)

**Comment by MHerszak** [comment]
@nisshii0313 until all packages are updated, you need to update all packages to Meteor 1.6.1 and run them in your project. As soon as you use the currently published packages (Vulcan@1.8.7) you will get a mix of versions of Meteor and this seems to be a problem for Meteor. This isn't a very in-depth explanation but it helped in my case. I hope that helps.

**Comment by nisshii0313** [comment]
I understand. Could you tell me how this is done specifically?

**Comment by nisshii0313** [comment]
When I try to update my all packages, the error massages interrupt me. 
How did you resolve this problem ?

**Comment by MHerszak** [comment]
One approach is to delete your `.meteor/versions` file and start over.

**Comment by nisshii0313** [comment]
I deleted my ".meteor/versions" file but new error message appear.
![2018-02-01 12 49 36](https://user-images.githubusercontent.com/28529327/35660321-b6ab924e-074e-11e8-9944-69069bf3a695.png)

**Comment by nisshii0313** [comment]
Do you have any ideas how to solve this error ?

**Comment by nisshii0313** [comment]
please let me know another way.

**Comment by nisshii0313** [comment]
Ploblems are resolved. thanks !

**Comment by ddresch** [comment]
This worked for me:

1. delete `./.meteor/local` folder
2. remove all pined versions in your projects `package.js`
4. METEOR_PACKAGE_DIRS="../vulcan-base/packages" meteor update --all-packages

**Comment by Whizkevina** [comment]
Hello!

Anyone to help me with the solution or how to fix this...
`=> Started proxy.
=> Errors prevented startup:

   While selecting package versions:
   error: Conflict: Constraint vulcan:lib@=1.16.0 is not
   satisfied by vulcan:lib 1.3.2.
   Constraints on package "vulcan:lib":
   * vulcan:lib@=1.16.0 <- vulcan:core 1.16.0
   * vulcan:lib@=1.16.0 <- vulcan:users 1.16.0 <- vulcan:core
   1.16.0
   * vulcan:lib@=1.16.0 <- vulcan:i18n 1.16.0 <- vulcan:core
   1.16.0
   * vulcan:lib@1.10.1 <- vulcan:ui-bootstrap 1.10.1 <-
   sidebar2020 0.0.0

   Conflict: Constraint email@1.0.4 is not satisfied by email
   2.0.0.
   Constraints on package "email":
   * email@~2.0.0 <- top level
   * email@1.0.4 <- vulcan:lib 1.3.2 <- vulcan:core 1.16.0
   * email@1.0.10 <- vulcan:accounts 1.3.2 <- sidebar2020 0.0.0

   Conflict: Constraint vulcan:lib@1.10.1 is not satisfied by
   vulcan:lib 1.3.2.
   Constraints on package "vulcan:lib":
   * vulcan:lib@=1.16.0 <- vulcan:core 1.16.0
   * vulcan:lib@=1.16.0 <- vulcan:users 1.16.0 <- vulcan:core
   1.16.0
   * vulcan:lib@=1.16.0 <- vulcan:i18n 1.16.0 <- vulcan:core
   1.16.0
   * vulcan:lib@1.10.1 <- vulcan:ui-bootstrap 1.10.1 <-
   sidebar2020 0.0.0

   Conflict: Constraint email@1.0.10 is not satisfied by email
   2.0.0.
   Constraints on package "email":
   * email@~2.0.0 <- top level
   * email@1.0.4 <- vulcan:lib 1.3.2 <- vulcan:core 1.16.0
   * email@1.0.10 <- vulcan:accounts 1.3.2 <- sidebar2020 0.0.0

=> Your application has errors. Waiting for file change.`

Please I need help.
