### ISSUE TITLE
Edit and Reply cancel methods not working on Comments in example-forum package

### ISSUE THREAD

**Issue by valgalin** [VulcanJS/Vulcan#1870]
Hello guys, I don't know where to report this, either in Starter repo or here. Anyway, I will just put it here.

I noticed that the "Edit" and "Reply" cancel methods in CommentsItem.jsx file are not working. For example, when I edit a comment, the "Cancel" option is not working. Likewise with the Reply form.

Currently, here are the methods:

```
replyCancelCallback(event) {
    event.preventDefault();
    this.setState({showReply: false});
}
```

and...

```
editCancelCallback(event) {
    event.preventDefault();
    this.setState({showEdit: false});
}
```

I thought that `event.preventDefault();` was preventing the method to execute. So what I did to make it work was make `this.setState({showEdit: false});` statement as first. Like this:

```
replyCancelCallback(event) {
    this.setState({showReply: false});
    event.preventDefault();
}
```

However, I don't know if what I did was correct?

Thanks!

**Comment by justinr1234** [comment]
The error in the log likely mentions calling prevent default twice. The SmartForms code already prevents default before calling this callback. If you remove it altogether that should fix it. If that works, please open a pull request against `devel` branch.

**Comment by valgalin** [comment]
Hello @justinr1234 ,

Thanks for the response! I will open a pull request.

Just to be sure I understand what you mean, I will remove `event.preventDefault();` from both the edit and reply methods, right?

**Comment by justinr1234** [comment]
Yes, that should fix it. This is why: https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-forms/lib/components/FormSubmit.jsx#L28

It's already being called there.

**Comment by valgalin** [comment]
Thanks a lot, @justinr1234 ! :+1:
