### ISSUE TITLE
Moving Parts React Router V4

### ISSUE THREAD

**Issue by MHerszak** [VulcanJS/Vulcan#1878]
I am looking into RRV4 and I am unsure as to where to begin. And I am just writing them down as I go through the error messages.

Currently affected files

- render_context.js (changes react-router -> react-router-dom)

- vulcan:routing/lib/server/router.jsx (changes react-router -> react-router-config & react-router-dom)

- vulcan:routing/lib/server/router.jsx (There is no `match` function anymore)

Because I believe we want to keep `RouterServer.run` in `vulcan-routing` we would have to mimick match? 

We could:
```
import { matchRoutes } from 'react-router-config'
import { matchPath } from 'react-router-dom';

routes.some(route => {
      const match = matchPath(req.path, route);

      if (match) ...do something

      return match;
});

or

const branch = matchRoutes(routes, req.url);
const promises = branch.map(({ route }) => {
  ... return or fetch data
});
```
I am rooting for `matchRoutes`, it uses `matchPath `.

Current routes structure:
```
routes =>  { path: '/',
    component: 
        { [Function: GraphQL]
      displayName: 'withCurrentUser(App)',
      WrappedComponent: 
       { [Function: App]
        propTypes: [Object],
        childContextTypes: [Object],
         displayName: 'App' },
      contextTypes: { client: [Object], getQueryRecycler: [Object] } },
   indexRoute: 
    { name: 'movies',
     componentName: 'MoviesList',
      component: 
       { [Function: GraphQL]
         displayName: 'withCurrentUser(withApollo(withState(withList(MoviesList))))',
         WrappedComponent: [Object],
         contextTypes: [Object] } },
   childRoutes: 
    [ { name: 'resetPassword',
       path: '/reset-password/:token',
        componentName: 'AccountsResetPassword',
        component: [Object] },
     { name: 'enrollAccount',
       path: '/enroll-account/:token',
       componentName: 'AccountsEnrollAccount',
        component: [Object] },
      { name: 'app.notfound',
        path: '*',
        componentName: 'Error404',
        component: [Object] } ] }
```
The structure we might need:
```
const routes = [
  {
    component: App,
    routes: [ { name: 'resetPassword',
       path: '/reset-password/:token',
        componentName: 'AccountsResetPassword',
        component: [Object] },
     { name: 'enrollAccount',
       path: '/enroll-account/:token',
       componentName: 'AccountsEnrollAccount',
        component: [Object] },
      { name: 'app.notfound',
        path: '*',
        componentName: 'Error404',
        component: [Object] } ]
  }
];
```

Sorry, this isn't in order but rather a reflection of where I am with RRv4. What are your thoughts?

**Comment by justinr1234** [comment]
I think it would be wise to allow a swap between 3 or 4. I’m not sure everyone would be happy to have a wholesale swap to 4. Would be a large breaking change.

**Comment by justinr1234** [comment]
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md

**Comment by MHerszak** [comment]
I like your idea @justinr1234. You could swap packages but the way you add the routes should stay the same, correct? What bugs me about the migration guide is that someone one Medium wrote a better one (look for unofficial migration guide react router 4). Most of the posts do not talk about SSR aspects @SachaG . Also, I went through some of the starter apps (express and RR4) and it is really inconclusive which one seems to work better. One that I like is [here](https://github.com/bertho-zero/react-redux-universal-hot-example/blob/b65ad7eaabfaaafd0caf0d3c86c8e66c120fa843/src/server.js#L131) I keep looking.

**Comment by SachaG** [comment]
> I think it would be wise to allow a swap between 3 or 4. I’m not sure everyone would be happy to have a wholesale swap to 4. Would be a large breaking change.

Not sure I agree. Seems like supporting both at the same time or even just swapping would be a pain to maintain, and also potentially cause a lot of confusion.

**Comment by MHerszak** [comment]
Also true.

**Comment by SachaG** [comment]
It's still on the roadmap… that being said Vulcan has its own thin wrapper on top of RR so ideally it shouldn't matter which version is actually used.

**Comment by eric-burel** [comment]
RR4 is used in the new Apollo 2 version. Breaking changes are numerous but most are documented in the React Router update doc, Vulcan's API is mostly the same.
