### ISSUE TITLE
Vulcan v1.8.9 - example-forum package, issues with posts categories ?

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan#1881]
Hi,

1. In the v.1.8.9, all categories that belong to the post are not showing under the title (like before, up to version 1.8.5).
When I look into more detail, it seems that when I insert a new post, the posts field post.categories is now post.categoriesIds but in the forum-package, some code still refer to post.categories.

I try to update the code myself but end up with the following error:
graphQLErrors: 
I20180204-09:04:48.598(7)?    [ { message: 'Field "categoriesIds" must not have a selection since type "[String]" has no subfields.',
I20180204-09:04:48.598(7)?        locations: [Array] } ],
I20180204-09:04:48.598(7)?   networkError: null,
I20180204-09:04:48.598(7)?   message: 'GraphQL error: Field "categoriesIds" must not have a selection since type "[String]" has no subfields.',
I20180204-09:04:48.599(7)?   extraInfo: undefined,
I20180204-09:04:48.599(7)?   queryErrors: [ [Circular] ] }

2. The v1.8.9 introduce also ParentID in the category collection. But when a category is a main category (not a sub-category), the field ParentID still force to choose one category as its parentID !

3. The example forum works fine up to version 1.8.5 but since then seem to have bugs related to the fact that the fragment name have to be unique.

Please help.

Thank You
Adalidda

**Comment by SachaG** [comment]
Oh right. Hopefully this should fix it: https://github.com/VulcanJS/Vulcan-Starter/commit/b17aa53b9d9d1dc2fef96a09f554b78ad307db09
