### ISSUE TITLE
simpl-schema version in package.json

### ISSUE THREAD

**Issue by vincro** [VulcanJS/Vulcan#1882]
I use the two repo solution, and roll my own package.json but I note that in the Vulcan repo the simpl-schema package.json is running as:

`"simpl-schema": "^0.3.2",`

and not:

`"simpl-schema": "^1.4.1",`

I notice one or two issues have been opened, and I know I had some issue with autoValue and others that were fixed with an update.  Perhaps prudent to upgrade the version, if this does not break anything from your side.  

I do not use SmartForm etc, so cannot validate such breaking changes.

V -

**Comment by SachaG** [comment]
Good point. I'll update on `devel` and see what happens! For reference, the SimpleSchema changelog: https://github.com/aldeed/simple-schema-js/blob/master/CHANGELOG.md

**Comment by vincro** [comment]
Might be worth doing a few different updates, but simpl-schema came to mind given recent comments.

**Comment by SachaG** [comment]
I've updated SS on `devel`, seems to work ok so far.
