### ISSUE TITLE
Registration form does not display errors (password too short, username already taken, etc.) in production (but does in development)

### ISSUE THREAD

**Issue by Discordius** [VulcanJS/Vulcan#1888]
The registration/Sign-in form still seems to have some bugs in production. It seems that the signup button doesn't do anything when the form throws an error, and the error doesn't display at all.

**Comment by SachaG** [comment]
Maybe we should seriously start thinking about overhauling that accounts package?

**Comment by vincro** [comment]
Maybe a good idea.

**Comment by SachaG** [comment]
I'll assume this is fixed on `devel`, closing it for now.
