### ISSUE TITLE
On production: Store doesn't reset on login anymore

### ISSUE THREAD

**Issue by Discordius** [VulcanJS/Vulcan#1889]
Another bug in the series of LoginForm/RegistrationForm bugs: The store no longer resets when you log in on production, which means that you sometimes get slightly invalid data, and things don't properly rerender.

**Comment by SachaG** [comment]
It does seem to be resetting for me? At least on http://zenshome.jp/.

**Comment by SachaG** [comment]
I'll close this for now.
