### ISSUE TITLE
No data send to engine.apollographql.com

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan#1910]
Hi,

I add my Apollo Engine key to my settings with:
    "apolloEngine.apiKey": "service:adalidda-siteweb:XXXXXXXXXXXX",

I install Apollo Engine npm package with:
    npm install --save apollo-engine

then I build and deploy my app as I done usually.

But when I check on https://engine.apollographql.com/service/adalidda-siteweb

The status is awaiting connection and I don't get any data in the performance report.

What am I missing to make Apollo Engine works with Vulcan ?

Thank You
Adalidda

**Comment by SachaG** [comment]
You have to add it like this:

```
"apolloEngine": {
    "apiKey": "service:adalidda-siteweb:XXXXXXXXXXXX"
  },
```

Is that what you did?

**Comment by adalidda** [comment]
Oh, I see.

Thank You so much SachaG

**Comment by adalidda** [comment]
It' s working now. It really great to have Vulcan supporting Apollo Engine !

Thank You for making this happen.

**Comment by SachaG** [comment]
Great :)
