### ISSUE TITLE
Swap from react-cookie to js-cookie

### ISSUE THREAD

**Issue by justinr1234** [VulcanJS/Vulcan#1912]

**Comment by SachaG** [comment]
I just used react-cookie for SSR actually, seems to work well. Any reason to switch?

**Comment by SachaG** [comment]
What's not standard about it? Also it works with SSR, so that's a plus.

**Comment by justinr1234** [comment]
@SachaG You fixed it by upgrading to the latest version: https://github.com/VulcanJS/Vulcan/commit/fc67471a38b646064fc728f767e8d8a1d6843903#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Previously the interface was `Cookies.save` which doesn't match the standard `set` and `get`: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies/set

But they fixed it in the version you upgraded to, so this tick is not longer necessary.
