### ISSUE TITLE
Fix intercom user_id

### ISSUE THREAD

**Issue by justinr1234** [VulcanJS/Vulcan#1914]
`signin:1 Uncaught (in promise) {"type":"error.list","request_id":"b1oild14o597jp6a8hog","errors":[{"code":"conflict","message":"Multiple existing users match this email address user@example.com - must be more specific using user_id"}]}`

Add `user_id` here: https://github.com/VulcanJS/Vulcan/blob/ecf5c4c49e7bc7b8106fbf85d348751ae25073ed/packages/vulcan-events-intercom/lib/client/intercom-client.js#L16

**Comment by SachaG** [comment]
I thought I fixed that? Doesn't work?

https://github.com/VulcanJS/Vulcan/blob/ecf5c4c49e7bc7b8106fbf85d348751ae25073ed/packages/vulcan-events-intercom/lib/client/intercom-client.js#L21

**Comment by justinr1234** [comment]
Somehow I missed that, thanks!
