### ISSUE TITLE
Vulcan 1.8.9 Example Forum - Bug when display post found through query

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan#1920]
Hi,

When we do search through a query, we got a list of posts that match the query. However when we click on  any post on the list, the post is displayed but after some second, we got automatic redirection to the home page.

It seem that the issue is related to the timer used in the query, after the post is displayed, the query consider that no result found to the query (the timer is still effective) then after some second, redirect automatically to the home page.

Thank You
Adalidda

**Comment by SachaG** [comment]
Thanks! should be fixed now. Btw for any issues related to the forum package please use the [Starter repo](https://github.com/VulcanJS/Vulcan-Starter/).

**Comment by adalidda** [comment]
Thank You Sacha. OK, will use the starter repo.
