### ISSUE TITLE
[Discuss] Vulcan switch to NPM module ? the roadmap ? Vulcan 2.0 ?

### ISSUE THREAD

**Issue by comus** [VulcanJS/Vulcan#1931]
> sorry for my english, not my native language

hi, all. We may discuss the best direction for Vulcan 😄 

## NPM module ?

recently i switch my project to `Next.js`.
it is great that i can easily use their deploy solution `NOW`.
but i love meteor too much. i found their `meteor-accounts-*` packages useful. i don't want to spend too much time to develop a new account system with `passport.js` (no confidence, my project almost meet deadline)

so i created a NPM module to integrates with those library and use it in `Next.js`:
- mongodb-prebuilt (easily to create mongo-dev-server in development)
- Some Meteor Packages for Mongo and Auth (remove fibers code to just use async await)
  - mongo
  - accounts-base
  - accounts-google (my project only need google oauth)
  - accounts-oauth
  - accounts-password
  - google-oauth
  - oauth
  - oauth2
  - email
 
## Meteor ?

i don't need Meteor because
- my project don't use DDP
- my project don't use minimongo
- my project just a website, so don't need to convert to iOS or android app by meteor
- i want to create a code-splitting pages app like `Next.js`. Meteor dynamic import not good at this
- slower build time
- a little bit hard to deploy

i need Meteor because
- their auth system is useful
- i like mongo-dev-server

## Code Splitting by Pages ?

and recently i found another library `After.js` may works on meteor to create pages app.
`After.js` can't directly use in meteor. so i copied After.js code to [meteor-pages](https://github.com/comus/Vulcan/tree/next/packages/meteor-pages)
with `meteor-pages`. create `/imports/pages/*.js` and `/pages.config.js` files and meteor can handle those pages by routes.

notes that `meteor-pages` use `react-router v4` and meteor dynamic import for pages code-splitting

## Pages + Meteor + Next.js ??

thanks `After.js`. so that i can create pages app in meteor easily.
and i think i may create a NPM module ([vulcan-next](https://github.com/comus/Vulcan/tree/next/packages/vulcan-next)) that works on both `Meteor` and `Next.js`

`vulcan-next` can add server modules by `Vulcan.addServerModule(...)`
and add app modules by `Vulcan.addAppModule(...)`
those modules contains hooks functions such as `setup`, `startup`, `beforeStartup`
see: https://github.com/comus/Vulcan/blob/next/examples/simple-todos/server.js

below is demo show that how it works in meteor and next.js
sorry that i am lazy to convert all Vulcan code to the new modules structure.
below just a todos demo with simple auth

demo sources: [examples](https://github.com/comus/Vulcan/tree/next/examples)
demo video: [here](https://www.youtube.com/watch?v=_YeJA4kvL8c)

## Feature: Auth Methods

All login/auth use `methodInvoker ` to communicate with server

see: https://github.com/comus/Vulcan/blob/next/packages/vulcan-next/lib/methods/server.js#L26

app can then call `applyMethod` to call the apolloClient mutation:

see: https://github.com/comus/Vulcan/blob/next/packages/vulcan-next/lib/methods/client.js#L51

## Vulcan 2.0

i don't know what is the best direction for Vulcan 2.0

we may discuss this topic more. Sometimes i copied some Vulcan code to my working projects.
and i think most most most of Vulcan code logic not depends on Meteor.

but Meteor is good. and the build time become shorter. and Meteor will improve more and more.
What do u guys think ? Meteor? Next.js? both? new Accounts system? passport.js? Auth0?

just share how i use above library to create my project(graphql + auth + next.js + some vulcan code) recently.

thanks Vulcan project i learn a lot how to create a graphql app on it

:)

**Comment by macrozone** [comment]
just a note on code-splitting:

it's fairly easy to use code splitting with meteor by component, so you can also use this to do code splitting by page:

use https://github.com/jamiebuilds/react-loadable and wrap your page-components in this hoc. Check that this component and its dependencies are not eagerly loaded (which could be currently the case with vulcan)

on the discussion:

I just recently discovered vulcan and i like many of its aspect. For me, it's a framework to create admin/operator-frontends on existing apps that needs a lot of CRUD and lists.

I am not sure whether i would use it for end-user apps. I think end-user apps are best written standalone (not fullstack). If the end-user-app is a webpage, use next or a create-react-app, if its an mobile app, use react-native (create-react-native-app). If this page needs administration and content managment, use vulcanjs for that.


So for vulcan 2.0 my wishlist would be:

- remove some technical debt
- remove meteor-package structure
- focus more on admin, content-managment and CRUD features

**Comment by jkbaseer** [comment]
Irrelavant to the Title of NVM but relevant to the Direction i guess :) 

I have watched the videos i can about VulcanJs from the youtube channel and sort of bit familiar with its documentation as well. 

You can consider me as non technical person but sort of like mass audience who want to still achieve the features it has.

There are two things i really liked about the product architecture from sacha video
- Flexibility and freedom in terms of stack the developers want to work on while using Vulcan
- Being between advanced frameworks and less like CMS (Below pic) @SachaG  you shared on the vision of vulcanJS at Algolio event. 

Happy to be on the top end technologies but it will be good if we align to this as well. 
![image](https://user-images.githubusercontent.com/968274/37565459-be410d90-2ae4-11e8-82d3-6d814e365dcf.png)

anyway my comment take it as a pinch of salt as am very new to this things but been using wordpress for last 7 years as a amateur user :) 
Apologise if this is irrelevant!

**Comment by comus** [comment]
say more what i want Vulcan to become...

## core

- not limited run on Meteor only, that's means:
  - On server side, Vulcan can exports middleware or server, you can use middleware or server anywhere when you want to start the server
    such as: https://github.com/comus/Vulcan/blob/next/examples/meteor-simple-todos/server/main.js#L5
  - On client side, Vulcan can exports hocs such as AppProvider, with AppProvider, you can use app instance do anything what you want
    such as: https://github.com/comus/Vulcan/blob/next/examples/meteor-simple-todos/imports/pages/about.js#L5

- so that we can use Vulcan on `Next.js`, `razzle`, `Meteor`. not limited how you use it.

- no globals, because `server` and `app` instance i talked above.
    - keep most of library logic/code under Vulcan object. ex. `Vulcan.addServerModule`, `Vulcan.isServer`, `Vulcan.createServer`
      such as: https://github.com/comus/Vulcan/blob/next/packages/vulcan-next/server/init.js#L5
    - `server` and `app` instance have functions. ex `app.getSettings`, `server.registerGraphqlFragment`, `server.getGraphqlMutation`
      such as: https://github.com/comus/Vulcan/blob/next/packages/vulcan-next/lib/graphql-schema/server.js#L42

- modules and hooks run when creating `server` or `app`
  -  custom server module, contains many hooks such as `setup`, `startup`
      means that when creating server, run all modules' s setup hooks, and then startup hooks
      such as: https://github.com/comus/Vulcan/blob/next/examples/meteor-simple-todos/server/main.js#L14
  - custom app module, the same contains many hooks

- auth with apollo mutation
  - client `app` can call apollo mutate function to login/logout, ex `app.loginWithGoogle`
     such as: https://github.com/comus/Vulcan/blob/next/packages/vulcan-next/lib/accounts/accounts-google/client.js#L52
  - server mutation resolver received those login/logout request and handle it
    such as: https://github.com/comus/Vulcan/blob/next/packages/vulcan-next/lib/methods/server.js#L26

## graphql related

- add more flexible function to handle graphql fragment, queries, mutations
    - with register graphql query/mutation, i can use those registered query/mutation in hocs
      such as: https://github.com/comus/Vulcan/blob/next/packages/vulcan-next/lib/settings/client.js#L30
    > app.registerGraphqlFragment
    > app.extendGraphqlFragment
    > app.getGraphqlFragment
    > app.registerGraphqlQuery
    > app.getGraphqlQuery
    > app.registerGraphqlMutation
    > app.getGraphqlMutation

- i know that defaultResolver and defaultMutation in Vulcan is great. but we may need other helpers for custom resolvers/mutations (my project always need custom resolvers)
  - helper functions such as: `checkIsAdmin`, `checkCurrentUser`, `checkRequiredFields`, `checkExistsUserById`, `checkNotExistsUserByDoc`

## other

- apollo client 2

- react router 4

- formik

- no bootstrap, but user may add material-ui/styled-jsx/styled-components

- hocs, ex:
  - Vulcan.withAppProvider
  - Vulcan.withCurrentUser
  - Vulcan.withAppSettings
  - Vulcan.withGraphql

if Vulcan can develop like this way. many react project can use Vulcan to create a graphql+react app i think.

currently my project switch to `Next.js` and copy some Vulcan code to use it like this way

i focus on core more. because change the core and many project(not only meteor) can use Vulcan

**Comment by SachaG** [comment]
Oh I think we can keep this open? I didn't reply yet because it's a complex topic and I wanted to take my time to answer, not because I don't think it's important :)

**Comment by SachaG** [comment]
Yeah we need to update to 2.x. @MHerszak any progress? I might take a look myself if you feel like you won't be able to complete the migration?

**Comment by MHerszak** [comment]
I haven't touched Apollo in a while. However, all Fragments for currentUser need to include @client or nothing for when you want to extract the currentUser for instance. Since fragments are loaded for client and server you will have to do something like this `!Meteor.isServer ? @client : ''`. This works with the pull request I had a couple of weeks ago. I only tested it with the simple package example, though.

**Comment by comus** [comment]
~ demo time ~

i published a **Meteor** package for a **demo** to use **pages** (support getInitialProps) in Meteor, `vulcanbeta:core`

it has 3 dependencies, `vulcanbeta:lib`, `vulcanbeta:pages`, `vulcanbeta:accounts`

`vulcanbeta:lib` contains some utils functions, ex Mongo without fibers
`vulcanbeta:pages` contains after.js files
`vulcanbeta:accounts` contains `accounts-base` and `accounts-password`
(graphql auth and without fibers)

**how to use it?**

1. `.packages`, lightweight that i just need install the minimal Meteor packages
```
meteor@1.8.6
webapp@1.5.0
standard-minifier-css@1.4.0
standard-minifier-js@2.3.1
ecmascript@0.10.0
shell-server@0.3.1

vulcanbeta:core
```

2. `npm i ...`, required apollo2 and react-router4, see https://github.com/comus/demo/blob/master/package.json

3. `/server/main.js`, need create a server instance on server side
```js
import { Meteor } from 'meteor/meteor'
import { createServer } from 'meteor/vulcanbeta:core'
import merge from 'lodash/merge'

Meteor.startup(() => {
  const server = createServer({
    dev: Meteor.isDevelopment,
    settings: merge({}, Meteor.settings, {
      public: {
        debug: true
      }
    }),
    modules: []
  })

  Promise.await(server.start())
})
```

4. `/client/main.js`, need to run react when DOM loaded
```js
import { Meteor } from 'meteor/meteor'
import { Pages } from 'meteor/vulcanbeta:core/app'

Meteor.startup(() => {
  Pages.start()
})
```

5. `/imports/pages/index.js`, support magic getInitialProps
```js
import React from 'react'
import { Link } from 'react-router-dom'
import { compose, withAppProvider, withCurrentUser } from 'meteor/vulcanbeta:core/app'

class Index extends React.PureComponent {
  static async getInitialProps (ctx) {
    await new Promise((resolve) => {
      setTimeout(() => {
        resolve()
      }, 5000)
    })

    return {
      bbb: 1
    }
  }

  render () {
    return (
      <div>
        hi {this.props.currentUser && this.props.currentUser.username}
        <Link to='/about'>About</Link>
        <style jsx global>{`
          body {
            background: pink;
          }

          div {
            color: red;
          }
        `}</style>
      </div>
    )
  }
}

export default compose(
  withAppProvider(),
  withCurrentUser
)(Index)
```

6. `meteor run`

**That's it**
- it support accounts-password, create account just type
```js
app.accounts.createUser({ username: 'comus', password: 'password' })
```
![image](https://user-images.githubusercontent.com/1200981/38176484-5e51bada-3622-11e8-8c3f-af8cd777a0a6.png)

- for more infomation

  - https://github.com/comus/Vulcan/pull/9 i am trying update my version vulcan, but i dont have much time

  - demo source code (https://github.com/comus/demo)

  - VulcanJS/Vulcan core merge a lot together, i mean there are a lot functions in core/lib. it's hard to split the real core logic independently, i think small `core` is better, core just focus on plugin/callback/modules handle, routing, graphql staff/communication and auth. other code such as defaultresolver, components, i18n may be handle by other vulcan package (or vulcan-boost)

  - and then the core can change to npm module in the future

**Comment by MathiasKandelborg** [comment]
This is quite awesome, is any further work being done on it?

**Comment by SachaG** [comment]
Just wanted to say I haven't forgotten about this, just really busy these days and I want to get a couple other things out the door first.
