### ISSUE TITLE
[devel] Bug in Forms control: editing required fields

### ISSUE THREAD

**Issue by Apollinaire** [VulcanJS/Vulcan#1942]
When on an edit form, on a required text input, if you delete every character it gets overwritten with what was previously prefilled. 

How to reproduce: use Vulcan devel + Vulcan-starter, package example-forms.
Create a new customer, let's call it Sacha, then click 'Edit' to open the edit modal form. 
In the field `Name`, remove every character. It's ok until you remove the first S, after what the field gets written with the full previous name, aka Sacha. 

If i'm not being clear enough i'll provide screenshots

**Comment by SachaG** [comment]
Oh right, that makes sense. We need to add the field to `deletedValues` when it's cleared.

**Comment by SachaG** [comment]
Actually this code should already take care of it?

https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-forms/lib/components/FormComponent.jsx#L27-L30

**Comment by SachaG** [comment]
OK, can I close this then?

**Comment by Apollinaire** [comment]
I closed this and the PR :)
