### ISSUE TITLE
[devel] form errors are not correctly labelised

### ISSUE THREAD

**Issue by Apollinaire** [VulcanJS/Vulcan#1944]
The problem comes from this snippet of code in [Forms.jsx](https://github.com/VulcanJS/Vulcan/blob/150f4107dd89d03bad1d06f9f818aaa41a1a45aa/packages/vulcan-forms/lib/components/Form.jsx#L321): 
```js
  getErrorMessage = error => {
    console.log(error);
    if (error.data.fieldName) {
      // if error has a corresponding field name, "labelify" that field name
      const fieldName = this.getLabel(error.data.fieldName);
      return this.context.intl.formatMessage({ id: error.id, defaultMessage: error.id }, { ...error.data, fieldName });
    } else {
      return this.context.intl.formatMessage({ id: error.id, defaultMessage: error.id }, error.data);
    }
  };
```
and more specifically: 

`if (error.data.fieldName) {`
The condition is looking for `error.data.fieldName`, which never exists because the field name is inside `error.data.name`
Should we just call `error.data.name` or keep `error.data.fieldName` and change the attribute in where errors are generated? 

EDIT : Actually `getErrorMessage` is never called so field errors are never labelized. I guess this function stayed here from the previous way we handled errors.

**Comment by SachaG** [comment]
Yes, I think we can remove that bit of code. And I used `error.data.name` because that's what the errors generated by SimpleSchema look like.
