### ISSUE TITLE
Vulcan.js with git bash on windows using powershell

### ISSUE THREAD

**Issue by anderskitson** [VulcanJS/Vulcan#1946]
I am using bash on Ubuntu on windows, I open powershell and the run command bash I navigate to the Vulcan-starter repo I cloned. I have installed meteor using the curl command as recommended on Meteor's website. I am using node version 8.11.1 I run npm install and everything installs fine, when I run npm start this is where I get the errors. Here is the error below, and a more detailed log is included in this [gist](https://gist.github.com/anderskitson/bc6d853ac35e2e84c27ea7e3e102db09).

```
MongoDB had an unspecified uncaught exception.
This can be caused by MongoDB being unable to write to a local database.
Check that you have permissions to write to .meteor/local. MongoDB does
not support filesystems like NFS that do not allow file locking.
npm ERR! code ELIFECYCLE
npm ERR! errno 254
npm ERR! Vulcan@1.8.11 start: `meteor --settings settings.json`
npm ERR! Exit status 254
npm ERR!
npm ERR! Failed at the Vulcan@1.8.11 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anderskitson/.npm/_logs/2018-03-30T21_21_54_469Z-debug.log
```

**Comment by justinr1234** [comment]
You can’t run Meteor with Mongo this way in Windows. Your error message points out `MongoDB does
not support filesystems like NFS that do not allow file locking.`

Windows file systems are NFS. You need to follow the official Meteor tutorial about how to run Meteor on Windows: https://www.meteor.com/install

**Comment by anderskitson** [comment]
Can I still use bash though, because I did install meteor via choco, however when I run npm start under bash I get this error. I am able to run meteor under powershell or command prompt however I was hoping to use bash.

**Comment by justinr1234** [comment]
I don't believe so, but the way the tool is working is that it's trying to run it in a way that it tries to take a lock on the filesystem. Likely Mongo thinks its running on a system that supports file locking, which it isn't.
