### ISSUE TITLE
Datatable: client crashes on submitting new document with graphQL only fields

### ISSUE THREAD

**Issue by Apollinaire** [VulcanJS/Vulcan#1947]
Context: I have a datable showing a collection, let's call it movies. Part of the data displayed is loaded through **graphQL only fields**, for example the user's username. I give a fragment with `user`: {username}' as `options` prop to datatable. In the datatable, everything works fine, the username is displayed by a custom component that simply looks into `document.user.username`.

Now comes the problem: when i click the New button, fill the needed fields, and then click Submit, the client crashes. 
First, I get a warning from Apollo : missing field user in {_id : "...", other_fields: "..."}  which shows that it seems to be expecting the field user in the document that i just submitted. I don't know if this is when i submit the form or when withList(DatatableContents) asks for the data.

Second, I get a big fat error from React: 
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at DatatableContents (Datatable.jsx:167)
```
There in Datatable.jsx i see: 
```js
  const {collection, columns, results, loading, loadMore, count, totalCount, networkStatus, showEdit, currentUser, emptyState} = props;

  if (loading) {
    return <div className="datatable-list datatable-list-loading"><Components.Loading /></div>;
  } else if (!results.length) {
    return emptyState || null;
  }
```
which basically means that `results` is undefined. It comes from `withList` which wraps DataTableContents.
When i add a console.log(results) in DatatableContents, i can see that it is undefined at one moment.

So here are my questions:
- Can anyone reproduce this ?
- Why is `withList` returning no data after i submit a new document, only when there is some graphQL only fields?

**Comment by Apollinaire** [comment]
Additional info: the document is correctly submitted to the db, when i refresh the page it appears in the datatable, with every data working well.

**Comment by justinr1234** [comment]
Can you post the full Apollo error? It should show up on the backend and/or the frontend. This is likely an issue where your resolver failed (threw an error). Check all the resolvers of all the fields included in your fragment. Do a few try catch/blocks in them (particularly any you think are suspicious).

**Comment by SachaG** [comment]
Can you also post your fragment?

**Comment by dbrrt** [comment]
@Apollinaire Can you post a reproducible example?

**Comment by Apollinaire** [comment]
@justinr1234 the Apollo **warning** is the following: 
```
Missing field user in {
  "_id": "i4WDwfTPnjPrXYLMw",
  "firstName": "test3",
  "lastName": "test",
```
And it's followed by the other fields/properties of the schema. 
`user` is the graphQL only part of my schema: 

```js
  userId: {
    type: String,
    optional: true,
    viewableBy: ['members'],
    resolveAs: {
      fieldName: 'user',
      type: 'User',
      resolver(candidate, args, context) {
        return context.Users.findOne(
          {
            _id: candidate.userId
          },
          {
            fields: context.Users.getViewableFields(context.currentUser, context.Users)
          }
        );
      },
      addOriginalField: true
    }
  },
```

And here is my fragment: 
``` 
 fragment CandidatesItemFragment on Candidate {
    _id
    createdAt
    userId
    user {
      username
      _id
    }
    firstName
    lastName
  }
```
If i remove `user {username _id} ` from the fragment, there is no error anymore. 
I'm using default resolvers and mutations.

**Comment by Apollinaire** [comment]
Ok everyone,  i'm sorry for bothering you with this for nothing, I found out it comes from the [vulcan-material-ui](https://github.com/ErikDakoda/vulcan-material-ui) implementation of datatable.jsx. You can all forget about this issue, i'll look into the package and fix it by comparing it to the vulcan source code
