### ISSUE TITLE
"Getting started" - Multiplied records in step 17

### ISSUE THREAD

**Issue by mkbctrl** [VulcanJS/Vulcan#1951]
Hey, I was playing around with Vaulcan for better understanding how it works, and in Step 17 I’ve encountered a weird behaviour.
When I add a new movie and submit it, it appears in the table multiplied by N. Sometime it’s 3 records, sometime its 11 records.

After a second or two, everything goes back to normal.
Just curious, what might be causing such issue. Any ideas?

I was following the steps from the tutorial by uncomenting stuff, so I didn’t add anything on my own.

**Before**
![screen shot 2018-04-10 at 20 59 51](https://user-images.githubusercontent.com/10107362/38600799-b5947a40-3d65-11e8-9a07-4a36a9f71a75.png)

**After few seconds**
**
![screen shot 2018-04-10 at 20 59 58](https://user-images.githubusercontent.com/10107362/38600810-c442f4cc-3d65-11e8-9750-b3d75c1ffbd2.png)
**

**Comment by SachaG** [comment]
On that topic, I think we'll have to revisit the post-mutation update code when we switch to Apollo 2.x anyway.

**Comment by MathiasKandelborg** [comment]
I noticed the same thing in that package. I haven't encountered this in my own code though, so I've not thought much of it since. I'll be sure to test for this in various environments when updates come around.

**Comment by Apollinaire** [comment]
I noticed this in the movies package too some time ago, up to 5-6 occurences of the same document showing in the list of movies just after this document is added. Returns to normal after the data fetch from withlist

**Comment by eric-burel** [comment]
Stale, this part of the code changed a lot in Apollo 2 and should be less buggy
