### ISSUE TITLE
Forum: voting per category

### ISSUE THREAD

**Issue by wassim** [VulcanJS/Vulcan#1977]
I'm looking for an independent vote scoring per category like users votes on category A will not affect post rating on category B.

Is this something possible?

**Comment by SachaG** [comment]
I'm not sure I understand what you mean. Do you mean rating an item on different criteria? If so yes, that's possible. Check out the "reactions" example.

**Comment by SachaG** [comment]
Also this should be on the Starter repo, so I'll close it here.
