### ISSUE TITLE
Create-vulcan-app

### ISSUE THREAD

**Issue by FedorArbuzov** [VulcanJS/Vulcan#1979]
Is there an analogue of the create-react-app for the vulcan?

**Comment by Apollinaire** [comment]
It's all in two command lines:
`git clone https://github.com/vulcanjs/vulcan.git`

`git clone https://github.com/vulcanjs/vulcan-starter.git`

**Comment by SachaG** [comment]
There's actually a CLI scaffolding tool but I sadly don't have the time to maintain it myself: https://github.com/VulcanJS/vulcanjs-cli
