### ISSUE TITLE
Dropdown.Toggle props are not accessible in Components.Dropdown

### ISSUE THREAD

**Issue by lc3t35** [VulcanJS/Vulcan#1983]
If you want to change the gray background that appears in Dropdown
![capture d ecran 2018-05-10 a 12 10 25](https://user-images.githubusercontent.com/921372/39866071-54e1781e-544f-11e8-8477-8803b47813a3.png)
you need to add a specific className in vulcan-ui-bootstrap, ui/Dropdown.jsx
````
<Dropdown.Toggle className="ddown" >{trigger}</Dropdown.Toggle>
````
and add in css :
````
.ddown { background: transparent; }
````
![capture d ecran 2018-05-10 a 12 36 41](https://user-images.githubusercontent.com/921372/39866240-18d68c6e-5450-11e8-9f81-303c65062417.png)

add a toggleProps as additional option in Dropdown ?
````
<Dropdown.Toggle {toggleProps} >{trigger}</Dropdown.Toggle>
````

**Comment by SachaG** [comment]
I think `toggleProps` might be a bit redundant given that you can already pass a `trigger` component to replace the toggle. But I'm open to it if it's useful.

**Comment by lc3t35** [comment]
As discussed on Slack, it allows here to modify the Dropdown.Toggle not the trigger ;)
