### ISSUE TITLE
vulcan:admin -> removing groups through admin interface

### ISSUE THREAD

**Issue by mazli84** [VulcanJS/Vulcan#1993]
I have added a custom group. I call it sales.

When I try to assign a user to it through the admin panel with the checkbox, it works.
However, when I try to remove the user from the group by unticking the checkbox, it stays in the group, does not update even when I click submit. 

Do you have any clue what do I do wrong?

**Comment by SachaG** [comment]
Sounds like a bug. I'll check it out, thanks!

**Comment by mazli84** [comment]
I use 1.9.1

**Comment by Apollinaire** [comment]
It might come from [`vulcan:users schema.js`](https://github.com/VulcanJS/Vulcan/blob/1f389dbf0a2ca9b6c8f435a884d551ba9955080b/packages/vulcan-users/lib/modules/schema.js#L252) 
I'm working with this code for the `groups` field: 
```js
  /**
    Groups
  */
  groups: {
    type: Array,
    optional: true,
    control: "checkboxgroup",
    insertableBy: ['admins'],
    editableBy: ['admins'],
    viewableBy: ['guests'],
    group: adminGroup,
    options: function () {
        const groups = _.without(_.keys(getCollection('Users').groups), "guests", "members", "admins");
        return groups.map(group => {return {value: group, label: group};});
      }
  },
  'groups.$': {
    type: String,
    optional: true
  },

```
I simply took the `options` key out of `form` to put it at the root of the field. I don't have special groups, so i did not test it completely, but it works for admins. I think the api to give options changed from 
```js
field: {
   form: {
      options: { }
   }
}
```
to: 
```js
field: {
   options: { }
}
```
but the users schema has not been updated yet to follow these rules. 
I'm on 1.9.1 too

**Comment by mazli84** [comment]
I have tried your idea @Apollinaire . No luck though. The admin rights are fine with or without taking the options to to the root of the field. However other groups are still not working. Once I click the checkbox, I can never uncheck it again. But for the first time clicking it, is fine.

**Comment by mazli84** [comment]
I did a little bit more digging. The issue is with the control: 'checkboxgroup' because when I try to change it to 'radiogroup' it updates the groups and I can change the user to be in a different group.

**Comment by SachaG** [comment]
I think this is the same issue as https://github.com/VulcanJS/Vulcan/issues/1998

If so, we can close this.

**Comment by mazli84** [comment]
Yeah. It is pretty much the same. You can close the issue. Thanks a lot.
