### ISSUE TITLE
Document how to update Vulcan version 

### ISSUE THREAD

**Issue by lorensr** [VulcanJS/Vulcan#2012]
Don't see instructions in the docs or blog post release announcements 😊

![image](https://user-images.githubusercontent.com/251288/42054156-a056b08a-7ae1-11e8-9219-c2321d49203f.png)

**Comment by SachaG** [comment]
Right, it's `meteor update` but people might not know that.

**Comment by lorensr** [comment]
https://github.com/GraphQLGuide/news/tree/master/packages

**Comment by SachaG** [comment]
Oh you're right, you do need to get the latest `_boilerplate-generator` package from https://github.com/VulcanJS/Vulcan-Starter/ as well. We should be able to get rid of that package very soon though.

**Comment by SachaG** [comment]
Alternatively you can also just delete that package to use the "real" boilerplate-generator, it only makes a difference when you're loading third-party CSS.

**Comment by lorensr** [comment]
*Just* `meteor update` wouldn't work b/c of exact versions, eg `vulcan:core@1.8.9` in `.meteor/packages` and those in `packages/example-forum/package.js`. I updated with:

```js
git remote add starter git@github.com:VulcanJS/Vulcan-Starter.git
git pull starter master
```

and fixed the merge conflicts. Now getting this error:

```
W20180629-19:12:43.328(-4)? (STDERR) ReferenceError: _ is not defined
W20180629-19:12:43.328(-4)? (STDERR)     at oauth_config.js (packages/vulcan:lib/lib/server/oauth_config.js:6:3)
W20180629-19:12:43.328(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180629-19:12:43.329(-4)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180629-19:12:43.329(-4)? (STDERR)     at main.js (packages/vulcan:lib/lib/server/main.js:1:14)
W20180629-19:12:43.329(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180629-19:12:43.329(-4)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180629-19:12:43.329(-4)? (STDERR)     at /Users/me/gh/news/.meteor/local/build/programs/server/packages/vulcan_lib.js:5459:15
W20180629-19:12:43.329(-4)? (STDERR)     at /Users/me/gh/news/.meteor/local/build/programs/server/packages/vulcan_lib.js:5466:3
W20180629-19:12:43.329(-4)? (STDERR)     at /Users/me/gh/news/.meteor/local/build/programs/server/boot.js:411:36
W20180629-19:12:43.329(-4)? (STDERR)     at Array.forEach (<anonymous>)
W20180629-19:12:43.330(-4)? (STDERR)     at /Users/me/gh/news/.meteor/local/build/programs/server/boot.js:220:19
W20180629-19:12:43.330(-4)? (STDERR)     at /Users/me/gh/news/.meteor/local/build/programs/server/boot.js:471:5
W20180629-19:12:43.330(-4)? (STDERR)     at Function.run (/Users/me/gh/news/.meteor/local/build/programs/server/profile.js:510:12)
W20180629-19:12:43.330(-4)? (STDERR)     at /Users/me/gh/news/.meteor/local/build/programs/server/boot.js:470:11
```

Repro: https://github.com/GraphQLGuide/news/tree/vulcan-2012

Not sure why—`underscore` is in my `.meteor/versions` and in here: https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-lib/package.js#L32

**Comment by SachaG** [comment]
This is because Underscore is now an explicit dependency: https://github.com/msavin/Mongol-meteor-devtools/issues/159

**Comment by lorensr** [comment]
Thanks! Got it running with:

- update vulcan to 1.11.2
- add `underscore` and `service-configuration` to `packages/news/package.js`

On load, have a couple errors. My `news` package is based on `forum` package, and I'm guessing there must have been major changes to `forum`, since I can't even find the file my error is in:

![image](https://user-images.githubusercontent.com/251288/42739575-9ea68484-8867-11e8-9192-70c9c4233c49.png)

![image](https://user-images.githubusercontent.com/251288/42739589-cb9edb6c-8867-11e8-956a-d10b65aaa10c.png)
![image](https://user-images.githubusercontent.com/251288/42739596-db31bb80-8867-11e8-9de8-76a6c5845b80.png)

Do you think it would be faster to fix the errors, or replace with the latest forum package and add my changes back in?

**Comment by SachaG** [comment]
That error means that `PostsListHeader` is not registered, maybe the file is not imported? That being said yes I would recommend always starting from the latest Starter repo code if you can.

**Comment by eric-burel** [comment]
Closing as an old issue
