### ISSUE TITLE
Error reporting integrations: tools such as Sentry, Rollbar, etc.

### ISSUE THREAD

**Issue by PolGuixe** [VulcanJS/Vulcan#2014]
I have tried to integrate Sentry into an app we are building. 

The front-end error reporting part is fairly easy, I'll publish a package soon. 😉 

The backend part is another story. 

I realized that integrating Sentry would require a lot of manual work. Migrating to a different service would then require a lot of refactoring. I thought that building an abstraction on top could be beneficial.

e.g. 

```
// app code
import {captureException} from 'meteor/vulcan-error-report-package; // find suitable name


// ... code and business logic

try {
    doSomething(a[0]);
} catch (e) {
    captureException(e);
}
```

```
// vulcan:sentry-integration package
import {setErrorTracking} from 'meteor/vulcan-error-report-package;

setErrorTracking(Raven.captureException);

```

Does it make sense?

**Comment by SachaG** [comment]
Wouldn't we need to wrap everything in `try...catch` then? Is that how Sentry works in Node apps?

**Comment by PolGuixe** [comment]
I am not sure of all the Sentry details. 

Looking at their docs: https://docs.sentry.io/clients/node/ I am not sure the `try...catch` pattern is required. Looks like you can call `Raven.captureException(/* ---error --- */)` outside a `try...catch`.  I'll have to try it I guess 😅 .

**Comment by PolGuixe** [comment]
Regarding Sentry, there is also a `requestHandler` for Express: https://docs.sentry.io/clients/node/integrations/express/

I am not sure how we can integrate it with a modular way and without adding too much overhead

**Comment by justinr1234** [comment]
This is how I implement it. It copies the code of Kadira's APM and intercepts any errors thrown by Meteor. Probably not the most verbose way of handling it though ...

```
import Raven from 'raven';
import { getSetting } from 'meteor/vulcan:core';

const dsn = getSetting('sentry.dsn');

if (!dsn) {
  // eslint-disable-next-line no-console
  console.warn('Sentry logging will not happen until you set settings in sentry.dsn');
} else {
  const release = process.env.SENTRY_RELEASE;

  if (release) {
    Meteor.settings.public.sentry.release = process.env.SENTRY_RELEASE;
  }

  Raven.config(dsn, { release }).install();

  const wrapMethodHandlerForErrors = function wrapMethodHanderForErrors(name, originalHandler, methodMap) {
    methodMap[name] = function() {
      try{
        return originalHandler.apply(this, arguments);
      } catch(ex) {
        Raven.captureException(ex);
        throw ex;
      }
    }
  };

  // TODO: Conflicts with Kadira APM
  export const wrapMethods = function() {
    var originalMeteorMethods = Meteor.methods;
    // wrap future method handlers for capturing errors
    Meteor.methods = function(methodMap) {
      Object.keys(methodMap)
        .map(name => ({
          handler: methodMap[name],
          name
        }))
        .forEach(function({handler, name}) {
          wrapMethodHanderForErrors(name, handler, methodMap);
        });
      originalMeteorMethods(methodMap);
    };

    // wrap existing method handlers for capturing errors
    Object.keys(Meteor.default_server.method_handlers)
      .map(name => ({
        handler: Meteor.default_server.method_handlers[name],
        name
      }))
      .forEach(function ({handler, name}) {
        wrapMethodHandlerForErrors(name, handler, Meteor.default_server.method_handlers);
      });
  };

  Meteor.startup(() => {
    wrapMethods();
  });
}
```

**Comment by PolGuixe** [comment]
Is Vulcan making use of Meteor Methods for the resolvers? 

As far as I know, Vulcan just uses Meteor for Accounts and as a built tool.

**Comment by SachaG** [comment]
We now have a first version of error tracking. I'll close this and we can open new threads to discuss specific issues.
