### ISSUE TITLE
Uncaught TypeError: React.createRef is not a function

### ISSUE THREAD

**Issue by deligent** [VulcanJS/Vulcan#2015]
Hi, I'm getting lots of errors when trying to implement my own package or your example package like sample, form, movies, Instagram. I think your (documentation, video tuts) too old, that does not matched with your current GitHub repository. If i'm a new user then it is very difficult to learn and implement Vulcan package in project. How I would implement my own package successfully using Vulcan repository?

Please guide me.
Thanks
![vulcanjs_error](https://user-images.githubusercontent.com/32838396/42306513-e98025dc-804c-11e8-9067-8c7c438aa4b1.png)

**Comment by SachaG** [comment]
`createRef` is only available in React 16.3 I think, so you need to upgrade React. I've also removed `createRef` on the `devel` branch, if you pull the latest commits. Btw if you're running the `devel` branch you should know that some things will break, it's not a stable branch.
