### ISSUE TITLE
Dropdown shows multiple  -- select options -- 

### ISSUE THREAD

**Issue by tokn136** [VulcanJS/Vulcan#2016]
when I type a product name and open the product selection, multiple -- select options -- are showing up in the list. Clicking the small (x) next to it removes them again. 
To reproduce checkout the Vulcan-Starter and run the forms sample package.

![bild eingefugt am 2018_07_12 02_14 pm](https://user-images.githubusercontent.com/5678193/42690018-06afa036-86a3-11e8-9cfb-f7c17e796edc.png)

**Comment by mattblackdev** [comment]
this was fixed here: https://github.com/VulcanJS/Vulcan/pull/2003
