### ISSUE TITLE
Email address verification broken

### ISSUE THREAD

**Issue by jimrandomh** [VulcanJS/Vulcan#2038]
Email address verification worked in v1.8, and was broken in the process of upgrading to Meteor 1.7.

In `meteor:accounts-base`, the accounts actions `reset-password`, `verify-email` and `enroll-account` are handled as a group; eg in [accounts_server.js](https://github.com/meteor/meteor/blob/devel/packages/accounts-base/accounts_server.js#L71) and [](accounts_client.js) their URLs are defined together. Since Vulcan isn't using hash-style routing and has its own UI, it overrides the routes [here](https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-accounts/imports/routes.js) and [here](https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-users/lib/server/urls.js) - but doesn't handle `verify-email` at all. So email address verification doesn't work; calling `Accounts.sendVerificationEmail` sends an email with a hash-style URL in it that doesn't work, and rewriting it to a non-hash-style URL doesn't work either.

**Comment by Apollinaire** [comment]
Hi @jimrandomh , I've worked a bit on the accounts part lately and I will add support for email verification, it is indeed a necesary feature.

> `Accounts.sendVerificationEmail` sends an email with a hash-style URL in it that doesn't work, and rewriting it to a non-hash-style URL doesn't work either.

What have you tried to fix this ? From what I see you need three things to make this work: 

- set `Accounts.urls.verifyEmail = token => Meteor.absoluteUrl(`verify-email/${token}`);`
- add a route to react-router : `addRoute({name: 'verifyEmail', path: '/verify-email/:token', componentName: 'AccountsVerifyEmail'});`
- Create the component `AccountsVerifyEmail` to call `Accounts.verifyEmail` and display a message

**Comment by jimrandomh** [comment]
https://github.com/VulcanJS/Vulcan/pull/2040
