### ISSUE TITLE
After updating to METEOR@1.7.0.5 application is crashing

### ISSUE THREAD

**Issue by deligence** [VulcanJS/Vulcan#2042]
Application is throwing following error after updating the meteor:

`/Users/dt/.meteor/packages/meteor-tool/.1.7.0_5.nqlbe1.vvu48++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

**ReferenceError: _ is not defined**
    at oauth_config.js (packages/vulcan:lib/lib/server/oauth_config.js:4:3)
    at fileEvaluate (packages/modules-runtime.js:322:7)
    at Module.require (packages/modules-runtime.js:224:14)
    at require (packages/modules-runtime.js:244:21)
    at main.js (packages/vulcan:lib/lib/server/main.js:1:14)
    at fileEvaluate (packages/modules-runtime.js:322:7)
    at Module.require (packages/modules-runtime.js:224:14)
    at require (packages/modules-runtime.js:244:21)
    at /Users/dt/development/project/.meteor/local/build/programs/server/packages/vulcan_lib.js:3562:15
    at /Users/dt/development/project/.meteor/local/build/programs/server/packages/vulcan_lib.js:3569:3
Exited with code: 1
Your application is crashing. Waiting for file change.`

> Underscore is already added in meteor package file.

**Comment by SachaG** [comment]
You shouldn't update Meteor yourself, you should wait until Vulcan itself is updated. But yes this is related to Meteor not finding the Underscore package for some reason.

**Comment by deligent** [comment]
I have added underscore in valcun-lib/package.js under meteor packages and above error resolved but it showing different error:
 

> valcun-lib/package.js:

```
Package.describe({
  name: 'vulcan:lib',
  summary: 'Vulcan libraries.',
  version: '1.7.0',
  git: "https://github.com/VulcanJS/Vulcan.git"
});

Package.onUse(function (api) {

  api.versionsFrom(['METEOR@1.0']);

  var packages = [

    'buffer@0.0.0', // see https://github.com/meteor/meteor/issues/8645

    // Meteor packages
    'underscore',
    'meteor-base@1.1.0',
    'mongo',
    'tracker',
    'service-configuration',
    'standard-minifiers@1.1.0',
    'modules@0.9.2',
    'accounts-base',
    'check',
    'http',
    'email',
    'ecmascript@0.8.2',
    'service-configuration',
    'shell-server@0.2.4',

    // Third-party packages

    // 'aldeed:collection2-core@2.0.0',
    'meteorhacks:picker@1.0.3',
    'percolatestudio:synced-cron@1.1.0',
    'meteorhacks:inject-initial@1.0.4',
  ];
```

>New Error:

```
W20180830-10:59:02.119(5.5)? (STDERR) /Users/dt/.meteor/packages/meteor-tool/.1.7.0_5.nqlbe1.vvu48++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180830-10:59:02.119(5.5)? (STDERR) 						throw(ex);
W20180830-10:59:02.119(5.5)? (STDERR) 						^
W20180830-10:59:02.119(5.5)? (STDERR) 
W20180830-10:59:02.120(5.5)? (STDERR) TypeError: Users.addField is not a function
W20180830-10:59:02.120(5.5)? (STDERR)     at custom_fields.js (packages/vulcan:posts/lib/custom_fields.js:3:7)
W20180830-10:59:02.120(5.5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180830-10:59:02.120(5.5)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180830-10:59:02.120(5.5)? (STDERR)     at require (packages/modules-runtime.js:244:21)
```

**Comment by SachaG** [comment]
There is no `vulcan:posts` package anymore so I'm not sure where that's coming from?
