### ISSUE TITLE
Tests?!

### ISSUE THREAD

**Issue by flemay** [VulcanJS/Vulcan#208]
Hi,

I'm new to meteor and I bought the book discover meteor (which is a good book so far)...and suddenly realised that the book has no section on testing (except testing a package). So I went to telescope repository and surprisingly no test folder!

Any reason of not doing it? Is testing a bad practice now? Am I missing something?

Thanks

**Comment by Alino** [comment]
is there widely accepted solution now? :)

**Comment by SachaG** [comment]
You can check out https://github.com/meteor-velocity/velocity
