### ISSUE TITLE
Need to flesh out form error messages

### ISSUE THREAD

**Issue by Neobii** [VulcanJS/Vulcan#2135]
Default error messages for form fields are missing such as `errors.minNumber`

**Comment by Apollinaire** [comment]
@Neobii thanks for submitting this. Some error messages are missing indeed, could you maybe list the ids, and what they mean? I'm guessing they are from SimpleSchema validation ? 
In that case, the only thing to do is add an i18n string  `{ 'errors.minNumber': 'The field "{label}" must be higher than {min}' }`. The file to change is here : https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-i18n-en-us/lib/en_US.js for the english version.
You can submit a PR if you want to!

**Comment by Neobii** [comment]
I'll list the ids, I think someone else should write the copy :).

**Comment by Apollinaire** [comment]
Adding my own contribution: 
```js
{
  'errors.expectedType': `Expected type {dataType} for field “{label}”, received "{value}” instead.`,
  'errors.required': `Field "{label}" is required`,
  'errors.maxString': `Field “{label}” is limited to {max} characters.`,
  'errors.regEx': `Field "{label}": wrong formatting`,
}
```

**Comment by Neobii** [comment]
Still need Spanish and French versions.

**Comment by SachaG** [comment]
Can we close this?

**Comment by Neobii** [comment]
we can, unless you want to wait until someone fills out Spanish and French versions.

**Comment by SachaG** [comment]
No, I think we'll worry about that when we set up an official process for translating.
