### ISSUE TITLE
Collection Creation Hooks

### ISSUE THREAD

**Issue by Neobii** [VulcanJS/Vulcan#2144]
Add hooks to creation collection like [Intl](https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-lib/lib/modules/collections.js#L155-L188).  Callbacks almost need to be ensured to run in order to ensure callbacks like intl run last.

**Comment by SachaG** [comment]
PR welcome!

**Comment by Neobii** [comment]
I will work on it this week, we just have to agree on callback name you mentioned `{collectionName}.collection.sync` but maybe this could be `{collectionName}.schema`.
