### ISSUE TITLE
Array SmartForm error messages don't have correct labels for nested items

### ISSUE THREAD

**Issue by Neobii** [VulcanJS/Vulcan#2159]
Because of schema flattening, `getLabel` cannot find the correct name of nested labels in the error messages resulting in errors that look like this `Field “memberInvites.0.firstName” is required.`.

**Comment by Neobii** [comment]
Should 
```javascript
Error.properties = {
id: "errors.required"
path: "memberInvites.0.firstName"
}
```
have a `path` of `firstName` because of the schema flattening?

**Comment by SachaG** [comment]
Hmm… maybe `getLabel` should only keep the last segment of any path then?

**Comment by Neobii** [comment]
So keep the error path how it is, but getLabel should use a regular expression to get the last segment of the path?

**Comment by SachaG** [comment]
You don't even need a regexp, you can just use `split` I think. But yes, I think that would be the easiest fix if I'm understanding the issue correctly.
