### ISSUE TITLE
meteor mobile app stop working after upgrade to 1.8

### ISSUE THREAD

**Issue by Nits7029** [VulcanJS/Vulcan#2164]
is it due to change in _meteor_runtime_config_ config?

**Comment by SachaG** [comment]
Can you provide more details?

**Comment by Nits7029** [comment]
i mean, app with an earlier version on the store that stops working after having upgraded my project to Meteor 1.8.

I think its mainly because the structure of meteor_runtime_config variable changed so old app is not getting hot code push and a request is not reaching to server

**Comment by eric-burel** [comment]
Closing as not directly related to Vulcan, you can find help on Meteor forum
