### ISSUE TITLE
Slack is down !

### ISSUE THREAD

**Issue by r-mach** [VulcanJS/Vulcan#2166]
Hello happy people,

I can not access the slack (vulcanjs.slack.com requires a specific mail domain, and slack.vulcanjs.org shows an Heroku error).

Can someone do something about it ? I would be happy to talk with you folks.

Regards

**Comment by r-mach** [comment]
It was the first time I tried so I couldn't tell.
It's working atm,
Thanks

**Comment by eric-burel** [comment]
@SachaG Still down :(

**Comment by SachaG** [comment]
I think it goes down sometimes for some reason, but then comes back up automatically. Don't have the time to look into it right now but maybe we should switch to now.sh instead of heroku.
