### ISSUE TITLE
Ability to dynamically set schema values based on prefilled props

### ISSUE THREAD

**Issue by Neobii** [VulcanJS/Vulcan#2167]
Any suggestions on how to do something like this?  Perhaps we can pass `prefilledProps` or even a new `formProps` to these schemas, also, on update, we probably should pass the document here as well so these have access to the values.

```
max(context) {
    //return totalNeeded from another collection to prevent users form submitting a larger number than the total needed.
    return Event.findOne({_id: context.eventId}).totalNeeded;
    }
```

**Comment by SachaG** [comment]
I feel like we're mixing two things here, because `prefilledProps` only concern forms while schemas are used on the back-end and things like `max` are used during validation completely independently of any form config.

In any case any `prefilledProps` value would be available to `max` as the current document being edited or inserted I think, so it should already be working?

**Comment by SachaG** [comment]
Sorry I'm not sure I understand, `prefilledProps` is related to forms while `min` and `max` validation is part of the schema and runs on the server. The server doesn't have a concept of a "form", it only knows about the data it receives?

**Comment by Neobii** [comment]
Ah well, I need to be able to dynamically set the min and max values.  Here's a use case:
I have a `makePayment` button that brings up a modal where you insert `payments` on an `event`.  `max` on the `payment` needs to be set dynamically depending on how much is paid using a denormalized field on the `event` that sums all current `payments`.  Give me a little guidance on how to accomplish this and you'll have a pr in return :).

**Comment by SachaG** [comment]
Well looking at the SimpleSchema docs about min/max, it says: 

> You can alternatively provide a function that takes no arguments and returns the appropriate minimum or maximum value. 

So it looks like you'd need to submit a PR to SimpleSchema to change that to a function that takes the current document as argument?

**Comment by Neobii** [comment]
I looked into this issue more
