### ISSUE TITLE
validationErrors undefined

### ISSUE THREAD

**Issue by Julien-Sytadelle** [VulcanJS/Vulcan#2185]
Hi, 

Since my last pull of devel this morning, I cannot create or update any object.
In vulcan-lib/server/mutators.js, l65, validationErrors are now undefined but were a list before the call to collection.create.validate callback.

If I force them back to an empty list, it makes an error later in mongo connector telling that  insert needs an argument.

I commented all my custom callbacks but does it  does nothing and my code works well with master branch.

**Comment by SachaG** [comment]
Yes, I introduced a bug, sorry about that. Just reverted my commit, it should work again now.

**Comment by Julien-Sytadelle** [comment]
No problem, that's how dev goes. I'll test tomorrow morning then close the issue. 

Le 22 janv. 2019 à 01:55, à 01:55, Sacha Greif <notifications@github.com> a écrit:
