### ISSUE TITLE
[apollo2] User appears logged out after reloading page

### ISSUE THREAD

**Issue by SachaG** [VulcanJS/Vulcan#2188]
Form @eric-burel:

in `context.js` I got this code
```
const getAuthToken = req => {
  return req.headers.authorization || new Cookies(req.cookies).get('meteor_login_token');
};
```

the cookie does not seem to be set as soon as you authenticate, but only after the next page reload
to reproduce :

1) empty cache
2) login (eg in example-forms of the Starter). The cookie `meteor_login_token` is not set
3) reload page. You appear as logged out. During this reload, the cookie `meteor_login_token` is set.
4) reload again. Now you seem to be logged back in, because the cookie is correctly set. (edited) 

I think the issue is that the cookie `meteor_login_token` is somehow stored too late, hence this behaviour. It should already work during the first reload. Note that you are actually never logged out, it's just SSR that fails to retrieve the user and thus render the page is if you were logged out. (edited) 
see the `auth.js`, it is called on `Meteor.start` but should also be called after login I think
I'll need help on this, I am not really familiar with the auth system, I guess the solution is just running the `auth.js` `initToken` function in a callback triggered after login.

**Comment by eric-burel** [comment]
Fixed it was a small regression, sorry. When you save `Meteor.loginToken` into the localStorage, it is now automatically added to the cookies too.
