### ISSUE TITLE
Material UI

### ISSUE THREAD

**Issue by SachaG** [VulcanJS/Vulcan#2190]
Let's discuss adding an official Material UI integration to Vulcan Core. Feel free to add a 👍 if you'd like to see this happen.

**Comment by SachaG** [comment]
@eric-burel let's start thinking about bringing the material UI package into core. I don't really want to maintain it myself, but I do think it being in core will help more people use it and contribute to it?

**Comment by eric-burel** [comment]
Yep that's a good idea. I will keep using it, and I will work on the app developed by @Apollinaire which uses Material UI too.

Right now my biggest question is: what about custom components?

When writing such a package, it's tempting to develop additional stuffs. @ErikDakoda already provides bonus in `vulcan:material-ui`, I wrote [`vulcan:more-material-ui`](https://github.com/lbke/vulcan-more-material-ui) that provides a simple layout, @ochicf published [`vulcan:material-ui-layouts`](https://github.com/OrigenStudio/vulcan-material-ui-layout)...

So, I guess we should only keep the core part of `vulcan:material-ui`, and provides the "bonuses" and additional components as one or more independant packages.

**Comment by SachaG** [comment]
Yeah that makes sense. Also for "non-core" components people also have the option of just using Material UI directly, which might make more sense. After all the main reason to have a Meteor package wrapper was inter-library compatibility.

**Comment by eric-burel** [comment]
Also I think we need some kind of `example-ui` package that showcases all the UI components with different states (empty datatable, datatable with value, form in edition, empty form, error form, and so on), at least for development purposes, it would be our own Storybook. I think I'll start there because it will be necessary for other packages too.

**Comment by SachaG** [comment]
Yeah good idea. Or, this could be part of the new docs package that's integrated to Vulcan? Or the current debug package?

**Comment by Apollinaire** [comment]
I would make it its own package and maybe integrate it in the debug package. To keep things separated. For now, a Storybook of the Core + necesary UI components would be enough. Maybe a recap page showing the whole list of necesary components, and a way to tell if they are registered or missing.

A great feature (later) would be to be able to "write your own stories". Or register them. That will probably mean creating a debug-only package forked in the repo.

**Comment by eric-burel** [comment]
Ongoing work:
- [ ] Copy pasting Erik Dakoda implementation into the core
- [ ] Upgrading to apollo 2
- [ ] Applying Apollinaire/Live for Good fixes
- [ ] Applying my own / Awesome Vulcan fixes
- [ ] Removing bonus components?
- [ ] Creating a left layout component

**Comment by Apollinaire** [comment]
If you update material-ui above 3.1 I think you will need to look into the ssr because they changed some things with style injection if I remember correctly.

**Comment by eric-burel** [comment]
Closing as MUI is now in the core and up to date. Components still need improvements to improve our UI swapping abilities, there are still some code redudancies.
