### ISSUE TITLE
Dataloader should be initialized for each request

### ISSUE THREAD

**Issue by SachaG** [VulcanJS/Vulcan#2195]
Currently it's only initialized when the server starts, which leads to stale data:

https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-lib/lib/server/apollo-server/context.js#L38-L46

**Comment by eric-burel** [comment]
My bad, this should be fixed on the latest commit. I am not sure how to test this, can you confirm it's ok?

**Comment by SachaG** [comment]
Seems to work, thanks!
