### ISSUE TITLE
Int/Floats should be cast to numbers when form input value is changed

### ISSUE THREAD

**Issue by SachaG** [VulcanJS/Vulcan#2197]
With the new version of Apollo, it seems like `"2"` is no longer accepted for a `Float` field, it has to be `2`. For now I've fixed it by casting any string that is a valid number to a number: 

https://github.com/VulcanJS/Vulcan/commit/0d69d81301d0666e1bbbf06d55d50c311787ec42

But it might be better to do this only for fields that are actual numbers?

**Comment by Neobii** [comment]
Currently, this [commit](https://github.com/VulcanJS/Vulcan/commit/0d69d81301d0666e1bbbf06d55d50c311787ec42) breaks the `example-simple` example.  If you put in 1992, it automatically typecasts it to a number although in the schema, it specified year as a string.

**Comment by Apollinaire** [comment]
> Currently, this [commit](https://github.com/VulcanJS/Vulcan/commit/0d69d81301d0666e1bbbf06d55d50c311787ec42) breaks the `example-simple` example. If you put in 1992, it automatically typecasts it to a number although in the schema, it specified year as a string and throws a graphql error.

Hence the `TODO : cast based on actual schema field type`
