### ISSUE TITLE
Admin package won't add users to new groups

### ISSUE THREAD

**Issue by yairtal** [VulcanJS/Vulcan#2199]
Reproduce:
Add Admin package to you VulcanJS app,
Create a new premissions group,
Edit one of the users to add him/her to a group
Click on the checkbox to add to the new group -
It won't become checked, stays on false, can't add users to groups.

**Comment by alirezamirsepassi** [comment]
Same problem here, no error appears!

**Comment by SachaG** [comment]
This was an issue with the checkboxgroup component, I've fixed it on `devel` and `devel-apollo1`, and I'm now publishing a fix in version 1.12.17.
