### ISSUE TITLE
Smart Forms error

### ISSUE THREAD

**Issue by alirezamirsepassi** [VulcanJS/Vulcan#2201]
Hi, I'm trying to use smartform component for my admin forms, after I push the submit button this error appears:

`// graphQL Error
Form.jsx:911 TypeError: this.form.reset is not a function
   at SmartForm.mutationSuccessCallback (Form.jsx:891)
   at SmartForm.newMutationSuccessCallback.result (Form.jsx:874)
   at meteor.js?hash=33066830ab46d87e2b249d2780805545e40ce9ba:1223`

**Comment by SachaG** [comment]
Yes this is a known issue, we'll have a fix out soon. I don't think it prevents the form submission though?

**Comment by alirezamirsepassi** [comment]
No, the form is submitted and saved successfully. Thanks
