### ISSUE TITLE
Deploy Vulcanojs App to AWS serverless cloud

### ISSUE THREAD

**Issue by TomFreudenberg** [VulcanJS/Vulcan#2202]
Hello

I am not sure if this is the rigth place to ask but try once.

Coming from article about serverless React + GraphQL app

https://dashbird.io/blog/serverless-react-graphql/

I am wondering if someone has experience in deploying a Vulcano app to AWS cloud.

Thanks for sharing some feedback

Tom

**Comment by SachaG** [comment]
If you mean deploying to EC2 you can use http://meteor-up.com/

**Comment by shierro** [comment]
@SachaG i think what Tom mean to ask, is if someone have been able to successfully start a vulcanjs app in AWS lambda, now that websocket has been supported by API Gateway last year November

**Comment by SachaG** [comment]
Oh right, I honestly don't know enough about serverless apps to answer definitively but that approach seems pretty incompatible with Vulcan? I guess the easiest way to find out would be to know if Meteor apps in general can run on it, if yes than Vulcan can as well. I'll close this for now as I don't think it's Vulcan-specific.

**Comment by shierro** [comment]
Yeah true, this is not vulcan specific 😄
[this](https://github.com/meteor/meteor-feature-requests/issues/284]) might be the right place to continue this conversation @TomFreudenberg

**Comment by TomFreudenberg** [comment]
Hi @SachaG @shierro 

thanks for your feedback even that this is not VulcanJS specifc.

Theo was right I am looking for deployment in AWS Lambda etc.

If I am able to get more senseful information, I will share here as well.

Have a nice weekend
Tom
