### ISSUE TITLE
example-instagram upload image vulcan-forms-upload

### ISSUE THREAD

**Issue by JimmyRowland** [VulcanJS/Vulcan#2208]
I am trying to upload photos to cloudinary in the example-Instagram app

I tried type String and Array, not none of them works
```
imageUrl: {
   label: 'Image URL',
   type: String,
   canRead: ['guests'],
   canCreate: ['members'],
   canUpdate: ['members'],
   input: FormsUpload, // use the FormsUpload form component
   options: {
     preset: 'mypreset'
   },
 },
```
error message for type Array:
Error: "imageUrl" is Array type but the schema does not include a "imageUrl.$" definition for the array items"
How do I fix this?
Thanks

**Comment by valgalin** [comment]
Please try this one, like this:

`imageUrl: {
   label: 'Image URL',
   type: String,
   canRead: ['guests'],
   canCreate: ['members'],
   canUpdate: ['members'],
   input: FormsUpload, // use the FormsUpload form component
   options: {
     preset: 'mypreset'
   },
 },
{
    fieldName: 'imageUrl.$',
    fieldSchema: {
      type: String
    }
 }`

**Comment by SachaG** [comment]
@valgalin thanks for the fix!

I'll close this since there is already a more appropriate issue on the starter repo: https://github.com/VulcanJS/Vulcan-Starter/issues/116
