### ISSUE TITLE
throwError is not defined

### ISSUE THREAD

**Issue by vale981** [VulcanJS/Vulcan#2224]
Throw error is defined in `/packages/vulcan-lib/lib/server/errors.js` but importet by `/packages/vulcan-lib/lib/modules/utils.js` from `/packages/vulcan-lib/lib/modules/errors.js`.

I am opening this as issue for I don't know what to make of it. The only solution i can think of is to shift all code using throwError to the server, or to rewrite `throwError` to work on the client.

**Comment by vale981** [comment]
Moving `Utils.performCheck` to the server code does the trick. Should be stuff for a PR.

**Comment by SachaG** [comment]
Oh right, yeah we can move `performCheck` to the server.

**Comment by vale981** [comment]
Is this a regression?

**Comment by SachaG** [comment]
Not really a regression, `throwError` shouldn't be used on the client anyway since it throws a GraphQL error.

**Comment by vale981** [comment]
It was used by the server. But it got a hickup, because the import didn't exist!
