### ISSUE TITLE
Form Error doesn't show Form Field that has error

### ISSUE THREAD

**Issue by darwis059** [VulcanJS/Vulcan#2225]
If one of required field is null while submitting form, Form Error only show this message `Network error: Cannot read property 'data' of null`

graphql response:
`{
  "errors": [
    {
      "message": "Cannot read property 'data' of null",
      "locations": [
        "TypeError: Cannot read property 'data' of null\n    at registerWatchedMutation (http://localhost:3000/packages/vulcan_core.js?hash=701f37454a591447e8a6b44c5d21bf3d324a8981:402:61)\n    at WatchedMutationLink.value [as updateQueryAfterMutation] (http://localhost:3000/packages/modules.js?hash=46f7a6d2a5862753d1af6eeba7f441f283f5fee2:120212:27)\n    at http://localhost:3000/packages/modules.js?hash=46f7a6d2a5862753d1af6eeba7f441f283f5fee2:120275:18\n    at Array.forEach (<anonymous>)\n    at http://localhost:3000/packages/modules.js?hash=46f7a6d2a5862753d1af6eeba7f441f283f5fee2:120268:33\n    at Object.next (http://localhost:3000/packages/modules.js?hash=46f7a6d2a5862753d1af6eeba7f441f283f5fee2:74950:23)\n    at notifySubscription (http://localhost:3000/packages/modules.js?hash=46f7a6d2a5862753d1af6eeba7f441f283f5fee2:74772:18)\n    at onNotify (http://localhost:3000/packages/modules.js?hash=46f7a6d2a5862753d1af6eeba7f441f283f5fee2:74807:3)\n    at SubscriptionObserver.next (http://localhost:3000/packages/modules.js?hash=46f7a6d2a5862753d1af6eeba7f441f283f5fee2:74861:7)\n    at Object.next (http://localhost:3000/packages/modules.js?hash=46f7a6d2a5862753d1af6eeba7f441f283f5fee2:123187:34)"
      ]
    }
  ]
}`

**Comment by darwis059** [comment]
on latest devel

**Comment by enzolutions** [comment]
Could you share your schema?

**Comment by darwis059** [comment]
```
import { generateIdResolverSingle } from '../../modules/utils/schemaUtils'
import { Utils, getSetting, registerSetting, getCollection } from 'meteor/vulcan:core';

const schema = {
    // default properties
  
    _id: {
      type: String,
      optional: true,
      canRead: ['guests'],
    },
    createdAt: {
      type: Date,
      optional: true,
      canRead: ['guests'],
      onCreate: () => {
        return new Date();
      },
    },
    userId: {
        type: String,
        optional: true,
        control: 'select',
        viewableBy: ['guests'],
        insertableBy: ['members'],
        hidden: true,
        resolveAs: {
          fieldName: 'user',
          type: 'User',
          resolver: generateIdResolverSingle(
            {collectionName: 'Users', fieldName: 'userId'}
          ),
          addOriginalField: true
        },
      },
  
    // custom properties
  
    contractName: {
      label: 'Name',
      type: String,
      // optional: true,
      canRead: ['members'],
      canCreate: ['members'],
      canUpdate: ['members'],
    },
    contractNumber: {
      label: 'Number',
      type: String,
      // optional: true,
      canRead: ['members'],
      canCreate: ['members'],
      canUpdate: ['members'],
    },
    contractValue: {
      label: 'Value',
      type: Number,
      // optional: true,
      canRead: ['members'],
      canCreate: ['members'],
      canUpdate: ['members'],
      form: {
        defaultValue: 0,
        min: 0,
        formatter: value => `${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ','),
        parser: value => `${value}`.replace(/\$\s?|(,*)/g, ''),
        style: {
          width: '150px'
        }
      }
    },
    contractDate: {
      label: 'Signed Date,
      type: Date,
      // optional: true,
      canRead: ['members'],
      canCreate: ['members'],
      canUpdate: ['members'],
    },
  };
  
  export default schema;
```

**Comment by enzolutions** [comment]
Hi @darwis059 

Last week I have an issue with Datatable a field declared as number  + optional. because in my database I have some imported data from CSV that create documents with an empty field ''.

So my solution was iterate in my document and remove those fields in the specific fields using the following snippet.

```
db.getCollection('suburbs').update(
	{communityCode: ''},
	{
		$unset: {
			"communityCode": 1,
		}
	},
	{ 
		upsert: true,
		multi:true
	}
);
```
What I did to found the issues in my schema + data storage, was to comment out the fields definitions and enable one by one until I found the ones with the issue.

I hope my experience helps you a little bit.

**Comment by SachaG** [comment]
Weird, I just tried submitting a document with empty fields and it worked fine. Also searching the codebase I can't find a trace of `registerWatchedMutation` actually being used, so I don't know how it could end up throwing an error?

**Comment by darwis059** [comment]
its happen on every type of Field that required and empty while form submitted. on server console detail of required Field error logged. 
on client side, the mutationErrorCallback called with document(DOM, not new document from form) passed as document variable <- is this normal?

**Comment by darwis059** [comment]
i tried using vulcan-starter example-simple. it got same error

**Comment by eric-burel** [comment]
Hi guys, should be fixed now on devel.
This was due to a failure on watchedMutations. When you create/update/delete, Apollo will detect it and update lists automatically, before the next polling. So you could have this bug on pages that contained both a form and a list (eg when editing from a datatable).
The errors were there, but since an error was thrown before they were sent it failed.

**Comment by eric-burel** [comment]
I am still not 100% sure about the internals of watchedMutations, basically they seem to be called if you also have a list on the page that calls the mutationResolver.
