### ISSUE TITLE
Example for file download

### ISSUE THREAD

**Issue by bseng** [VulcanJS/Vulcan#2231]
Hi,

Where can I find an example for creating a button to download a file generated from the server side?

Thanks

**Comment by darwis059** [comment]
you can create server side route for that using picker or express. you can see example here:
picker: Vulcan-Starter/packages/example-forum/lib/server/posts/out.js
express: Vulcan/packages/vulcan-payments/lib/server/integrations/stripe.js
after that, you just create Button/Link to that route.

**Comment by bseng** [comment]
Thanks for the pointer. I end up using express.
