### ISSUE TITLE
example-movies project error: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by luccascorrea** [VulcanJS/Vulcan#2237]
Hi,

I am new to Vulcan and so I was following along the Movies example and I noticed that there is an error happening every time a movie is deleted. The error is:

    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
        at endDebugMutator (packages/vulcan:lib/lib/server/mutators.js:582:10)
        at Promise.asyncApply (packages/vulcan:lib/lib/server/mutators.js:560:3)
        at /Users/luccascorrea/.meteor/packages/promise/.0.11.2.hy69oz.ytuae++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40

It's quite simple to reproduce, you only need to run the example-movies package, insert a movie and then delete it. I am using Vulcan version 1.12.17.

I had a look at the source code and it seems like an easy fix. Either on this line here: https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-lib/lib/server/mutators.js#L560 you should pass an empty object as the third parameter to the **endDebugMutator** function or on this line here: https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-lib/lib/server/mutators.js#L582 there should be a null check for the parameter **properties** before the iteration.

I hope that helps.

PS: I am still learning as I go but I can already see how great Vulcan is! Congrats!

Luccas

**Comment by SachaG** [comment]
Thanks for the report! I applied your fix on the `devel` branch, it should be merged soon.
