### ISSUE TITLE
Error with Date fields with Schema using Material UI Form

### ISSUE THREAD

**Issue by enzolutions** [VulcanJS/Vulcan#2251]
Hey folks,

I have been testing the latest implementation of Material UI at @devel branch, and now I am facing some issues with fields of type Date.

Visually the fields are rendered and using a date picker to change the date, but after hit submit the changes are not stored.

I found that is the field is defined as `String` and force the input to `date` visually and the update works as you can see in the following definition.

```
{
  fieldName: 'startDate',
  fieldSchema: {
    type: String,
    optional: true,
    canRead: ['members', 'admins'],
    canUpdate: ['members'],
    canCreate: ['members'],
    input: 'date',
  },
},
```

That workaround "solve" the issue, but I would really prefer to stay with Date type. I am still debugging to try to find the issue.

Any guidance and/or suggestion are welcome.

**Comment by eric-burel** [comment]
I did not have time to investigate but the error message seems to say that there is some kind of mismatch between the expected type and the actual value.

First you should check what the value looks like client side (in the SmartForm props) after you modified the date. Then what is expected server side (not sure where to look at though, maybe in `graphql.js`?).

**Comment by eric-burel** [comment]
Fixed on devel, thanks for your PR!
