### ISSUE TITLE
Create a "password" control

### ISSUE THREAD

**Issue by eric-burel** [VulcanJS/Vulcan#2257]
When creating a user outside of Meteor Accounts, we could need to handle passwords in the SmartForm. We can set the input type to "password", but this does not allow to create a nicer default input for all passwords. I think passwords deserves to be handled like date, numbers and so on.

That would mean adding a "password" control in `FormComponent.jsx`.

**Comment by eric-burel** [comment]
@juliensl could be an interesting issue for you
@SachaG would you be ok with this feature? Not an emergency at all of course

**Comment by SachaG** [comment]
Yes that seems like a good idea.

**Comment by eric-burel** [comment]
Closed by #2472
