### ISSUE TITLE
Move to Jest

### ISSUE THREAD

**Issue by eric-burel** [VulcanJS/Vulcan#2270]
Hi,

Just to open a discussion about improving testing.

Right now, I only managed to setup Mocha to run with Meteor. I struggle to mock Meteor packages, mainly Mongo.

Jest is far more powerful in terms of performance, features, mocking and so on. It does not integrate directly with Meteor though.

This article describes however how to use Jest by mocking Meteor, which is actually quite easy :
https://www.okgrow.com/posts/real-world-unit-testing-with-meteor-and-jest

To work with Vulcan, we would additionally need to rely on specific Webpack loader, exactly the same way we try to do with Storybook. Vulcan code would be fetched from the local install.

Drawbacks:
- no actual integration testing, Meteor is mocked
- need for a 2-repo install, same as for Storybook. However I'd like to use it only for testing Vulcan itself in the first place, so it's ok.
- need to improve the Meteor mock, eg I don't know how to handle Meteor.startup yet. Jest should be configurable enough to allow this though
- not sure what to do about Meteor.isClient, Meteor.isServer, and client/server code more broadly, so basically I am not 100% sure that this is actually doable. Maybe with 2 different configs for client side testing and server side testing, each producing a different build?

Advantages:
- get rid of Mocha
- use Jest
- tests are not pure hell to write anymore
- no need to run/build Meteor to test Vulcan

**Comment by cvolant** [comment]
Hi,
I am currently studying different options to decide which framework I should adopt.
Vulcan sounds really nice: if it supported Jest and PWA, I would go for it.

**Comment by eric-burel** [comment]
Vulcan is an active project so even if it may sometimes takes time, it's perpetually improving with new features and usage of the latest libs.

Concerning Jest it's a bit difficult due to the need to build a Meteor app with Webpack. But we managed to do it with Storybook (still under experiment/cleanup) so I am sure it will be ok.

Concerning PWAs, honestly people makes a huge deal about them but technically they are not complex features, basically the hardest part is caching data when offline. Thus I don't think this is the most relevant criteria when choosing a framework. You'll find example of Meteor+Apollo PWA that would adapt in Vulcan.

**Comment by SachaG** [comment]
Sounds good to me!

> not sure what to do about Meteor.isClient, Meteor.isServer, and client/server code more broadly, so basically I am not 100% sure that this is actually doable. Maybe with 2 different configs for client side testing and server side testing, each producing a different build?

I think avoiding Meteor.isClient and Meteor.isServer is a good idea anyway. But I'm not really familiar enough with Jest to know more…

**Comment by jimrandomh** [comment]
What would be the implications for Vulcan-using projects which already have a significant number of unit tests?

**Comment by eric-burel** [comment]
I think in any case we would need both. So I think Jest tests would have to be isolated in a `jest` folder, a bit like Storybook, they won't be able to live anywhere in the code. This folder would be ignored by Meteor.
So "meteor test" would run Mocha as usual, and "jest" would run jest tests. We could maintain a legacy behaviour + some specific tests with Mocha, and write new tests with Jest.

**Comment by eric-burel** [comment]
Gave a first shot at this:

- We need Babel processors instead of the Webpack loader we made for Storybook. This is not a huge deal, we simply need to transform "vulcan-loader" and "scrap-meteor-loader" in a Babel function
- There is also this package that could fit: https://www.npmjs.com/package/babel-plugin-replace-imports. It's basically this, it allow to replace import so you can scrap out "meteor" imports and point "meteor/vulcan:*" to the place you want;
- BUT... you'll be in trouble with isomorphism. That probably means having to differentiate Jest client and server tests.

**Comment by juliensl** [comment]
This is a nice move ! I can't wait to see the result :D

**Comment by eric-burel** [comment]
I am almost there, with one slight limitation: it work only if you install node_modules with `yarn`. I suspect this issue is related to https://github.com/VulcanJS/Vulcan/issues/2680, basically Meteor is implying an older version of Babel/core-js for some reason.

**Comment by eric-burel** [comment]
It seems that we have to avoid to use "Meteor" and "Mongo" as global variables in Vulcan (which are bad practicies anyway), because it doesn't seem doable to define a global mock from Jest in this case (jest globals can't be functions so they are not sufficient), because the packages are imported and do not belong to users code.
I've raised the question [on this SO question related to Meteor and Jest](https://stackoverflow.com/questions/51566816/what-is-the-best-way-to-mock-window-sessionstorage-in-jest/58143066?noredirect=1#comment116569789_58143066)

**Comment by eric-burel** [comment]
Ok I did not succeed with babel-plugin-transform-globals, somehow it isn't applied to the Vulcan install. Best course of action is to remove global "Meteor" and "Mongo" variables from Vulcan and instead import them from "meteor/meteor" explicitely (which is a better practice anyway)

**Comment by eric-burel** [comment]
Summary of what I've tempted so far:

**Comment by haveaguess** [comment]
Hi @eric-burel , thanks for this attempt, and sharing your progress. I was just about to start on this journey when I saw your comment in stackoverflow and this backlink. Figured Id see how you were getting on. 

Just to understand, is this something we could do with a project that is simpler than what Vulcan is trying to do or is a dead-end even for simpler Meteor apps like ours? 

Like you, I'd love to get the benefits of Jest that the author you referred to, seemed to, but don't want to lose time if it's a dead end.

**Comment by eric-burel** [comment]
Hi ! The problem will be even worse in a normal Meteor application, because the difficulty lies in making Meteor core features available with a Webpack build (or to mock them). It's not really a dead-end, this approach has been successful at least for client-side build, but more a lot of trouble for not much added value if you want also Jest for server-side test.

So it's definitely better to use Mocha solution, until Jest is supported by Meteor (if it ever happens). That means running Jest in Meteor, instead of trying to run Meteor code in Jest+Webpack.
