### ISSUE TITLE
After callbacks are run too late in create mutator

### ISSUE THREAD

**Issue by eric-burel** [VulcanJS/Vulcan#2271]
Line 197 of mutators.js, this code get the document from the db before returning the mutation:
```
  // note: query for document to get fresh document with collection-hooks effects applied
  document = await Connectors.get(collection, document._id);
```
It is called after `after` callbacks are called, thus overriding their result. It only affects the `create` mutator, not the update mutator. 

I've written a test that is not passed currently but (I hope) should pass after this is fixed. I can handle the fix, I just wanted to confirm my understanding before.

**Comment by SachaG** [comment]
Yeah I guess you're right. Thanks for finding and fixing this issue!
