### ISSUE TITLE
Can't replace modalTrigger (material-ui)

### ISSUE THREAD

**Issue by harold20** [VulcanJS/Vulcan#2280]
Hello people.

I did a custom component to replace the default modalTrigger like the doc said. To add extra functionality to close modal. but it didn't replace it. For test it, I copied the same file(ModalTrigger) and replace it with extra custom code  to know if it was replaced, but I didn't work

There is no errors. when I replaced the component
`replaceComponent('ModalTrigger', CustomModalTrigger, [withStyles, styles]);
`

My replacement is to add a function that is called when the modal is closed. I accept any suggestion

Regards

**Comment by ErikDakoda** [comment]
This is often a load order issue. In package.js of the package where you have your `CustomModalTrigger` do you have `api.use(['vulcan:ui-material']);`?

**Comment by harold20** [comment]
Yes @ErikDakoda, It seems to be working now. Of course I have updated Vulcan with the latest changes.
 I'm going to close this.
