### ISSUE TITLE
Resolver can’t return an array  

### ISSUE THREAD

**Issue by harold20** [VulcanJS/Vulcan#2290]
Hello people.
I am trying to create a  resolver for new field that return an array or object but I got this error.

`Error: Unknown type "Array". at assertValidSDL(/Users/projectName/node_modules/graphql/validation/validate.js:89:11)`

and this is my field in the schema

```
 file: {
    label: 'Files',
    type: Array,
    optional: true,
    canRead: ['members','admins'],
    canCreate: ['members','admins'],
    canUpdate: ['members','admins'],
    control: 'Upload',
    resolveAs: {
      fieldName: 'imageUrl',
      type: 'Array',
      resolver: async (candidates) => {
        if (!candidates.file) return null;
        const resolve = candidates.file.map(async fileId => {
          const file =  await CandidateLogFiles.findOne(fileId);
          return `${file.name};${file.link()}`;
        });
        const fileList = await Promise.all(resolve);
        return fileList;
      },
      addOriginalField: true
    },
```

I am not sure if this is possible to do or if is an issue of Vulcan.

Any comment is grateful :)

**Comment by SachaG** [comment]
`Array` is not a valid GraphQL type. It would have to be something like `[File]` if you've defined a `File` type, or else `[JSON]` if you want to use the pre-existing JSON type.

**Comment by harold20** [comment]
Thank @SachaG for the answer. I understood, I'll try see that option.
