### ISSUE TITLE
Admin panel UI sometimes deletes all users database...

### ISSUE THREAD

**Issue by yairtal** [VulcanJS/Vulcan#2335]
Version: 1.13.0, latest 'devel' branch

Reproduce:

Go to Admin Panel
Delete a user
Before the refresh, delete the same user or another user
Repeat a few times

**Your entire users database is completely deleted**

**Comment by eric-burel** [comment]
I've managed to repro. Still don't know what the issue but it smells like deletion with a badly defined condition. There's a race condition somewhere.

**Comment by eric-burel** [comment]
Fixed and unit tested for default_mutations and users related mutation.
