### ISSUE TITLE
Mismatching className when using Material UI withStyles

### ISSUE THREAD

**Issue by eric-burel** [VulcanJS/Vulcan#2338]
See https://github.com/mui-org/material-ui/issues/10522
Sometimes the class names of material UI component are not matching during SSR (for buttons, inputs etc.), needs investigation.

**Comment by ErikDakoda** [comment]
Hi Eric,

Oh, if could recoup the days and sweat and tears I have spent on trying to resolve this issue!!! LOL

I eventually gave up, and now wrap my whole app in <NoSsr/> - not ideal. I think the solution is in how SSR is rendered and how it's hydrated on the client - something that I am completely unfamiliar with.

**Comment by eric-burel** [comment]
Yeah I'll take a look asap I just wanted to document this. The code is fairly short but dense so hard to debug, for the moment the first step is to have a minimal repro. I can also happen when HOCs are not used correctly.

**Comment by eric-burel** [comment]
Should be fixed when https://github.com/VulcanJS/Vulcan/pull/2352 is merged
