### ISSUE TITLE
Update react-dropzone to 10.1.5 (Upload component)

### ISSUE THREAD

**Issue by lc3t35** [VulcanJS/Vulcan#2347]
current version is "react-dropzone": "^8.0.3",

this generates the warning

> Warning: The prop `disableClick` of `t` is deprecated. Use onClick={evt => evt.preventDefault()} instead. This prop will be removed in the next major version.

As seen https://github.com/react-dropzone/react-dropzone/issues/831, you should update to 10.1.5.
I did .. no more warning

**Comment by eric-burel** [comment]
Done thank you!
