### ISSUE TITLE
New Permissions API

### ISSUE THREAD

**Issue by SachaG** [VulcanJS/Vulcan#2390]
Proposal:

```
const Movies = createCollection({
  collectionName: 'Movies',

  typeName: 'Movie',

  schema,

  resolvers: getDefaultResolvers({ typeName: 'Movie' }),

  mutations: getDefaultMutations({ typeName: 'Movie' }),

  permissions: {
    read: ['members'],
    create: ['members'],
    update: ['owners', 'admins'],
    delete: ['owners', 'admins'],
  },
});
```

To-do: 

- [ ] Create new dynamic `owners` group that automatically triggers a check on the document's `userId` property.
- [ ] Handle new `permissions` option on `createCollection` that accepts four properties that each take either an array of groups or a function.

**Comment by justinr1234** [comment]
@SachaG might be a good time to also think about Organizations here. `orgMembers` as another option.

**Comment by SachaG** [comment]
@justinr1234 can you expand on that? What exactly do you mean?

**Comment by justinr1234** [comment]
Meaning not just role-based access, but also access determined by group membership.

For instance, “people who are members of Organization A who are also of the role orgAdmin”

@SachaG

**Comment by eric-burel** [comment]
That's the kind of thing you may not want directly into the core, but that should be doable easily. Does `canRead` accept an async function currently for example?

The problem with Orgs is that it's a many-to-many relationship, potentially with hierarchy. Say a group of companies. Managing this kind of advanced concepts in the core is not sustainable given the work load with have just with purely technical issues.

**Comment by justinr1234** [comment]
@eric-burel I think it’s worth it as orgs is a common feature

**Comment by ErikDakoda** [comment]
I have written a "companies" package on top of Vulcan that implements organizations. Currently modifies the meaning of `members`, so you can read and edit docs created by you or by other members of the same company. It also supports inviting members to join your company. Yeah, I think this is a pretty common feature.

**Comment by justinr1234** [comment]
It’s common but also poorly implemented everywhere I’ve seen in other frameworks and systems

**Comment by eric-burel** [comment]
This feature is in production in v1.14!
