### ISSUE TITLE
withMulti does not update locally when using a view with selectors

### ISSUE THREAD

**Issue by 143mailliw** [VulcanJS/Vulcan#2395]
When terms are set to use a view with selectors in the parent component, a component with a withMulti does not update locally, instead only updating on a server poll.

This is reproduced in this repository: https://github.com/143mailliw/Vulcan-withMulti-bug (npm install, npm start). The package is named `withMulti-repro`.

**Comment by eric-burel** [comment]
This is because you have a custom view, if you remove it it works. I will investigate why it doesn't add the document in this case and whether it is expected or not (we can't do much filtering on the client).

**Comment by eric-burel** [comment]
Fixed on devel + added non regression test for this case, thanks!
