### ISSUE TITLE
Semantized classNames

### ISSUE THREAD

**Issue by eric-burel** [VulcanJS/Vulcan#2423]
As stated by @juliensl , autogenerated HTML code lacks some semantic classNames, in order to write stable selector.

This is especially necessary for end-to-end testing, eg with Cypress (that we could add to the Starter as the default testing framework btw).

To solve this we would need to add className based on the schema field names and collection/type name on Datatable, Smartform and Card. Those classes only needs to be added to key parent elements (a form group, and input wrapper etc.).

**Comment by loustak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/zTjBSL88/1-test)
