### ISSUE TITLE
update.all does not let user to edit own documents

### ISSUE THREAD

**Issue by EloyID** [VulcanJS/Vulcan#2446]
In default_mutations.js 

```
        return Users.owns(user, document)
          ? Users.canDo(user, [
              `${typeName.toLowerCase()}.update.own`,
              `${collectionName.toLowerCase()}.edit.own`,
            ])
          : Users.canDo(user, [
              `${typeName.toLowerCase()}.update.all`,
              `${collectionName.toLowerCase()}.edit.all`,
            ]);

```
If user owns a document && user can update.all => user cannot edit his own document.
In my opinion, the user should be able to edit his too. I will send a PR soon :)

**Comment by eric-burel** [comment]
You can automatically close your issues in PR by writing "Closes #2446" in the PR message for example.
Thanks for fixing this!
