### ISSUE TITLE
Vulcan Components component does not allow refs to be pased

### ISSUE THREAD

**Issue by 143mailliw** [VulcanJS/Vulcan#2449]
Using Vulcan's Component object does not allow refs to be passed, as it is a function component with no forwardRef. This means that there is no way for a function in a child component to be run (like click()).

**Comment by eric-burel** [comment]
Hi, could you please elaborate a bit which component would need a forward ref? You think about inputs, button etc.?

**Comment by 143mailliw** [comment]
A component registered with registerComponent() and then used with
<Component.ComponentName/> cannot have a ref passed to it. I need this to
make a button that can be clicked by another element.

**Comment by eric-burel** [comment]
Did you try to add React.forwardRef to your component before registering it?

**Comment by eric-burel** [comment]
In addition we now recommend to avoid registerComponent if you don't have a good use case (eg this component must be replaceable by another package for theming). You don't need it anymore for delayed HOCs (withMulti etc.).

**Comment by 143mailliw** [comment]
> 
> 
> Did you try to add React.forwardRef to your component before registering it?

Yes.

**Comment by 143mailliw** [comment]
It also seems like this would need to be done with the HoCs too.

**Comment by yannick-mayeur** [comment]
Hi I am looking into your issue and I managed to do an example with two components the parent one passing a ref to its child. I did it like this:

Parent: 
```javascript
import React from 'react';
import { Components, registerComponent } from 'meteor/vulcan:core';

class TestComponent extends React.Component {
  constructor(props) {
    super(props);
    this.textInput = React.createRef();
    this.focusTextInput = this.focusTextInput.bind(this);
  }

  focusTextInput() {
    this.textInput.current.focus();
  }

  render() {
    return (
      <div>
        <Components.TestChild ref={this.textInput} />
        <input
          type="button"
          value="Focus the text input in TestChild"
          onClick={this.focusTextInput}
        />
      </div>
    );
  }
}

registerComponent({ name: 'TestComponent', component: TestComponent });
```

Child :
```javascript
import React from 'react';
import { registerComponent } from 'meteor/vulcan:core';

const TestChild = React.forwardRef((props, ref) => {
  console.log(props)
  return (
    <input
      type="text"
      ref={ref} />
  )
});

registerComponent({ name: 'TestChild', component: TestChild });
```

Did I miss something ?

**Comment by 143mailliw** [comment]
Huh. I'll have to look into it.

**Comment by 143mailliw** [comment]
Seems to work, i'll try to find the actual cause of this issue ASAP.

**Comment by eric-burel** [comment]
Thanks for your help @yannick-mayeur. Maybe you could create a story to demonstrate this?

**Comment by yannick-mayeur** [comment]
Yes I am on it.

**Comment by yannick-mayeur** [comment]
Can I use register component when working in a story ?

**Comment by eric-burel** [comment]
Yes I think. The call to registerComponent should probably be at the root of your file (so in the story file, but not actually in the story `add` function).
