### ISSUE TITLE
Material-UI Datatable doesn't populate columns

### ISSUE THREAD

**Issue by Neobii** [VulcanJS/Vulcan#2475]
When using the datatable with Material-ui, the columns do not show up, however, rows show up and when the edit button is clicked, the proper data is populated there.

**Comment by eric-burel** [comment]
Can you please provide some examples so we can reproduce?

**Comment by Neobii** [comment]
Here's the test case: https://github.com/Neobii/Datatable.
One problem to fix right off the bat is the need to use `getCollection` here (https://github.com/VulcanJS/Vulcan/blob/devel/packages/vulcan-ui-material/lib/components/core/Datatable.jsx#L136)

**Comment by Neobii** [comment]
Actually a better test case is just going to `/debug` and having the `vulcan:ui-material` packages added.  The datatable's don't show the columns there.
