### ISSUE TITLE
Update Webpack to at least 4.31

### ISSUE THREAD

**Issue by eric-burel** [VulcanJS/Vulcan#2487]
We have some conflicting issues for Webpack version, necessary to build Storybook:

- This needs us to update Webpack to at least 4.31: https://github.com/storybookjs/storybook/issues/9154
- This locks us to at most 4.28 to support dynamic import: https://github.com/webpack/webpack/issues/8656

But maybe the second issue is now solved so we should try a Webpack update. I've locked some package versions to bypass the first issue but it has to be temporary.

**Comment by chrysillala** [comment]
HI @eric-burel , I would like to work on this issue. Thanks!

**Comment by eric-burel** [comment]
Yep feel free to work on it, but bear in mind that we are releasing [Vulcan Next](https://github.com/VulcanJS/vulcan-next), an updated version of Vulcan based on Next.js. So the Meteor version is considered legacy, and mostly maintained by people that were already using it for their app.

**Comment by chrysillala** [comment]
@eric-burel please check my PR here https://github.com/VulcanJS/Vulcan/pull/2731 and kindly let me know your feedback :) thanks!
