### ISSUE TITLE
Use `meteor npm install` instead of just `npm install`

### ISSUE THREAD

**Issue by williamli** [VulcanJS/Vulcan#2506]
Since Meteor uses a really outdated Node.js version (v8.15.1) while the latest LTS version is already on 12.x, it is highly unlikely that the Node.js version on anyone's computer still defaults to 8.x; it is better for the npm packages to be installed with the Node.js installed with Meteor.js.

Instead of doing a `npm install`, `meteor npm install` should be used in https://github.com/vulcanjs/vulcan#install and https://docs.vulcanjs.org/index.html#Install.

If you don't want to expose `meteor` cli to the user, maybe wrap it around a npm script and call it something like install-dependencies and ask the user to run the following instead:

```
npm run install-dependencies
npm start
```

**Comment by michaeldjeffrey** [comment]
This is exactly what I needed to see. Thank you kind sir.
