### ISSUE TITLE
Pressing 'enter' submits form when editing a textarea

### ISSUE THREAD

**Issue by kevinashworth** [VulcanJS/Vulcan#2520]
If you press 'enter' intending to type a newline when editing the text in a textarea on a SmarForm field, it submits the form instead.

**Comment by kevinashworth** [comment]
Note: I am using Bootstrap and a two-repo install. And there is a `formKeyDown` function in `packages/vulcan-forms/lib/components/Form.jsx` that should swallow the 'enter' events.

**Comment by SachaG** [comment]
Yes it's because of that function: 

```
  formKeyDown = event => {
    if (event.key === 'Enter') {
      event.preventDefault();
      this.submitForm();
    }
  };
```

However now I'm not sure why we need it in the first place since forms submit on enter even without it?

**Comment by SachaG** [comment]
OK fixed it for now I think.

**Comment by kevinashworth** [comment]
Thanks! Works for me now, too.

However, I also had noticed a very similar change in behavior in another form field. It's from the `react-select` library, which uses a `text` form element for input, along with other form elements, in a way that makes them seem like a `select` form element 

Lately, when selecting an entry from the dropdown using my keyboard, the form has submitted -- and as with the `textarea`, this is in a way it didn't used to. The workaround as a user is to only use the mouse. But my fix for now, to allow both keyboard and mouse, is to add to what you did in `Form.jsx`, @sacha:

`if (event.key === 'Enter' && event.target && event.target.type !== 'textarea' && event.target.id.indexOf('react-select') === -1)`

Sharing in case it helps others. And maybe it makes sense to make further fixes to the Vulcan code base. I really don't know if it might be having an impact on others.
