### ISSUE TITLE
Add canFilter instead of using canRead for filters

### ISSUE THREAD

**Issue by SachaG** [VulcanJS/Vulcan#2542]
Add explicit `canFilter` field to schemas instead of relying on `canRead`. Also pass document(s) to `canFilter` if possible.

**Comment by eric-burel** [comment]
Do you have an example where you may need to be able to filter but not to read? Maybe `createdAt` for example if you want to sort by creation date but try to respect privacy?

**Comment by eric-burel** [comment]
A few edge case to define:
- `{ onlyMeCanSee: { canRead:["owners"] }}` => do I implicitly allow filtering in this case, or do I disallow it?
- `{ onlyMeCanSee: { canRead:["guests"] }}` => should "canRead" be prioritary on "canFilter", so that if guests canRead, then they automatically canFilter?

**Comment by eric-burel** [comment]
Cross-posting from Slack:

The behaviour could be:
1. check if the filtering fields are allowed. Keep fields whose status is ambiguous at this point, eg owners or function (as we don't have documents)
2. get documents
3. Rerun the filtering step in JS. Remove documents whose filtering would have been disallowed, now we have the documents (eg documents not owned by the user)

Now it's ok, you have the correct set of documents. I don't see the need for `canFilter` at this point.
