### ISSUE TITLE
SmartForm cannot update nested input fields

### ISSUE THREAD

**Issue by kevinashworth** [VulcanJS/Vulcan#2575]
Addressed by PR #2574 -- this one change to my two-repo install restores my ability to edit nested form fields

**Comment by kevinashworth** [comment]
Some Form changes from a week ago, just before version 1.15.0, are causing a significant error — cannot create or update nested inputs. Nothing happens when I type in these inputs.

I’ve gone backwards in the commit history, and this commit introduces the problem:
https://github.com/VulcanJS/Vulcan/commit/594bf423bc86aa83061b53866f6fcefa6415be03

I hope I have this right:  document — what gets used with this commit — does not contain the updated values. But what was used previously, currentDocument (i.e. the SmartForm’s this.state.currentDocument), does have the necessary values.

In Vulcan-Starter, I see the same thing in example-forms: at the problematic commit, updating of address inputs does not work, but at the commit before, it does. (I removed blackboxNestedArray to get this form to submit.)

In both my app and example-forms, I can update addresses only up to this commit:
https://github.com/VulcanJS/Vulcan/commit/4a216826b1a1876662e0d3c89e20250c55bf5707

**Comment by eric-burel** [comment]
Does the merged PR fixes it for you now in devel?

**Comment by kevinashworth** [comment]
Yes, it's working for me now with the `devel` branch where it stands now (commit 16e06e5888088f660d7726db6d042e4bafcb84c1). I can edit all the fields.

**Comment by eric-burel** [comment]
Thanks a lot then for finding the issue and solving it!
