### ISSUE TITLE
Schema field options not getting a callback with ui-material

### ISSUE THREAD

**Issue by yairtal** [VulcanJS/Vulcan#2578]
Vulcan 1.15
Any callback placed in options at a schema's field will result in an app crash with ui-material.

**Example**
Vulcan-Starter, locale on Users, it gets:
options: () => Locales.map(({ id, label }) => ({ value: id, label })),
This crashes material-ui's Select component with options being undefined

**Comment by SachaG** [comment]
When you say "crash", I assume there must be some kind of error message?

**Comment by yairtal** [comment]
Uncaught TypeError: properties.options is not iterable
    at SelectComponent (Select.jsx:8)

This would fix the issue for example:
options: Locales.map(({ id, label }) => ({ value: id, label }))

**Comment by eric-burel** [comment]
Investigated a bit, this does not seem related to Material UI. Using `options` as a function will also fail in Bootstrap, eg try the `example-forms` and change "categories" options to a function in `packages/example-forms/lib/modules/customers/schema.js`.

**Comment by eric-burel** [comment]
@SachaG this is probably an issue the recent changes, but I can't tell when `options` was called previously, in the case where it's a function and not directly an array

**Comment by eric-burel** [comment]
Progressing, the relevant commit is: "6c8d214f70c0152be5f39bb2239796cd20ad527e" "Do not handle options at form level anymore since we don't have field-specific data yet".

You removed the code that handled option as functions from form, which makes sense when the data are not yet there, but at this point I can't tell where its used. It is supposed to be called by some inner component? It seems to fail the Bootstrap Select and Mui Select at least

**Comment by eric-burel** [comment]
It seems that this new behaviour is already handled correctly in "Autocomplete", but just not in Checkbox groups, radios, and select at this point.

As far as I understand, the `packages/vulcan-forms/lib/components/FormComponentLoader.jsx` will also do some of the work. But it is only present if the user specify a field query explicitely.

**Comment by SachaG** [comment]
Sorry, I found the issue. We just need to add this in `FormComponent`:

```js
    // if there is no query, handle options here; otherwise they will be handled by
    // the FormComponentLoader component
    if (!this.props.query && typeof this.props.options === 'function') {
      fciProps.options = this.props.options(this.props);
    }
```

Like you said I split the logic in two, for when there is a query and when there isn't. But forgot to replace the `options()` function call for the second scenario…

**Comment by SachaG** [comment]
@yairtal I pushed the fix to `devel`, can you let me know if it works for you?

**Comment by yairtal** [comment]
Works fine on my end with both ui-bootstrap and ui-material, thank you!
