### ISSUE TITLE
Smartform shows delete button regardless of collection.permissions.canDelete

### ISSUE THREAD

**Issue by Apollinaire** [VulcanJS/Vulcan#2664]
**Describe the bug**

SmartForm doesn't check the new API collection..permissions.canDelete to tell if it's possible to delete a document, and shows the delete button. 

**To Reproduce**
create a collection with `permissions: { canDelete: [] }`, or without it altogether. Use a smartform to edit a document of that collection, it will show the delete button. If you click it, the server will reject the mutation (thank god) , but the error is not handled. 

**Expected behavior**
The SmartForm checks that the user can delete the document and shows the delete button only if he can.

**Additional context**
v1.16.0 ; current master, commit 27d6f014d3c6c6c7ca756c91566c8452bc50c4a7

**Comment by kevinashworth** [comment]
In [Form.jsx](https://github.com/VulcanJS/Vulcan/blob/c1bfcfc779cf1b1aa0c26d0476b4a1b759df7906/packages/vulcan-forms/lib/components/Form.jsx#L1162), there is this conditional:

`this.props.showRemove && this.props.showDelete`

Why does Vulcan have both `showRemove` and `showDelete`, and what is the difference between them?

**Comment by Apollinaire** [comment]
There has probably been some prop renaming, and the old prop was kept for backwards compatibility.
The docs only mention showRemove, so I guess it's the one to use now.
