### ISSUE TITLE
I can't run the project  Vulcan(Lubuntu)

### ISSUE THREAD

**Issue by matiasclapera** [VulcanJS/Vulcan#2707]
paki@lubuntu-paki:~/Vulcan$ meteor run
[[[[[ ~/Vulcan ]]]]]                         

=> Started proxy.                            
=> Started MongoDB.                          
W20210328-19:59:52.511(-3)? (STDERR) /home/paki/.meteor/packages/meteor-tool/.2.1.0.yuair9.drob++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20210328-19:59:52.747(-3)? (STDERR)                         throw(ex);
W20210328-19:59:52.748(-3)? (STDERR)                         ^
W20210328-19:59:52.748(-3)? (STDERR)
W20210328-19:59:52.749(-3)? (STDERR) Error: Cannot find module './random.js'
W20210328-19:59:52.749(-3)? (STDERR)     at makeMissingError (packages/modules-runtime.js:222:12)
W20210328-19:59:52.749(-3)? (STDERR)     at Module.resolve (packages/modules-runtime.js:228:17)
W20210328-19:59:52.750(-3)? (STDERR)     at Module.moduleLink [as link] (/home/paki/.meteor/packages/modules/.0.16.0.1d4exh9.zo59++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:45:25)
W20210328-19:59:52.750(-3)? (STDERR)     at module (packages/vulcan:lib/lib/modules/index.js:1:1122)
W20210328-19:59:52.750(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20210328-19:59:52.751(-3)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20210328-19:59:52.751(-3)? (STDERR)     at Module.moduleLink [as link] (/home/paki/.meteor/packages/modules/.0.16.0.1d4exh9.zo59++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20210328-19:59:52.751(-3)? (STDERR)     at module (packages/vulcan:lib/lib/server/mutators.js:1:334)
W20210328-19:59:52.751(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20210328-19:59:52.752(-3)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20210328-19:59:52.752(-3)? (STDERR)     at Module.moduleLink [as link] (/home/paki/.meteor/packages/modules/.0.16.0.1d4exh9.zo59++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20210328-19:59:52.752(-3)? (STDERR)     at module (packages/vulcan:lib/lib/server/default_mutations.js:1:115)
W20210328-19:59:52.752(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20210328-19:59:52.752(-3)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20210328-19:59:52.753(-3)? (STDERR)     at Module.moduleLink [as link] (/home/paki/.meteor/packages/modules/.0.16.0.1d4exh9.zo59++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20210328-19:59:52.753(-3)? (STDERR)     at module (packages/vulcan:lib/lib/server/graphql/collection.js:1:142)
W20210328-19:59:52.753(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20210328-19:59:52.753(-3)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20210328-19:59:52.753(-3)? (STDERR)     at Module.moduleLink [as link] (/home/paki/.meteor/packages/modules/.0.16.0.1d4exh9.zo59++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20210328-19:59:52.754(-3)? (STDERR)     at module (packages/vulcan:lib/lib/server/graphql/graphql.js:1:860)
W20210328-19:59:52.754(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20210328-19:59:52.754(-3)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

**Comment by ErikDakoda** [comment]
Do you happen to be on Windows 7 or Windows 10?

**Comment by matiasclapera** [comment]
yes but in lubuntu I can't, I have the same error

**Comment by matiasclapera** [comment]
I have the same error in linux

**Comment by eric-burel** [comment]
It seems that the file is called "Random" and not "random"

**Comment by matiasclapera** [comment]
greetings Eric!

I followed the steps in the tutorial and I can't run the project https://docs.vulcanjs.org/

regards!

**Comment by eric-burel** [comment]
What I find strange is that I see "Vulcan" as the folder name and not "Vulcan Starter", did you clone the starter?

**Comment by matiasclapera** [comment]
If I have installed vulkan and vulcan-starter but both projects give an error, I will try the Two-Repo Install (Optional)

**Comment by matiasclapera** [comment]
Eric I ran Vulcan-Starter :-1: it does not work but this repo https://github.com/VulcanJS/Vulcan if it works...when I run the project it says **Sorry, we couldn't find what you were looking for.**

paki@lubuntu-paki:~/Vulcan-Starter$ npm start 

> vulcan-meteor-start@1.16.1 prestart
> node .vulcan/prestart_vulcan.js

 ___    ___ 
 \\\\  ////
  \\\\////    Vulcan.js
   \\\///    The full-stack React+GraphQL framework
    ────     
>  Happy hacking with Vulcan!
>  The docs are available at: http://docs.vulcanjs.org

> vulcan-meteor-start@1.16.1 start
> meteor --settings settings.json

[[[[[ ~/Vulcan-Starter ]]]]]                  

=> Started proxy.                             
=> Started MongoDB.                           
W20210329-22:39:06.802(-3)? (STDERR) /home/paki/.meteor/packages/meteor-tool/.2.1.0.yuair9.drob++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20210329-22:39:07.019(-3)? (STDERR) 						throw(ex);
W20210329-22:39:07.019(-3)? (STDERR) 						^
W20210329-22:39:07.019(-3)? (STDERR) 
W20210329-22:39:07.020(-3)? (STDERR) ReferenceError: Accounts is not defined
W20210329-22:39:07.020(-3)? (STDERR)     at module (packages/vulcan:accounts/imports/helpers.js:7:36)
W20210329-22:39:07.020(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20210329-22:39:07.020(-3)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20210329-22:39:07.020(-3)? (STDERR)     at Module.moduleLink [as link] (/home/paki/.meteor/packages/modules/.0.16.0.1d4exh9.zo59++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20210329-22:39:07.021(-3)? (STDERR)     at module (packages/vulcan:accounts/imports/accounts_ui.js:1:98)
W20210329-22:39:07.021(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20210329-22:39:07.021(-3)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20210329-22:39:07.021(-3)? (STDERR)     at Module.moduleLink [as link] (/home/paki/.meteor/packages/modules/.0.16.0.1d4exh9.zo59++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:52:22)
W20210329-22:39:07.022(-3)? (STDERR)     at module (packages/vulcan:accounts/main_server.js:1:200)
W20210329-22:39:07.022(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20210329-22:39:07.022(-3)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20210329-22:39:07.022(-3)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20210329-22:39:07.022(-3)? (STDERR)     at /home/paki/Vulcan-Starter/.meteor/local/build/programs/server/packages/vulcan_accounts.js:3266:15
W20210329-22:39:07.022(-3)? (STDERR)     at /home/paki/Vulcan-Starter/.meteor/local/build/programs/server/packages/vulcan_accounts.js:3271:3
W20210329-22:39:07.023(-3)? (STDERR)     at /home/paki/Vulcan-Starter/.meteor/local/build/programs/server/boot.js:401:38
W20210329-22:39:07.023(-3)? (STDERR)     at Array.forEach (<anonymous>)
W20210329-22:39:07.023(-3)? (STDERR)     at /home/paki/Vulcan-Starter/.meteor/local/build/programs/server/boot.js:226:21
W20210329-22:39:07.023(-3)? (STDERR)     at /home/paki/Vulcan-Starter/.meteor/local/build/programs/server/boot.js:464:7
W20210329-22:39:07.023(-3)? (STDERR)     at Function.run (/home/paki/Vulcan-Starter/.meteor/local/build/programs/server/profile.js:280:14)
W20210329-22:39:07.024(-3)? (STDERR)     at /home/paki/Vulcan-Starter/.meteor/local/build/programs/server/boot.js:463:13
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

**Comment by eric-burel** [comment]
it should be fixed in latest vulcan starter
