### ISSUE TITLE
Attempting to implement multiple interfaces on a type causes an error

### ISSUE THREAD

**Issue by arctop-sk** [VulcanJS/Vulcan#2727]
**Describe the bug**
Implementing multiple interfaces on a type in a collection is broken, due to wrong delimiter between interfaces.

**To Reproduce**
add 2 interfaces to a collection, build fails

**Expected behavior**
type is built correctly

Source of the issue is likely here:

export const mainTypeTemplate = ({ typeName, description, interfaces, fields }) =>
  `${description ? `# ${description}` : ''}
type ${typeName} ${interfaces.length ? `implements ${interfaces.join(', ')} ` : ''}{
${convertToGraphQL(fields, '  ')}
}
`;

${interfaces.join(', ')} should be ${interfaces.join(' & ')} 

As multiple interfaces are defined as such:
type Business implements NamedEntity & ValuedEntity {
  name: String
  value: Int
  employeeCount: Int
}

**Comment by eric-burel** [comment]
Yes you're right, could you please try to open a PR so that I can fix this as soon as possible?

**Comment by eric-burel** [comment]
Note that it seems that comma used to work in earlier version of graphql, but the & is the official syntax now

**Comment by arctop-sk** [comment]
https://github.com/VulcanJS/Vulcan/pull/2728
