### ISSUE TITLE
Unable to connect to any application instances.

### ISSUE THREAD

**Issue by downstream1960** [VulcanJS/Vulcan#339]
I tried to deploy telescope onto modulus. After deploying I then went onto the url it gave me and it gave me the message "Unable to connect to any application instances."

**Comment by alexflom2** [comment]
I am following this tutorial to test telescope http://help.modulus.io/customer/portal/articles/1647770-using-meteor-with-modulus

I am getting this error : Unable to connect to any application instances.

And this is the log: /mnt/data/1/node_modules/fibers/future.js:245 throw(ex); ^ TypeError: Cannot read property 'name' of undefined at app/server/migrations.js:469:43 at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:965:1) at [object Object].Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:812:1) at Object.migrationsList.updateUserNames (app/server/migrations.js:462:14) at runMigration (app/server/migrations.js:45:52) at app/server/migrations.js:10:5 at Array.forEach (native) at Function..each..forEach (packages/underscore/underscore.js:105:1) at Meteor.methods.removeMigration.Migrations.remove.name (app/server/migrations.js:9:5) at /mnt/data/1/programs/server/boot.js:229:5 [2015-04-09T22:31:49.395Z] Failed to start application.

Thank you !!

**Comment by SachaG** [comment]
It sounds like a problem with a migration. Do you have old data on the server you're trying to deploy on? Can you try deploying on a new one?

**Comment by alexflom2** [comment]
I am just following the tutorial step by step(creating a new project, database etc), I don't have old server.

**Comment by SachaG** [comment]
Hmm, what if you try again from scratch? Do you get this error every time?

**Comment by acodesmith** [comment]
Little late to this conversation, but I had the same problem. Turned out my password had unsupported characters. Keep your password secure, but don't use crazy characters.
