### ISSUE TITLE
Meteor 0.9.4 - cannot find npm-container

### ISSUE THREAD

**Issue by zbal** [VulcanJS/Vulcan#497]
I used to be able to setup telesc.pe without any issue but suddenly since the new release of meteor 0.9.4, I can't bundle it anymore. It's complaining to not be able to find the npm-container package. 

I can't find that package anywhere, neither on npmjs.org nor atmospherejs.com - so I'm a bit confused...

Any hints?

```
$ meteor build /opt/telescope/ --directory --verbose

Figuring out the best package versions to use. This may take a moment.
Could not resolve the specified constraints for this project:
Error: unknown package: npm-container
```

**Comment by benzel** [comment]
Tolsi, I also had this problem after removing npm-container package. The reason was packages/npm-container directory wasn't removed. I removed it and the problem gone.

**Comment by gentunian** [comment]
Yep, as @benzel said. Removing `<project>/packages/npm-container` removed the error message from appearing.
