### ISSUE TITLE
3 brackets on settings elements

### ISSUE THREAD

**Issue by gldnlab** [VulcanJS/Vulcan#527]
It seems this is in error?

{{{extraCode}}}

https://github.com/TelescopeJS/Telescope/blob/master/client/views/common/layout.html#L18

{{{footerCode}}}

https://github.com/TelescopeJS/Telescope/blob/master/client/views/common/footer.html#L4

**Comment by amelialin** [comment]
@cloudunicorn I was hoping to use Olark and ran into the same issue--did you ever find a way to use JS scripts?
