### ISSUE TITLE
Can't update - deploy fails

### ISSUE THREAD

**Issue by velvet-shark** [VulcanJS/Vulcan#530]
This error still persists:

```
✘ Invoking deployment process: FAILED

 -----------------------------------STDERR-----------------------------------
 o spawn args '-Dmodule_root_dir=/opt/app/tmp/bundle/programs/server/npm/sacha:juice/node_modules/juice/node_modules/jsdom/node_modules/contextify',
 gyp info spawn args '--depth=.',
 gyp info spawn args '--no-parallel',
 gyp info spawn args '--generator-output',
 gyp info spawn args 'build',
 gyp info spawn args '-Goutput_dir=.' ]
 gyp info spawn make
 gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
 gyp info ok
 npm WARN package.json meteor-dev-bundle@0.0.0 No description
 npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
 npm WARN package.json meteor-dev-bundle@0.0.0 No README data
   % Total % Received % Xferd Average Speed Time Time Time Current
                                  Dload Upload Total Spent Left Speed
  0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0curl: (7) Failed to connect to localhost port 80: Connection refused
 Latest deployment failed! Reverted back to the previous version.
 -----------------------------------STDOUT-----------------------------------
 ) Release/obj.target/contextify/src/contextify.o
   SOLINK_MODULE(target) Release/obj.target/contextify.node
   SOLINK_MODULE(target) Release/obj.target/contextify.node: Finished
   COPY Release/contextify.node
 make: Leaving directory `/opt/app/tmp/bundle/programs/server/npm/sacha:juice/node_modules/juice/node_modules/jsdom/node_modules/contextify/build'

 > fibers@1.0.1 install /opt/app/tmp/bundle/programs/server/node_modules/fibers
 > node ./build.js

 `linux-x64-v8-3.14` exists; testing
 Binary is fine; exiting
 underscore@1.5.2 node_modules/underscore

 semver@2.2.1 node_modules/semver

 fibers@1.0.1 node_modules/fibers

 source-map-support@0.2.5 node_modules/source-map-support
 └── source-map@0.1.29 (amdefine@0.1.0)
 Waiting for MongoDB to initialize. (5 minutes)
 connected
 app stop/waiting
 app start/running, process 2738
 Waiting for 15 seconds while app is booting up
 Checking is app booted or not?
 app stop/waiting
 app start/running, process 2768
 ----------------------------------------------------------------------------
```

When I remove juice package, same error, just a different package name.

**Comment by ThangDX** [comment]
Started TaskList: Deploy app 'Tele_VDDA' (linux)
[54.169.253.233] - Uploading bundle
[54.169.253.233] ✔ Uploading bundle: SUCCESS
[54.169.253.233] - Setting up Environment Variables
[54.169.253.233] ✔ Setting up Environment Variables: SUCCESS
[54.169.253.233] - Invoking deployment process
[54.169.253.233] ✘ Invoking deployment process: FAILED
        
        -----------------------------------STDERR-----------------------------------
          '-Dvisibility=default',
        gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.node-gyp/0.10.33',
        gyp info spawn args   '-Dmodule_root_dir=/opt/Tele_VDDA/tmp/bundle/programs/server/npm/sacha:juice/node_modules/juice/node_modules/jsdom/node_modules/contextify',
        gyp info spawn args   '--depth=.',
        gyp info spawn args   '--no-parallel',
        gyp info spawn args   '--generator-output',
        gyp info spawn args   'build',
        gyp info spawn args   '-Goutput_dir=.' ]
        gyp info spawn make
        gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
        gyp info ok 
        npm WARN package.json meteor-dev-bundle@0.0.0 No description
        npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
        npm WARN package.json meteor-dev-bundle@0.0.0 No README data
        
        /usr/lib/node_modules/wait-for-mongo/bin/wait-for-mongo:14
            throw err;
                  ^
        Error: TIMEOUTED_WAIT_FOR_MONGO
            at null._onTimeout (/usr/lib/node_modules/wait-for-mongo/lib/waitForMongo.js:20:14)
            at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
        -----------------------------------STDOUT-----------------------------------
        3456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        wait-for-mongo: failed to connect to [123456:27017]
        ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'Tele_VDDA' (linux)

**Comment by ThangDX** [comment]
I tried to install  Telescope on EC2 and got above error, can someone help me fix that? Thanks

**Comment by jshimko** [comment]
I have Telescope running on EC2 (deployed again last night).  Can you connect to your database with a mongo shell using the same credentials in your mup.json?  Are you trying to use oplog?  If so, what do your env variables look like? (without sharing passwords obviously)

**Comment by SachaG** [comment]
Also, try just giving Mup more time to deploy, and running `mup logs -f`
while you're deploying. Sometimes if there's long migrations Mup cuts off
before the deploy process is done.

**Comment by ThangDX** [comment]
Hi jshimko and SachaG, Thanks for yours help.
1.  yes, I can connect to my database with mongo shell with the same credentials.
2.  I am not using oplog
3. I had increased Mup time to even 6000

Here is my mup logs -f:
 
thangdx@thangdx:~/DeployedApp/VDDA$ mup logs -f

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

[54.255.167.89] Warning: Permanently added '54.255.167.89' (ECDSA) to the list of known hosts.
[54.255.167.89] Exception in callback of async function: Error: failed to connect to [123456:27017]
    at [object Object].<anonymous> (/opt/Tele_VDDA/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:536:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/opt/Tele_VDDA/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:150:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/opt/Tele_VDDA/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:516:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)

Any advice? 

Thanks

**Comment by jshimko** [comment]
If I had to guess (which I do), I'd say your database isn't configured correctly in your mup.json (or there's a JSON syntax error that's causing it to not be read properly)...

`Error: failed to connect to [123456:27017]`

And from your earlier post...

`wait-for-mongo: failed to connect to [123456:27017]`

That looks to me like you're trying to connect to a database at 123456 on port 27017.  Obviously not a valid IP or domain name.

Also FYI, running `mup logs -f` is for watching the current live logs.  It starts by showing you the most recent 15 lines and then monitors for new additions.  You should run that while you're deploying to get more detailed info as it happens.  The other option is to run something like `mup logs -n 300` to get the last 300 lines in the logs.  It won't keep updating live with new logs, but it gets more of the history (what you pasted in your last message doesn't really give a lot of detail).

How about you just post your entire mup.json here and just remove the sensitive info? (passwords, etc)  I suspect that's where your problem is.

**Comment by ThangDX** [comment]
Thank jshimko, below is my mup.json:

{
  // Server authentication info
  "servers": [
    {
      "host": "54.255.167.89",
      "username": "ubuntu",
      //"password": "password"
      // or pem file (ssh based authentication)
      "pem": "/home/thangdx/Downloads/dxt040907.pem"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": false,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.33 by default. Do not use v, only version number.
  "nodeVersion": "0.10.35",

  // Install PhantomJS in the server
  "setupPhantom": true,

  // Application name (No spaces)
  "appName": "Tele_VDDA",

  // Location of app (local directory)
  "app": "/home/thangdx/DeployedApp/VDDA",

  // Configure environment
  "env": {
    "ROOT_URL": "http://qlda.org",
    "MONGO_URL": "mongodb://thang:thang123456@dogen.mongohq.com:10050/qlda_telescope"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 600
}

**Comment by jshimko** [comment]
Assuming your info is all correct, that looks right.  I use pretty much the same setup and it works fine for me.  There has to be a small detail you're missing somewhere.  

Sorry, I don't know what else to recommend at this point other than to make sure you're credentials and URL's are correct.

**Comment by ThangDX** [comment]
Yes, jshimko. I must do something wrong, I will double check every-steps and find out. Thank you very much.

**Comment by ThangDX** [comment]
SUCCESS! after recreating database. Thank you guys for helps.

**Comment by jshimko** [comment]
:+1:

**Comment by applocalizations** [comment]
Hi Gentlemen, I am attempting to deploy Meteor/Telescope (DigitalOcean + Compose.io) but no success. I received the following error message a few seconds ago. Would you have any recommendations? Eric
![bcrypt](https://cloud.githubusercontent.com/assets/5565476/6401055/5300293c-bdb2-11e4-942a-d4b9850b4a01.png)

**Comment by jshimko** [comment]
Pretty sure Meteor requires Node 0.10.3x right now. Looks like you're using the current stable (0.12.0). Try changing your mup config and starting over with a fresh server.

**Comment by applocalizations** [comment]
SUCCESS!!! Shout out to jshimko!

**Comment by jshimko** [comment]
:+1:

**Comment by mhlavacka** [comment]
I have the same problem as you guys had. Could somebody help me out ?

[45.55.144.173] ✘ Invoking deployment process: FAILED
	
	-----------------------------------STDERR-----------------------------------
	p ERR! cwd /opt/comicsprout/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt
	gyp ERR! node -v v0.12.2
	gyp ERR! node-gyp -v v1.0.3
	gyp ERR! not ok 
	npm WARN package.json meteor-dev-bundle@0.0.0 No description
	npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
	npm WARN package.json meteor-dev-bundle@0.0.0 No README data
	child_process: customFds option is deprecated, use stdio instead.
	../src/coroutine.cc: In function ‘void* find_thread_id_key(void*)’:
	../src/coroutine.cc:90:3: warning: ‘thread_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
	   if (tls == thread_id) {
	   ^
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
	Latest deployment failed! Reverted back to the previous version.
	-----------------------------------STDOUT-----------------------------------
	rget) Release/obj.target/fibers.node: Finished
	  COPY Release/fibers.node
	make: Leaving directory `/opt/comicsprout/tmp/bundle/programs/server/node_modules/fibers/build'
	Installed in `/opt/comicsprout/tmp/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.28/fibers.node`
	underscore@1.5.2 node_modules/underscore
	
	eachline@2.3.3 node_modules/eachline
	└── type-of@2.0.1
	
	chalk@0.5.1 node_modules/chalk
	├── escape-string-regexp@1.0.3
	├── ansi-styles@1.1.0
	├── supports-color@0.2.0
	├── has-ansi@0.1.0 (ansi-regex@0.2.1)
	└── strip-ansi@0.3.0 (ansi-regex@0.2.1)
	
	semver@4.1.0 node_modules/semver
	
	source-map-support@0.2.8 node_modules/source-map-support
	└── source-map@0.1.32 (amdefine@0.1.0)
	
	fibers@1.0.5 node_modules/fibers
	Waiting for MongoDB to initialize. (5 minutes)
	connected
	comicsprout stop/waiting
	comicsprout start/running, process 12827
	Waiting for 30 seconds while app is booting up
	Checking is app booted or not?
	comicsprout stop/waiting
	comicsprout start/running, process 12930

**Comment by valgalin** [comment]
Please try node version 0.10.36 in your mup.json file, then run 'mup setup' again, and 'mup deploy'

**Comment by mhlavacka** [comment]
I have it by default. The following is my mup.json : 
{
  // Server authentication info
  "servers": [
    {
      "host": "myhost",
      "username": "root",
      //"password": "mypassword"
      // or pem file (ssh based authentication)
      "pem": "~/.ssh/id_rsa"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": false,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  "nodeVersion": "0.10.36",

  // Install PhantomJS in the server
  "setupPhantom": true,

  // Application name (No spaces)
  "appName": "comicsprout",

  // Location of app (local directory)
  "app": "/Users/matejhlavacka/Meteor/Comic/",

  // Configure environment
  "env": {
    "ROOT_URL": "http://comicsprout.com",
    "MONGO_URL": "mongodb://username:userpassword@dogen.mongohq.com:10062/telescope-comic-sproute"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 30
}

**Comment by mhlavacka** [comment]
Now that you pointed that out, I realized I installed Node.js while setting up droplet in DigitalOcean. So it's already-preinstalled. Have to figure out the way how to undo that.

**Comment by applocalizations** [comment]
I would simply create a fresh droplet.

2015-04-13 2:46 GMT-07:00 Matej Hlavacka <notifications@github.com>:

**Comment by valgalin** [comment]
Yes, create a fresh Ubuntu 14.04 installation, with nothing pre-installed.

**Comment by mhlavacka** [comment]
Thanks for advice, it's working now :+1:

**Comment by applocalizations** [comment]
No problem.

2015-04-16 0:55 GMT-07:00 Matej Hlavacka <notifications@github.com>:

**Comment by SpaceG** [comment]
Hello! I'm trying to Install Telescope app to Digital Ocean Server! Which Server Ubuntu need i to take for the I)nstallation? and which version of the Telescope App? 

i get this back : 

`Started TaskList: Deploy app 'MyTestApp' (linux)
[107.170.144.234] - Uploading bundle
[107.170.144.234] - Uploading bundle: SUCCESS
[107.170.144.234] - Setting up Environment Variables
[107.170.144.234] - Setting up Environment Variables: SUCCESS
[107.170.144.234] - Invoking deployment process
[107.170.144.234] x Invoking deployment process: FAILED
	
	-----------------------------------STDERR-----------------------------------
	npm WARN package.json meteor-dev-bundle@0.0.0 No description
	npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
	npm WARN package.json meteor-dev-bundle@0.0.0 No README data
	npm WARN cannot run in wd meteor-dev-bundle@0.0.0 node npm-rebuild.js (wd=/opt/MyTestApp/tmp/bundle/programs/server)
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
	Latest deployment failed! Reverted back to the previous version.
	-----------------------------------STDOUT-----------------------------------
	x@0.2.1 node_modules/ansi-regex
	
	ansi-styles@1.1.0 node_modules/ansi-styles
	
	chalk@0.5.1 node_modules/chalk
	
	escape-string-regexp@1.0.5 node_modules/escape-string-regexp
	
	has-ansi@0.1.0 node_modules/has-ansi
	
	strip-ansi@0.3.0 node_modules/strip-ansi
	
	supports-color@0.2.0 node_modules/supports-color
	
	eachline@2.3.3 node_modules/eachline
	
	type-of@2.0.1 node_modules/type-of
	
	amdefine@1.0.0 node_modules/amdefine
	
	asap@2.0.3 node_modules/asap
	
	underscore@1.5.2 node_modules/underscore
	
	meteor-promise@0.5.1 node_modules/meteor-promise
	
	promise@7.0.4 node_modules/promise
	
	source-map-support@0.3.2 node_modules/source-map-support
	
	semver@4.1.0 node_modules/semver
	
	source-map@0.1.32 node_modules/source-map
	
	fibers@1.0.8 node_modules/fibers
	Waiting for MongoDB to initialize. (5 minutes)
	connected
	MyTestApp stop/waiting
	MyTestApp start/running, process 1690
	Waiting for 30 seconds while app is booting up
	Checking is app booted or not?
	MyTestApp stop/waiting
	MyTestApp start/running, process 1794
	----------------------------------------------------------------------------
Space-Odysseys-Mac-Pro:MyTestApp cyberspace$ 


and my mup setup set file is here :


`{
  // Server authentication info
  "servers": [
    {
       "host": "107.175.144.234",
      "username": "root",
      "password": "Password",
      // or pem file (ssh based authentication)
      // WARNING: Keys protected by a passphrase are not supported
      //"pem": "~/.ssh/id_rsa"
      // Also, for non-standard ssh port use this
      //"sshOptions": { "port" : 49154 },
      // server specific environment variables
      "env": {}
    }
  ],

  // Install MongoDB on the server. Does not destroy the local MongoDB on future setups
  "setupMongo": false,

  // Application name (no spaces).
  "appName": "MyTestApp",

    // Install PhantomJS in the server
  "setupPhantom": true,

  // Location of app (local directory). This can reference '~' as the users home directory.
  // i.e., "app": "~/Meteor/my-app",
  // This is the same as the line below.
  "app": ".",

  // Configure environment
  // ROOT_URL must be set to your correct domain (https or http)
  "env": {
    "PORT": 80,
    "ROOT_URL": "http://www.MyTestApp.com",
    "MONGO_URL": "mongodb://MyTestApp:password@aws-us-east-1-portal.18.dblayer.com:12189,aws-us-east-1-portal.19.dblayer.com:11519/MyTestApp?ssl=true"

  },

  // Meteor Up checks if the app comes online just after the deployment.
  // Before mup checks that, it will wait for the number of seconds configured below.
  "deployCheckWaitTime": 30,

  // show a progress bar while uploading. 
  // Make it false when you deploy using a CI box.
  "enableUploadProgressBar": true
}`
`


where is the problem att, therefor it was installed the sails.js ... maybe i need a fresh droplet from digital ocean.? 

thanks for help!

**Comment by SachaG** [comment]
Yes, I think a fresh droplet might work better. Although right now there's also some issues with Mup, so you could also try Heroku or Galaxy.
