### ISSUE TITLE
MongoError: Can't canonicalize query

### ISSUE THREAD

**Issue by juanbzz** [VulcanJS/Vulcan#534]
I'm getting this error on Kadira, any thoughts?

`
Trace Explorer : Exception in queued task: MongoError: Can't canonicalize query: BadValue bad sort specification at Object.Future.wait (/opt/frontendsapp/app/programs/server/node_modules/fibers/future.js:326:15) at _.extend._nextObject (packages/mongo/mongo_driver.js:858) at _.extend.forEach (packages/mongo/mongo_driver.js:892) at _.extend.getRawObjects (packages/mongo/mongo_driver.js:941) at _.extend._pollMongo (packages/mongo/polling_observe_driver.js:144) at Object.task (packages/mongo/polling_observe_driver.js:85) at _.extend._run (packages/meteor/fiber_helpers.js:145) at packages/meteor/fiber_helpers.js:123 - - - - - at Object.toError (/opt/frontendsapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/utils.js:110:11) at /opt/frontendsapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/cursor.js:686:54 at Cursor.close (/opt/frontendsapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/cursor.js:969:5) at commandHandler (/opt/frontendsapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/cursor.js:686:21) at /opt/frontendsapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/db.js:1843:9 at Server.Base._callHandler (/opt/frontendsapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/base.js:445:41) at /opt/frontendsapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:468:18 at MongoReply.parseBody (/opt/frontendsapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5) at null. (/opt/frontendsapp/app/programs/server/npm/mongo/node_modules/mongodb/lib/mongodb/connection/server.js:426:20) at emit (events.js:95:17) (0ms)
`

**Comment by richkuo** [comment]
this could be due to a data issue - can't sort against null values
