### ISSUE TITLE
external settings file?

### ISSUE THREAD

**Issue by dcsan** [VulcanJS/Vulcan#561]
rather than configuring via the Admin login, I'd suggest using a meteor settings.json file
usually we have this per env, ie testing.json / production.json / development.json 

if need be these keys can be .gitignore'd but for deployment it feels not quite reproducible to type these into a login box each time.

http://docs.meteor.com/#/full/meteor_settings

**Comment by corneadoug** [comment]
I feel like I'm digging some old issues but better ask my question here.
I was looking into Telescope, and I wanted to use settings.json to be able to make a clean deployment.
The documentation wasn't giving much details. So I made a settings.json file and used it with ```meteor run --settings settings.json``` However I Can't see any of those settings being applied not showed in the admin settings section.

**Comment by SachaG** [comment]
The settings won't show up in the admin section, but they should still be in effect. You can test it by doing `Settings.get("nameOfSetting")` in the browser console.

**Comment by corneadoug** [comment]
Yes, it seems its just the forms that are not showing the current values. Thanks
