### ISSUE TITLE
Related to Kadira issues

### ISSUE THREAD

**Issue by neilborromeo** [VulcanJS/Vulcan#566]
Hi,

Happen to see https://github.com/TelescopeJS/Telescope/issues/535 but it seems I got a different scenario.. Error log shows:

=> Started proxy.  
=> Started MongoDB.  
I20141127-22:55:08.474(8)? [MailChimp] Error: MailChimp Options have not been set in your settings.json file.
W20141127-22:55:10.178(8)? (STDERR) 
W20141127-22:55:10.180(8)? (STDERR) /home/cliper/Desktop/meteor.projects/answers/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:3014
W20141127-22:55:10.181(8)? (STDERR)     throw err;  
W20141127-22:55:10.181(8)? (STDERR)           ^
W20141127-22:55:10.181(8)? (STDERR) TypeError: Cannot call method 'extend' of undefined
W20141127-22:55:10.181(8)? (STDERR)     at app/lib/router/comments.js:3:52
W20141127-22:55:10.182(8)? (STDERR)     at app/lib/router/comments.js:47:3
W20141127-22:55:10.182(8)? (STDERR)     at /home/cliper/Desktop/meteor.projects/answers/.meteor/local/build/programs/server/boot.js:168:10
W20141127-22:55:10.182(8)? (STDERR)     at Array.forEach (native)
W20141127-22:55:10.182(8)? (STDERR)     at Function._.each._.forEach (/home/cliper/.meteor/packages/meteor-tool/.1.0.35.ftql1v++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20141127-22:55:10.182(8)? (STDERR)     at /home/cliper/Desktop/meteor.projects/answers/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 7
I20141127-22:55:21.295(8)? [MailChimp] Error: MailChimp Options have not been set in your settings.json file.
W20141127-22:55:21.824(8)? (STDERR) 
W20141127-22:55:21.825(8)? (STDERR) /home/cliper/Desktop/meteor.projects/answers/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:3014
W20141127-22:55:21.826(8)? (STDERR)     throw err;  
W20141127-22:55:21.826(8)? (STDERR)           ^
W20141127-22:55:21.828(8)? (STDERR) TypeError: Cannot call method 'extend' of undefined
W20141127-22:55:21.828(8)? (STDERR)     at app/lib/router/comments.js:3:52
W20141127-22:55:21.829(8)? (STDERR)     at app/lib/router/comments.js:47:3
W20141127-22:55:21.829(8)? (STDERR)     at /home/cliper/Desktop/meteor.projects/answers/.meteor/local/build/programs/server/boot.js:168:10
W20141127-22:55:21.829(8)? (STDERR)     at Array.forEach (native)
W20141127-22:55:21.830(8)? (STDERR)     at Function._.each._.forEach (/home/cliper/.meteor/packages/meteor-tool/.1.0.35.ftql1v++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20141127-22:55:21.830(8)? (STDERR)     at /home/cliper/Desktop/meteor.projects/answers/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 7
I20141127-22:55:32.837(8)? [MailChimp] Error: MailChimp Options have not been set in your settings.json file.
W20141127-22:55:33.357(8)? (STDERR) 
W20141127-22:55:33.358(8)? (STDERR) /home/cliper/Desktop/meteor.projects/answers/.meteor/local/build/programs/server/packages/meteorhacks_kadira.js:3014
W20141127-22:55:33.358(8)? (STDERR)     throw err;  
W20141127-22:55:33.360(8)? (STDERR)           ^
W20141127-22:55:33.361(8)? (STDERR) TypeError: Cannot call method 'extend' of undefined
W20141127-22:55:33.361(8)? (STDERR)     at app/lib/router/comments.js:3:52
W20141127-22:55:33.362(8)? (STDERR)     at app/lib/router/comments.js:47:3
W20141127-22:55:33.363(8)? (STDERR)     at /home/cliper/Desktop/meteor.projects/answers/.meteor/local/build/programs/server/boot.js:168:10
W20141127-22:55:33.363(8)? (STDERR)     at Array.forEach (native)
W20141127-22:55:33.363(8)? (STDERR)     at Function._.each._.forEach (/home/cliper/.meteor/packages/meteor-tool/.1.0.35.ftql1v++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20141127-22:55:33.363(8)? (STDERR)     at /home/cliper/Desktop/meteor.projects/answers/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 7
=> Your application is crashing. Waiting for file change.

--- List of packages before the update --
accounts-base                1.1.2  A user account system
accounts-facebook            1.0.2  Login service for Facebook accounts
accounts-google              1.0.2  Login service for Google accounts
accounts-password            1.0.4  Password support for accounts
accounts-twitter             1.0.2  Login service for Twitter accounts
accounts-ui                  1.1.3  Simple templates to add login widgets to an app
aldeed:autoform              4.0.2\* Easily create forms with automatic insert and update, and automatic reactive validation.
aldeed:collection2           2.2.0  Automatic validation of insert and update operations on the client and server.
aldeed:simple-schema         1.1.0  A simple schema validation object with reactivity. Used by collection2 and autoform.
backbone                     1.0.0  A minimalist client-side MVC framework
bengott:avatar               0.6.0  Consolidated user avatar template (twitter, facebook, gravatar, etc.)
ccan:cssreset                1.0.0  Eric Meyer's Reset CSS v.2.0 (http://meyerweb.com/eric/tools/css/reset/)
chuangbo:marked              0.3.5  A markdown parser and compiler. Built for speed.
cmather:handlebars-server    2.0.0  Allows handlebars templates to be defined on the server in .handlebars files
djedi:sanitize-html          1.3.0  Sanitze HTML
email                        1.0.4  Send email messages
ewall:foundation             5.4.7  Foundation by ZURB - an advanced responsive web framework
iron:router                  1.0.1\* Routing specifically designed for Meteor
jparker:gravatar             0.3.0  Simple package to use gravatar images
matb33:collection-hooks      0.7.6  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
meteorhacks:fast-render      1.2.1\* Render initial page 2-10 times faster by sending data with HTML
meteorhacks:npm              1.2.1  Use npm modules with your Meteor App
meteorhacks:subs-manager     1.2.0\* Subscriptions Manager for Meteor
mrt:cookies                  0.3.0  Basic cookies support for client
mrt:jquery-hotkeys           0.0.1  Meteor Packaged jquery-hotkeys (from John Resig https://github.com/jeresig/jquery.hotkeys)
mrt:mailchimp                0.4.0  A Meteor wrapper for MailChimp API
mrt:moment                   2.8.1  Moment.js, a JavaScript date library for dates, packaged for Meteor. See http://momentjs.com.
npm-container                1.0.0  Contains all your npm dependencies
percolatestudio:synced-cron  1.0.0  Allows you to define and run scheduled jobs across multiple servers.
rajit:bootstrap3-datepicker  1.3.1  Meteor packaging of eternicode/bootstrap-datepicker for Bootstrap 3
sacha:juice                  0.1.0  Juice wrapper package
sacha:spin                   2.0.4  Simple spinner package for Meteor
service-configuration        1.0.2  Manage the configuration for third-party services
spiderable                   1.0.5  Makes the application crawlable to web spiders
standard-app-packages        1.0.3  Moved to meteor-platform
tap:i18n                     1.2.1  A comprehensive internationalization solution for Meteor
telescope-api                0.0.0  Telescope API package
telescope-base               0.0.0  Telescope base package
telescope-daily              0.0.0  Telescope daily view
telescope-email              0.2.9  Telescope email package
telescope-i18n               0.0.0  Telescope i18n package
telescope-kadira             0.1.0  Telescope Kadira package
telescope-lib                0.2.9  Telescope library package
telescope-module-embedly     0.2.9  Telescope Embedly module package
telescope-module-share       0.0.0  Telescope share module package
telescope-newsletter         0.1.0  Telescope email newsletter package
telescope-notifications      0.1.0  Telescope notifications package
telescope-rss                0.0.0  Telescope RSS package
telescope-search             0.0.0  Telescope search package
telescope-tags               0.0.0  Telescope tags package
telescope-theme-base         0.0.0  Telescope base theme
telescope-theme-hubble       0.0.0  Telescope Hubble theme
telescope-update-prompt      0.1.0  Telescope update prompt package.
useraccounts:unstyled        1.2.3\* Accounts Templates unstyled.

-- Logs when updating the packages --
- New versions of these packages are available! Run 'meteor update' to try
  to update those packages to their latest versions. If your packages cannot be
  updated further, try typing meteor add <package>@<newVersion> to see more
  information.
  cliper@office2:~/answers$ meteor update
  This project is already at Meteor 1.0, the latest release.
  upgraded useraccounts:unstyled from version 1.2.3 to version 1.3.2
  upgraded meteorhacks:subs-manager from version 1.2.0 to version 1.2.2
  upgraded aldeed:autoform from version 4.0.2 to version 4.0.7
  upgraded iron:router from version 1.0.1 to version 1.0.3
  upgraded useraccounts:core from version 1.2.3 to version 1.3.2
  upgraded iron:middleware-stack from version 1.0.0 to version 1.0.3
  upgraded iron:controller from version 1.0.0 to version 1.0.3
  upgraded meteorhacks:fast-render from version 1.2.1 to version 2.0.2

The following packages have been updated to new versions that are not backwards compatible:
meteorhacks:fast-render  (1.2.1->2.0.2) Render you app even before the DDP connection comes live. - magic?

**Comment by applocalizations** [comment]
I ran: meteor add telescope-module-share but none of the buttons are appearing in the posts. What do you recommend?

**Comment by jshimko** [comment]
First, I recommend posting questions like this in a relevant issue.  (your question has nothing to do with Kadira)

The social links are [hidden by default][1] with CSS.  You just need to override that.

[1]: https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-theme-hubble/lib/client/scss/modules/_posts.scss#L355-L357

**Comment by applocalizations** [comment]
Hi Jeremy,

I thank you for sharing this link with me. I posted the question on
stackoverflow here:
https://stackoverflow.com/questions/29082336/telescope-module-share-does-not-yield-buttons
Do you know how to override the defaults? Should I override those defaults
in the css file in the telescope-custom package?

Eric

2015-03-16 9:39 GMT-07:00 Jeremy Shimko <notifications@github.com>:

**Comment by jshimko** [comment]
Again, please open a new issue.
