### ISSUE TITLE
CSS native is not working :(

### ISSUE THREAD

**Issue by Purexo** [VulcanJS/Vulcan#593]
Hi, I've install Telescope on my VPS. and I have no CSS
![](http://i.imgur.com/kFlM2Qm.png)

[my Telescope](http://purexo.eu:3000/)

I tried on master and release v0.9.11, and I've the same matter.

**Comment by thanhluu** [comment]
@purexo What is your OS version? According to my thoughts, your system is not supported GLIBC_2.14
Check this: http://unix.stackexchange.com/questions/176489/how-to-update-glibc-to-2-14-in-centos-6-5
