### ISSUE TITLE
PhantomJS bugs?

### ISSUE THREAD

**Issue by jasonify** [VulcanJS/Vulcan#597]
spiderable: phantomjs failed: { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' }

Can I turn this off?

I do have phantom installed but I would rather turn it off for now.

Is there a way to turn off console.logs on the server too (and only to file maybe?)

**Comment by Kikobeats** [comment]
about this, I was to remove `spiderable` because every day crash is app. `spiderable`gets all the cpu and UNIX have to kill the process.
