### ISSUE TITLE
Vote comments down

### ISSUE THREAD

**Issue by mazing** [VulcanJS/Vulcan#600]
Why is it not possible to vote posts down like I can vote comments down?

The option to vote down makes the site more consistent. People are searching for the vote down button because they can vote down comments. Besides, it seems stupid not to make it possible when the functionality is already implemented.

**Comment by lisacheng** [comment]
Hi I'm trying to implement the downvote function, if I change the following in callback.js - is there anywhere else I should use this callback function?

 Meteor.users.update({_id: userId}, {$inc: {"telescope.postCount": 1}});
  Telescope.upvoteItem(Posts, post, postAuthor);
  Telescope.downvoteItem(Posts, post, postAuthor);
  return post;
}
Telescope.callbacks.add("postSubmitAsync", afterPostSubmitOperations);
