### ISSUE TITLE
Social Share button is not visible in desktop

### ISSUE THREAD

**Issue by qasimzee** [VulcanJS/Vulcan#663]
Hi,

Social Sharing buttons are not visible on desktop but they are ok in mobile. Do I have to configure something to make them work for desktop ?

Same is the case on http://demo2.telescopeapp.org/

**Comment by rodclarke** [comment]
"In this specific case, adding a few lines of CSS should be enough to make the share button appear everywhere :)"

Is there any chance of a blog post on how to do this? which file to edit and where?

**Comment by jshimko** [comment]
@rodclarke 

```css
.post-share {
    display: block; 
}
```
...in the extra css box on the settings page

**Comment by rodclarke** [comment]
thanks very much! @jshimko

**Comment by capensisma** [comment]
@SachaG would like please adding it to master repo 
```
.post-share {
    display: block; 
}
```
plenty of people are expecting this to be displayed
thanks

**Comment by SachaG** [comment]
Yeah I'll have to think about it.
